// lib/data/datasources/local/hive/hive_datasource.dart

import 'dart:async';
import 'package:hive_flutter/hive_flutter.dart';
import '../models/user_hive_model.dart';
import '../models/health_profile_hive_model.dart';
import '../models/training_program_hive_model.dart';
import '../models/weekly_workout_hive_model.dart';
import '../models/workout_log_hive_model.dart';
import 'hive_boxes.dart';

/// Hive datasource — handles all direct Hive operations.
/// No business logic — only CRUD operations.
class HiveDatasource {
  HiveDatasource._();

  /// Initialize Hive and register all adapters.
  static Future<void> initialize() async {
    await Hive.initFlutter();

    // Register adapters (generated by hive_generator)
    Hive.registerAdapter(UserHiveModelAdapter());
    Hive.registerAdapter(HealthProfileHiveModelAdapter());
    Hive.registerAdapter(TrainingProgramHiveModelAdapter());
    Hive.registerAdapter(WeeklyWorkoutHiveModelAdapter());
    Hive.registerAdapter(WorkoutLogHiveModelAdapter());

    // Open boxes
    await Hive.openBox<UserHiveModel>(HiveBoxes.users);
    await Hive.openBox<HealthProfileHiveModel>(HiveBoxes.healthProfiles);
    await Hive.openBox<TrainingProgramHiveModel>(HiveBoxes.trainingPrograms);
    await Hive.openBox<WeeklyWorkoutHiveModel>(HiveBoxes.weeklyWorkouts);
    await Hive.openBox<WorkoutLogHiveModel>(HiveBoxes.workoutLogs);
    await Hive.openBox(HiveBoxes.currentUser);
  }

  // ============================================================
  // USER
  // ============================================================

  static Future<void> saveUser(UserHiveModel user) async {
    await HiveBoxes.usersBox.put(user.uid, user);
  }

  static UserHiveModel? getUser(String uid) {
    return HiveBoxes.usersBox.get(uid);
  }

  static List<UserHiveModel> getAllUsers() {
    return HiveBoxes.usersBox.values.toList();
  }

  static Future<void> deleteUser(String uid) async {
    await HiveBoxes.usersBox.delete(uid);
  }

  static Stream<BoxEvent> watchUser(String uid) {
    return HiveBoxes.usersBox.watch(key: uid);
  }

  static Stream<BoxEvent> watchCurrentUser() {
    return HiveBoxes.currentUserBox.watch();
  }

  // ============================================================
  // CURRENT USER
  // ============================================================

  static Future<void> setCurrentUserId(String? uid) async {
    if (uid == null) {
      await HiveBoxes.currentUserBox.delete('uid');
    } else {
      await HiveBoxes.currentUserBox.put('uid', uid);
    }
  }

  static String? getCurrentUserId() {
    return HiveBoxes.currentUserBox.get('uid') as String?;
  }

  // ============================================================
  // HEALTH PROFILE
  // ============================================================

  static Future<void> saveHealthProfile(HealthProfileHiveModel profile) async {
    await HiveBoxes.healthProfilesBox.put(profile.userId, profile);
  }

  static HealthProfileHiveModel? getHealthProfile(String userId) {
    return HiveBoxes.healthProfilesBox.get(userId);
  }

  static Future<void> deleteHealthProfile(String userId) async {
    await HiveBoxes.healthProfilesBox.delete(userId);
  }

  static Stream<BoxEvent> watchHealthProfile(String userId) {
    return HiveBoxes.healthProfilesBox.watch(key: userId);
  }

  // ============================================================
  // TRAINING PROGRAM
  // ============================================================

  static Future<void> saveTrainingProgram(
      TrainingProgramHiveModel program) async {
    await HiveBoxes.trainingProgramsBox.put(program.id, program);
  }

  static TrainingProgramHiveModel? getTrainingProgram(String id) {
    return HiveBoxes.trainingProgramsBox.get(id);
  }

  static List<TrainingProgramHiveModel> getUserTrainingPrograms(String userId) {
    return HiveBoxes.trainingProgramsBox.values
        .where((p) => p.userId == userId)
        .toList();
  }

  static TrainingProgramHiveModel? getCurrentTrainingProgram(String userId) {
    final programs = getUserTrainingPrograms(userId);
    if (programs.isEmpty) return null;

    programs.sort((a, b) => b.createdAt.compareTo(a.createdAt));
    return programs.firstWhere(
      (p) => p.expiresAt.isAfter(DateTime.now()),
      orElse: () => programs.first,
    );
  }

  static Future<void> deleteTrainingProgram(String id) async {
    await HiveBoxes.trainingProgramsBox.delete(id);
  }

  static Stream<BoxEvent> watchTrainingPrograms() {
    return HiveBoxes.trainingProgramsBox.watch();
  }

  // ============================================================
  // WEEKLY WORKOUT
  // ============================================================

  static Future<void> saveWeeklyWorkout(WeeklyWorkoutHiveModel weekly) async {
    await HiveBoxes.weeklyWorkoutsBox.put(weekly.id, weekly);
  }

  static WeeklyWorkoutHiveModel? getWeeklyWorkout(String id) {
    return HiveBoxes.weeklyWorkoutsBox.get(id);
  }

  static List<WeeklyWorkoutHiveModel> getProgramWeeklyWorkouts(
      String programId) {
    return HiveBoxes.weeklyWorkoutsBox.values
        .where((w) => w.programId == programId)
        .toList()
      ..sort((a, b) => a.weekNumber.compareTo(b.weekNumber));
  }

  static WeeklyWorkoutHiveModel? getCurrentWeeklyWorkout(String programId) {
    final workouts = getProgramWeeklyWorkouts(programId);
    return workouts.where((w) => w.isActive).toList().lastOrNull;
  }

  static Future<void> deleteWeeklyWorkout(String id) async {
    await HiveBoxes.weeklyWorkoutsBox.delete(id);
  }

  static Stream<BoxEvent> watchWeeklyWorkouts() {
    return HiveBoxes.weeklyWorkoutsBox.watch();
  }

  // ============================================================
  // WORKOUT LOG
  // ============================================================

  static Future<void> saveWorkoutLog(WorkoutLogHiveModel log) async {
    await HiveBoxes.workoutLogsBox.put(log.id, log);
  }

  static WorkoutLogHiveModel? getWorkoutLog(String id) {
    return HiveBoxes.workoutLogsBox.get(id);
  }

  static List<WorkoutLogHiveModel> getUserWorkoutLogs(String userId) {
    return HiveBoxes.workoutLogsBox.values
        .where((l) => l.userId == userId)
        .toList()
      ..sort((a, b) => b.savedAt.compareTo(a.savedAt));
  }

  static List<WorkoutLogHiveModel> getLogsForDay(String userId, DateTime day) {
    final start = DateTime(day.year, day.month, day.day);
    final end = start.add(const Duration(days: 1));

    return HiveBoxes.workoutLogsBox.values
        .where((l) =>
            l.userId == userId &&
            l.savedAt.isAfter(start) &&
            l.savedAt.isBefore(end))
        .toList()
      ..sort((a, b) => b.savedAt.compareTo(a.savedAt));
  }

  static Future<void> deleteWorkoutLog(String id) async {
    await HiveBoxes.workoutLogsBox.delete(id);
  }

  static Stream<BoxEvent> watchWorkoutLogs() {
    return HiveBoxes.workoutLogsBox.watch();
  }

  // ============================================================
  // CLEAR ALL
  // ============================================================

  static Future<void> clearAll() async {
    await HiveBoxes.usersBox.clear();
    await HiveBoxes.healthProfilesBox.clear();
    await HiveBoxes.trainingProgramsBox.clear();
    await HiveBoxes.weeklyWorkoutsBox.clear();
    await HiveBoxes.workoutLogsBox.clear();
    await HiveBoxes.currentUserBox.clear();
  }
}
