// lib/data/datasources/local/hive/hive_datasource.dart

import 'dart:async';
import 'package:hive_flutter/hive_flutter.dart';
import '../models/user_hive_model.dart';
import '../models/health_profile_hive_model.dart';
import '../models/training_program_hive_model.dart';
import '../models/workout_log_hive_model.dart';
import '../models/meal_hive_model.dart';
import '../models/nutrition_profile_hive_model.dart';
import '../models/nutrition_plan_hive_model.dart';
import '../models/recovery_status_hive_model.dart';
import '../models/daily_checkin_hive_model.dart';
import 'hive_boxes.dart';

/// Hive datasource — handles all direct Hive operations.
/// No business logic — only CRUD operations.
class HiveDatasource {
  HiveDatasource._();

  /// Initialize Hive and register all adapters.
  static Future<void> initialize() async {
    await Hive.initFlutter();

    // Register adapters (generated by hive_generator)
    Hive.registerAdapter(UserHiveModelAdapter());
    Hive.registerAdapter(HealthProfileHiveModelAdapter());
    Hive.registerAdapter(TrainingProgramHiveModelAdapter());
    Hive.registerAdapter(WorkoutLogHiveModelAdapter());
    Hive.registerAdapter(NutritionProfileHiveModelAdapter());
    Hive.registerAdapter(MealHiveModelAdapter());
    Hive.registerAdapter(NutritionPlanHiveModelAdapter());
    Hive.registerAdapter(RecoveryStatusHiveModelAdapter());
    Hive.registerAdapter(DailyCheckInHiveModelAdapter());

    // Open boxes
    await Hive.openBox<UserHiveModel>(HiveBoxes.users);
    await Hive.openBox<HealthProfileHiveModel>(HiveBoxes.healthProfiles);
    await Hive.openBox<TrainingProgramHiveModel>(HiveBoxes.trainingPrograms);
    await Hive.openBox<WorkoutLogHiveModel>(HiveBoxes.workoutLogs);
    await Hive.openBox(HiveBoxes.currentUser);
    await Hive.openBox<NutritionProfileHiveModel>(HiveBoxes.nutritionProfiles);
    await Hive.openBox<NutritionPlanHiveModel>(HiveBoxes.nutritionPlans);
    await Hive.openBox<RecoveryStatusHiveModel>(HiveBoxes.recoveryStatuses);
    await Hive.openBox<DailyCheckInHiveModel>(HiveBoxes.dailyCheckIns);
  }

  // ============================================================
  // USER
  // ============================================================

  static Future<void> saveUser(UserHiveModel user) async {
    await HiveBoxes.usersBox.put(user.uid, user);
  }

  static UserHiveModel? getUser(String uid) {
    return HiveBoxes.usersBox.get(uid);
  }

  static List<UserHiveModel> getAllUsers() {
    return HiveBoxes.usersBox.values.toList();
  }

  static Future<void> deleteUser(String uid) async {
    await HiveBoxes.usersBox.delete(uid);
  }

  static Stream<BoxEvent> watchUser(String uid) {
    return HiveBoxes.usersBox.watch(key: uid);
  }

  static Stream<BoxEvent> watchCurrentUser() {
    return HiveBoxes.currentUserBox.watch();
  }

  // ============================================================
  // CURRENT USER
  // ============================================================

  static Future<void> setCurrentUserId(String? uid) async {
    if (uid == null) {
      await HiveBoxes.currentUserBox.delete('uid');
    } else {
      await HiveBoxes.currentUserBox.put('uid', uid);
    }
  }

  static String? getCurrentUserId() {
    return HiveBoxes.currentUserBox.get('uid') as String?;
  }

  // ============================================================
  // HEALTH PROFILE
  // ============================================================

  static Future<void> saveHealthProfile(HealthProfileHiveModel profile) async {
    await HiveBoxes.healthProfilesBox.put(profile.userId, profile);
  }

  static HealthProfileHiveModel? getHealthProfile(String userId) {
    return HiveBoxes.healthProfilesBox.get(userId);
  }

  static Future<void> deleteHealthProfile(String userId) async {
    await HiveBoxes.healthProfilesBox.delete(userId);
  }

  static Stream<BoxEvent> watchHealthProfile(String userId) {
    return HiveBoxes.healthProfilesBox.watch(key: userId);
  }

  // ============================================================
  // TRAINING PROGRAM
  // ============================================================

  static Future<void> saveTrainingProgram(
      TrainingProgramHiveModel program) async {
    await HiveBoxes.trainingProgramsBox.put(program.id, program);
  }

  static TrainingProgramHiveModel? getTrainingProgram(String id) {
    return HiveBoxes.trainingProgramsBox.get(id);
  }

  static List<TrainingProgramHiveModel> getUserTrainingPrograms(String userId) {
    return HiveBoxes.trainingProgramsBox.values
        .where((p) => p.userId == userId)
        .toList();
  }

  static TrainingProgramHiveModel? getCurrentTrainingProgram(String userId) {
    final programs = getUserTrainingPrograms(userId);
    if (programs.isEmpty) return null;

    programs.sort((a, b) => b.createdAt.compareTo(a.createdAt));
    return programs.firstWhere(
      (p) => p.expiresAt.isAfter(DateTime.now()),
      orElse: () => programs.first,
    );
  }

  static Future<void> deleteTrainingProgram(String id) async {
    await HiveBoxes.trainingProgramsBox.delete(id);
  }

  static Stream<BoxEvent> watchTrainingPrograms() {
    return HiveBoxes.trainingProgramsBox.watch();
  }

  // ============================================================
  // WORKOUT LOG
  // ============================================================

  static Future<void> saveWorkoutLog(WorkoutLogHiveModel log) async {
    await HiveBoxes.workoutLogsBox.put(log.id, log);
  }

  static WorkoutLogHiveModel? getWorkoutLog(String id) {
    return HiveBoxes.workoutLogsBox.get(id);
  }

  static List<WorkoutLogHiveModel> getUserWorkoutLogs(String userId) {
    return HiveBoxes.workoutLogsBox.values
        .where((l) => l.userId == userId)
        .toList()
      ..sort((a, b) => b.savedAt.compareTo(a.savedAt));
  }

  static List<WorkoutLogHiveModel> getLogsForDay(String userId, DateTime day) {
    final start = DateTime(day.year, day.month, day.day);
    final end = start.add(const Duration(days: 1));

    return HiveBoxes.workoutLogsBox.values
        .where((l) =>
            l.userId == userId &&
            l.savedAt.isAfter(start) &&
            l.savedAt.isBefore(end))
        .toList()
      ..sort((a, b) => b.savedAt.compareTo(a.savedAt));
  }

  static Future<void> deleteWorkoutLog(String id) async {
    await HiveBoxes.workoutLogsBox.delete(id);
  }

  static Stream<BoxEvent> watchWorkoutLogs() {
    return HiveBoxes.workoutLogsBox.watch();
  }

  // ============================================================
  // NUTRITION PROFILE
  // ============================================================

  static Future<void> saveNutritionProfile(
    NutritionProfileHiveModel profile,
  ) async {
    await HiveBoxes.nutritionProfilesBox.put(profile.userId, profile);
  }

  static NutritionProfileHiveModel? getNutritionProfile(String userId) {
    return HiveBoxes.nutritionProfilesBox.get(userId);
  }

  static Future<void> deleteNutritionProfile(String userId) async {
    await HiveBoxes.nutritionProfilesBox.delete(userId);
  }

  // ============================================================
  // NUTRITION PLAN
  // ============================================================

  static Future<void> saveNutritionPlan(NutritionPlanHiveModel plan) async {
    await HiveBoxes.nutritionPlansBox.put(plan.id, plan);
  }

  static NutritionPlanHiveModel? getNutritionPlan(String id) {
    return HiveBoxes.nutritionPlansBox.get(id);
  }

  static Future<void> deleteNutritionPlansForUser(String userId) async {
    final keys = HiveBoxes.nutritionPlansBox.values
        .where((p) => p.userId == userId)
        .map((p) => p.id)
        .toList();
    for (final key in keys) {
      await HiveBoxes.nutritionPlansBox.delete(key);
    }
  }

  // ============================================================
  // RECOVERY STATUS
  // ============================================================

  static String _recoveryKey(String userId, DateTime date) {
    final day = DateTime(date.year, date.month, date.day);
    return '${userId}_${day.year.toString().padLeft(4, '0')}-${day.month.toString().padLeft(2, '0')}-${day.day.toString().padLeft(2, '0')}';
  }

  static Future<void> saveRecoveryStatus(RecoveryStatusHiveModel model) async {
    final key = _recoveryKey(model.userId, model.date);
    await HiveBoxes.recoveryStatusesBox.put(key, model);
  }

  static RecoveryStatusHiveModel? getRecoveryStatus(
      String userId, DateTime date) {
    return HiveBoxes.recoveryStatusesBox.get(_recoveryKey(userId, date));
  }

  static RecoveryStatusHiveModel? getLatestRecoveryStatus(String userId) {
    final entries = HiveBoxes.recoveryStatusesBox.values
        .where((m) => m.userId == userId)
        .toList()
      ..sort((a, b) => b.date.compareTo(a.date));
    return entries.isEmpty ? null : entries.first;
  }

  // ============================================================
  // DAILY CHECK-IN
  // ============================================================

  static Future<void> saveDailyCheckIn(DailyCheckInHiveModel model) async {
    final key = _recoveryKey(model.userId, model.date);
    await HiveBoxes.dailyCheckInsBox.put(key, model);
  }

  static DailyCheckInHiveModel? getDailyCheckIn(
      String userId, DateTime date) {
    return HiveBoxes.dailyCheckInsBox.get(_recoveryKey(userId, date));
  }

  static List<DailyCheckInHiveModel> getDailyCheckIns(
    String userId, {
    DateTime? from,
    DateTime? to,
  }) {
    return HiveBoxes.dailyCheckInsBox.values.where((m) {
      if (m.userId != userId) return false;
      if (from != null && m.date.isBefore(from)) return false;
      if (to != null && m.date.isAfter(to)) return false;
      return true;
    }).toList()
      ..sort((a, b) => b.date.compareTo(a.date));
  }

  static String _skipKey(String userId, DateTime date) =>
      'checkin_skipped_${_recoveryKey(userId, date)}';

  static Future<void> markCheckInSkipped(String userId, DateTime date) async {
    await HiveBoxes.currentUserBox.put(_skipKey(userId, date), true);
  }

  static bool isCheckInSkipped(String userId, DateTime date) {
    return HiveBoxes.currentUserBox.get(_skipKey(userId, date)) == true;
  }

  static Future<void> clearCheckInSkipped(String userId, DateTime date) async {
    await HiveBoxes.currentUserBox.delete(_skipKey(userId, date));
  }

  // ============================================================
  // CLEAR ALL
  // ============================================================

  static Future<void> clearAll() async {
    await HiveBoxes.usersBox.clear();
    await HiveBoxes.healthProfilesBox.clear();
    await HiveBoxes.trainingProgramsBox.clear();
    await HiveBoxes.workoutLogsBox.clear();
    await HiveBoxes.nutritionProfilesBox.clear();
    await HiveBoxes.nutritionPlansBox.clear();
    await HiveBoxes.recoveryStatusesBox.clear();
    await HiveBoxes.dailyCheckInsBox.clear();
    await HiveBoxes.currentUserBox.clear();
  }
}
