// lib/data/datasources/local/hive/hive_datasource.dart

import 'dart:async';
import 'package:hive_flutter/hive_flutter.dart';
import '../models/user_hive_model.dart';
import '../models/health_profile_hive_model.dart';
import '../models/training_program_hive_model.dart';
import '../models/workout_log_hive_model.dart';
import '../models/meal_hive_model.dart';
import '../models/nutrition_profile_hive_model.dart';
import '../models/nutrition_plan_hive_model.dart';
import '../models/recovery_status_hive_model.dart';
import '../models/daily_checkin_hive_model.dart';
import '../models/progress_snapshot_hive_model.dart';
import '../models/conversation_hive_model.dart';
import '../models/coach_cache_hive_model.dart';
import '../models/blood_pressure_hive_model.dart';
import '../models/blood_glucose_hive_model.dart';
import '../models/hydration_log_hive_model.dart';
import '../models/mental_wellness_hive_model.dart';
import '../models/habit_hive_model.dart';
import '../models/habit_log_hive_model.dart';
import '../models/logged_food_portion_hive_model.dart';
import '../models/nutrition_log_hive_model.dart';
import 'hive_boxes.dart';

/// Hive datasource — handles all direct Hive operations.
/// No business logic — only CRUD operations.
class HiveDatasource {
  HiveDatasource._();

  /// Initialize Hive and register all adapters.
  static Future<void> initialize() async {
    await Hive.initFlutter();

    // Register adapters (generated by hive_generator)
    Hive.registerAdapter(UserHiveModelAdapter());
    Hive.registerAdapter(HealthProfileHiveModelAdapter());
    Hive.registerAdapter(TrainingProgramHiveModelAdapter());
    Hive.registerAdapter(WorkoutLogHiveModelAdapter());
    Hive.registerAdapter(NutritionProfileHiveModelAdapter());
    Hive.registerAdapter(MealHiveModelAdapter());
    Hive.registerAdapter(NutritionPlanHiveModelAdapter());
    Hive.registerAdapter(RecoveryStatusHiveModelAdapter());
    Hive.registerAdapter(DailyCheckInHiveModelAdapter());
    Hive.registerAdapter(ProgressSnapshotHiveModelAdapter());
    Hive.registerAdapter(ConversationHiveModelAdapter());
    Hive.registerAdapter(CoachCacheHiveModelAdapter());
    Hive.registerAdapter(BloodPressureHiveModelAdapter());
    Hive.registerAdapter(BloodGlucoseHiveModelAdapter());
    Hive.registerAdapter(HydrationLogHiveModelAdapter());
    Hive.registerAdapter(MentalWellnessHiveModelAdapter());
    Hive.registerAdapter(HabitHiveModelAdapter());
    Hive.registerAdapter(HabitLogHiveModelAdapter());
    Hive.registerAdapter(LoggedFoodPortionHiveModelAdapter());
    Hive.registerAdapter(NutritionLogHiveModelAdapter());

    // Open boxes
    await Hive.openBox<UserHiveModel>(HiveBoxes.users);
    await Hive.openBox<HealthProfileHiveModel>(HiveBoxes.healthProfiles);
    await Hive.openBox<TrainingProgramHiveModel>(HiveBoxes.trainingPrograms);
    await Hive.openBox<WorkoutLogHiveModel>(HiveBoxes.workoutLogs);
    await Hive.openBox(HiveBoxes.currentUser);
    await Hive.openBox<NutritionProfileHiveModel>(HiveBoxes.nutritionProfiles);
    await Hive.openBox<NutritionPlanHiveModel>(HiveBoxes.nutritionPlans);
    await Hive.openBox<RecoveryStatusHiveModel>(HiveBoxes.recoveryStatuses);
    await Hive.openBox<DailyCheckInHiveModel>(HiveBoxes.dailyCheckIns);
    await Hive.openBox<ProgressSnapshotHiveModel>(HiveBoxes.progressSnapshots);
    await Hive.openBox<ConversationHiveModel>(HiveBoxes.conversations);
    await Hive.openBox<CoachCacheHiveModel>(HiveBoxes.coachCache);
    await Hive.openBox<BloodPressureHiveModel>(HiveBoxes.bloodPressure);
    await Hive.openBox<BloodGlucoseHiveModel>(HiveBoxes.bloodGlucose);
    await Hive.openBox<HydrationLogHiveModel>(HiveBoxes.hydrationLogs);
    await Hive.openBox<MentalWellnessHiveModel>(HiveBoxes.mentalWellness);
    await Hive.openBox<HabitHiveModel>(HiveBoxes.habits);
    await Hive.openBox<HabitLogHiveModel>(HiveBoxes.habitLogs);
    await Hive.openBox<NutritionLogHiveModel>(HiveBoxes.nutritionLogs);
  }

  // ============================================================
  // USER
  // ============================================================

  static Future<void> saveUser(UserHiveModel user) async {
    await HiveBoxes.usersBox.put(user.uid, user);
  }

  static UserHiveModel? getUser(String uid) {
    return HiveBoxes.usersBox.get(uid);
  }

  static List<UserHiveModel> getAllUsers() {
    return HiveBoxes.usersBox.values.toList();
  }

  static Future<void> deleteUser(String uid) async {
    await HiveBoxes.usersBox.delete(uid);
  }

  static Stream<BoxEvent> watchUser(String uid) {
    return HiveBoxes.usersBox.watch(key: uid);
  }

  static Stream<BoxEvent> watchCurrentUser() {
    return HiveBoxes.currentUserBox.watch();
  }

  // ============================================================
  // CURRENT USER
  // ============================================================

  static Future<void> setCurrentUserId(String? uid) async {
    if (uid == null) {
      await HiveBoxes.currentUserBox.delete('uid');
    } else {
      await HiveBoxes.currentUserBox.put('uid', uid);
    }
  }

  static String? getCurrentUserId() {
    return HiveBoxes.currentUserBox.get('uid') as String?;
  }

  // ============================================================
  // HEALTH PROFILE
  // ============================================================

  static Future<void> saveHealthProfile(HealthProfileHiveModel profile) async {
    await HiveBoxes.healthProfilesBox.put(profile.userId, profile);
  }

  static HealthProfileHiveModel? getHealthProfile(String userId) {
    return HiveBoxes.healthProfilesBox.get(userId);
  }

  static Future<void> deleteHealthProfile(String userId) async {
    await HiveBoxes.healthProfilesBox.delete(userId);
  }

  static Stream<BoxEvent> watchHealthProfile(String userId) {
    return HiveBoxes.healthProfilesBox.watch(key: userId);
  }

  // ============================================================
  // TRAINING PROGRAM
  // ============================================================

  static Future<void> saveTrainingProgram(
      TrainingProgramHiveModel program) async {
    await HiveBoxes.trainingProgramsBox.put(program.id, program);
  }

  static TrainingProgramHiveModel? getTrainingProgram(String id) {
    return HiveBoxes.trainingProgramsBox.get(id);
  }

  static List<TrainingProgramHiveModel> getUserTrainingPrograms(String userId) {
    return HiveBoxes.trainingProgramsBox.values
        .where((p) => p.userId == userId)
        .toList();
  }

  static TrainingProgramHiveModel? getCurrentTrainingProgram(String userId) {
    final programs = getUserTrainingPrograms(userId);
    if (programs.isEmpty) return null;

    programs.sort((a, b) => b.createdAt.compareTo(a.createdAt));
    return programs.firstWhere(
      (p) => p.expiresAt.isAfter(DateTime.now()),
      orElse: () => programs.first,
    );
  }

  static Future<void> deleteTrainingProgram(String id) async {
    await HiveBoxes.trainingProgramsBox.delete(id);
  }

  static Stream<BoxEvent> watchTrainingPrograms() {
    return HiveBoxes.trainingProgramsBox.watch();
  }

  // ============================================================
  // WORKOUT LOG
  // ============================================================

  static Future<void> saveWorkoutLog(WorkoutLogHiveModel log) async {
    await HiveBoxes.workoutLogsBox.put(log.id, log);
  }

  static WorkoutLogHiveModel? getWorkoutLog(String id) {
    return HiveBoxes.workoutLogsBox.get(id);
  }

  static List<WorkoutLogHiveModel> getUserWorkoutLogs(String userId) {
    return HiveBoxes.workoutLogsBox.values
        .where((l) => l.userId == userId)
        .toList()
      ..sort((a, b) => b.savedAt.compareTo(a.savedAt));
  }

  static List<WorkoutLogHiveModel> getLogsForDay(String userId, DateTime day) {
    final start = DateTime(day.year, day.month, day.day);
    final end = start.add(const Duration(days: 1));

    return HiveBoxes.workoutLogsBox.values
        .where((l) =>
            l.userId == userId &&
            l.savedAt.isAfter(start) &&
            l.savedAt.isBefore(end))
        .toList()
      ..sort((a, b) => b.savedAt.compareTo(a.savedAt));
  }

  static Future<void> deleteWorkoutLog(String id) async {
    await HiveBoxes.workoutLogsBox.delete(id);
  }

  static Stream<BoxEvent> watchWorkoutLogs() {
    return HiveBoxes.workoutLogsBox.watch();
  }

  // ============================================================
  // NUTRITION PROFILE
  // ============================================================

  static Future<void> saveNutritionProfile(
    NutritionProfileHiveModel profile,
  ) async {
    await HiveBoxes.nutritionProfilesBox.put(profile.userId, profile);
  }

  static NutritionProfileHiveModel? getNutritionProfile(String userId) {
    return HiveBoxes.nutritionProfilesBox.get(userId);
  }

  static Future<void> deleteNutritionProfile(String userId) async {
    await HiveBoxes.nutritionProfilesBox.delete(userId);
  }

  // ============================================================
  // NUTRITION PLAN
  // ============================================================

  static Future<void> saveNutritionPlan(NutritionPlanHiveModel plan) async {
    await HiveBoxes.nutritionPlansBox.put(plan.id, plan);
  }

  static NutritionPlanHiveModel? getNutritionPlan(String id) {
    return HiveBoxes.nutritionPlansBox.get(id);
  }

  static Future<void> deleteNutritionPlansForUser(String userId) async {
    final keys = HiveBoxes.nutritionPlansBox.values
        .where((p) => p.userId == userId)
        .map((p) => p.id)
        .toList();
    for (final key in keys) {
      await HiveBoxes.nutritionPlansBox.delete(key);
    }
  }

  // ============================================================
  // RECOVERY STATUS
  // ============================================================

  static String _recoveryKey(String userId, DateTime date) {
    final day = DateTime(date.year, date.month, date.day);
    return '${userId}_${day.year.toString().padLeft(4, '0')}-${day.month.toString().padLeft(2, '0')}-${day.day.toString().padLeft(2, '0')}';
  }

  static Future<void> saveRecoveryStatus(RecoveryStatusHiveModel model) async {
    final key = _recoveryKey(model.userId, model.date);
    await HiveBoxes.recoveryStatusesBox.put(key, model);
  }

  static RecoveryStatusHiveModel? getRecoveryStatus(
      String userId, DateTime date) {
    return HiveBoxes.recoveryStatusesBox.get(_recoveryKey(userId, date));
  }

  static RecoveryStatusHiveModel? getLatestRecoveryStatus(String userId) {
    final entries = HiveBoxes.recoveryStatusesBox.values
        .where((m) => m.userId == userId)
        .toList()
      ..sort((a, b) => b.date.compareTo(a.date));
    return entries.isEmpty ? null : entries.first;
  }

  // ============================================================
  // DAILY CHECK-IN
  // ============================================================

  static Future<void> saveDailyCheckIn(DailyCheckInHiveModel model) async {
    final key = _recoveryKey(model.userId, model.date);
    await HiveBoxes.dailyCheckInsBox.put(key, model);
  }

  static DailyCheckInHiveModel? getDailyCheckIn(
      String userId, DateTime date) {
    return HiveBoxes.dailyCheckInsBox.get(_recoveryKey(userId, date));
  }

  static List<DailyCheckInHiveModel> getDailyCheckIns(
    String userId, {
    DateTime? from,
    DateTime? to,
  }) {
    return HiveBoxes.dailyCheckInsBox.values.where((m) {
      if (m.userId != userId) return false;
      if (from != null && m.date.isBefore(from)) return false;
      if (to != null && m.date.isAfter(to)) return false;
      return true;
    }).toList()
      ..sort((a, b) => b.date.compareTo(a.date));
  }

  static String _skipKey(String userId, DateTime date) =>
      'checkin_skipped_${_recoveryKey(userId, date)}';

  static Future<void> markCheckInSkipped(String userId, DateTime date) async {
    await HiveBoxes.currentUserBox.put(_skipKey(userId, date), true);
  }

  static bool isCheckInSkipped(String userId, DateTime date) {
    return HiveBoxes.currentUserBox.get(_skipKey(userId, date)) == true;
  }

  static Future<void> clearCheckInSkipped(String userId, DateTime date) async {
    await HiveBoxes.currentUserBox.delete(_skipKey(userId, date));
  }

  // ============================================================
  // PROGRESS SNAPSHOT
  // ============================================================

  static String _progressKey(String userId, DateTime computedAt) {
    final day = DateTime(
      computedAt.year,
      computedAt.month,
      computedAt.day,
      computedAt.hour,
      computedAt.minute,
    );
    return '${userId}_progress_${day.toIso8601String()}';
  }

  static Future<void> saveProgressSnapshot(
      ProgressSnapshotHiveModel model) async {
    final key = _progressKey(model.userId, model.computedAt);
    await HiveBoxes.progressSnapshotsBox.put(key, model);
  }

  static ProgressSnapshotHiveModel? getProgressSnapshot(
    String userId,
    DateTime computedAt,
  ) {
    return HiveBoxes.progressSnapshotsBox.get(
      _progressKey(userId, computedAt),
    );
  }

  static ProgressSnapshotHiveModel? getLatestProgressSnapshot(String userId) {
    final entries = HiveBoxes.progressSnapshotsBox.values
        .where((m) => m.userId == userId)
        .toList()
      ..sort((a, b) => b.computedAt.compareTo(a.computedAt));
    return entries.isEmpty ? null : entries.first;
  }

  static List<ProgressSnapshotHiveModel> getProgressSnapshots(
    String userId, {
    DateTime? from,
    DateTime? to,
  }) {
    return HiveBoxes.progressSnapshotsBox.values.where((m) {
      if (m.userId != userId) return false;
      if (from != null && m.computedAt.isBefore(from)) return false;
      if (to != null && m.computedAt.isAfter(to)) return false;
      return true;
    }).toList()
      ..sort((a, b) => b.computedAt.compareTo(a.computedAt));
  }

  // ============================================================
  // COACH CONVERSATIONS
  // ============================================================

  static Future<void> saveConversation(ConversationHiveModel model) async {
    await HiveBoxes.conversationsBox.put(model.id, model);
  }

  static ConversationHiveModel? getLatestConversation(String userId) {
    final entries = HiveBoxes.conversationsBox.values
        .where((m) => m.userId == userId)
        .toList()
      ..sort((a, b) => b.updatedAt.compareTo(a.updatedAt));
    return entries.isEmpty ? null : entries.first;
  }

  static Future<void> deleteConversation(String id) async {
    await HiveBoxes.conversationsBox.delete(id);
  }

  // ============================================================
  // COACH CACHE
  // ============================================================

  static Future<void> saveCoachCache(CoachCacheHiveModel model) async {
    await HiveBoxes.coachCacheBox.put(model.id, model);
  }

  static CoachCacheHiveModel? getCoachCache(String id) {
    return HiveBoxes.coachCacheBox.get(id);
  }

  // ============================================================
  // HEALTH PLATFORM
  // ============================================================

  static Future<void> saveBloodPressure(BloodPressureHiveModel model) async {
    await HiveBoxes.bloodPressureBox.put(model.id, model);
  }

  static BloodPressureHiveModel? getLatestBloodPressure(String userId) {
    final list = HiveBoxes.bloodPressureBox.values
        .where((e) => e.userId == userId)
        .toList()
      ..sort((a, b) => b.measuredAt.compareTo(a.measuredAt));
    return list.isEmpty ? null : list.first;
  }

  static List<BloodPressureHiveModel> getBloodPressureHistory(String userId) {
    return HiveBoxes.bloodPressureBox.values
        .where((e) => e.userId == userId)
        .toList()
      ..sort((a, b) => b.measuredAt.compareTo(a.measuredAt));
  }

  static Future<void> deleteBloodPressure(String id) async {
    await HiveBoxes.bloodPressureBox.delete(id);
  }

  static Future<void> saveBloodGlucose(BloodGlucoseHiveModel model) async {
    await HiveBoxes.bloodGlucoseBox.put(model.id, model);
  }

  static BloodGlucoseHiveModel? getLatestBloodGlucose(String userId) {
    final list = HiveBoxes.bloodGlucoseBox.values
        .where((e) => e.userId == userId)
        .toList()
      ..sort((a, b) => b.measuredAt.compareTo(a.measuredAt));
    return list.isEmpty ? null : list.first;
  }

  static List<BloodGlucoseHiveModel> getBloodGlucoseHistory(String userId) {
    return HiveBoxes.bloodGlucoseBox.values
        .where((e) => e.userId == userId)
        .toList()
      ..sort((a, b) => b.measuredAt.compareTo(a.measuredAt));
  }

  static Future<void> deleteBloodGlucose(String id) async {
    await HiveBoxes.bloodGlucoseBox.delete(id);
  }

  static Future<void> saveHydrationLog(HydrationLogHiveModel model) async {
    await HiveBoxes.hydrationLogsBox.put(model.id, model);
  }

  static List<HydrationLogHiveModel> getHydrationLogs(String userId) {
    return HiveBoxes.hydrationLogsBox.values
        .where((e) => e.userId == userId)
        .toList()
      ..sort((a, b) => b.loggedAt.compareTo(a.loggedAt));
  }

  static Future<void> deleteHydrationLog(String id) async {
    await HiveBoxes.hydrationLogsBox.delete(id);
  }

  static Future<void> saveMentalWellness(MentalWellnessHiveModel model) async {
    await HiveBoxes.mentalWellnessBox.put(model.id, model);
  }

  static MentalWellnessHiveModel? getMentalWellnessForDay(
    String userId,
    DateTime day,
  ) {
    final key = DateTime(day.year, day.month, day.day);
    for (final e in HiveBoxes.mentalWellnessBox.values) {
      if (e.userId != userId) continue;
      final d = DateTime(e.date.year, e.date.month, e.date.day);
      if (d == key) return e;
    }
    return null;
  }

  static List<MentalWellnessHiveModel> getMentalWellnessHistory(
    String userId,
  ) {
    return HiveBoxes.mentalWellnessBox.values
        .where((e) => e.userId == userId)
        .toList()
      ..sort((a, b) => b.date.compareTo(a.date));
  }

  static Future<void> deleteMentalWellness(String id) async {
    await HiveBoxes.mentalWellnessBox.delete(id);
  }

  static Future<void> saveHabit(HabitHiveModel model) async {
    await HiveBoxes.habitsBox.put(model.id, model);
  }

  static List<HabitHiveModel> getHabits(String userId) {
    return HiveBoxes.habitsBox.values
        .where((e) => e.userId == userId)
        .toList()
      ..sort((a, b) => a.name.compareTo(b.name));
  }

  static Future<void> deleteHabit(String id) async {
    await HiveBoxes.habitsBox.delete(id);
  }

  static Future<void> saveHabitLog(HabitLogHiveModel model) async {
    await HiveBoxes.habitLogsBox.put(model.id, model);
  }

  static List<HabitLogHiveModel> getHabitLogs(String userId) {
    return HiveBoxes.habitLogsBox.values
        .where((e) => e.userId == userId)
        .toList()
      ..sort((a, b) => b.date.compareTo(a.date));
  }

  static Future<void> deleteHabitLog(String id) async {
    await HiveBoxes.habitLogsBox.delete(id);
  }

  static Future<void> saveNutritionLog(NutritionLogHiveModel model) async {
    await HiveBoxes.nutritionLogsBox.put(model.id, model);
  }

  static List<NutritionLogHiveModel> getNutritionLogs(String userId) {
    return HiveBoxes.nutritionLogsBox.values
        .where((e) => e.userId == userId)
        .toList()
      ..sort((a, b) => b.loggedAt.compareTo(a.loggedAt));
  }

  static List<NutritionLogHiveModel> getNutritionLogsForDay(
    String userId,
    DateTime day,
  ) {
    final key = DateTime(day.year, day.month, day.day);
    return HiveBoxes.nutritionLogsBox.values
        .where((e) {
          if (e.userId != userId) return false;
          final d = DateTime(e.loggedAt.year, e.loggedAt.month, e.loggedAt.day);
          return d == key;
        })
        .toList()
      ..sort((a, b) => a.loggedAt.compareTo(b.loggedAt));
  }

  static Future<void> deleteNutritionLog(String id) async {
    await HiveBoxes.nutritionLogsBox.delete(id);
  }

  static Future<void> deleteNutritionLogsForUser(String userId) async {
    final keys = HiveBoxes.nutritionLogsBox.values
        .where((e) => e.userId == userId)
        .map((e) => e.id)
        .toList();
    await HiveBoxes.nutritionLogsBox.deleteAll(keys);
  }

  // ============================================================
  // CLEAR ALL
  // ============================================================

  static Future<void> clearAll() async {
    await HiveBoxes.usersBox.clear();
    await HiveBoxes.healthProfilesBox.clear();
    await HiveBoxes.trainingProgramsBox.clear();
    await HiveBoxes.workoutLogsBox.clear();
    await HiveBoxes.nutritionProfilesBox.clear();
    await HiveBoxes.nutritionPlansBox.clear();
    await HiveBoxes.recoveryStatusesBox.clear();
    await HiveBoxes.dailyCheckInsBox.clear();
    await HiveBoxes.progressSnapshotsBox.clear();
    await HiveBoxes.conversationsBox.clear();
    await HiveBoxes.coachCacheBox.clear();
    await HiveBoxes.bloodPressureBox.clear();
    await HiveBoxes.bloodGlucoseBox.clear();
    await HiveBoxes.hydrationLogsBox.clear();
    await HiveBoxes.mentalWellnessBox.clear();
    await HiveBoxes.habitsBox.clear();
    await HiveBoxes.habitLogsBox.clear();
    await HiveBoxes.nutritionLogsBox.clear();
    await HiveBoxes.currentUserBox.clear();
  }
}
