import 'package:gymgenius/domain/enums/exports.dart';
import 'package:gymgenius/engines/workout_engine/shared/exercise_pool_entry.dart';

const List<ExercisePoolEntry> legsHomemadeExercises = [
  ExercisePoolEntry(
    id: 'legs_homemade_goblet_squat',
    name: 'Homemade Weight Goblet Squat',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.homemadeWeights,
    targetMuscles: [MuscleGroup.quadriceps, MuscleGroup.glutes],
    secondaryMuscles: [MuscleGroup.hamstrings],
    usesWeight: true,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Hold a weight at chest level, squat down as if sitting in a chair, then stand back up.',
  ),
  ExercisePoolEntry(
    id: 'legs_homemade_lunge',
    name: 'Homemade Weight Lunge',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.homemadeWeights,
    targetMuscles: [MuscleGroup.quadriceps, MuscleGroup.glutes],
    secondaryMuscles: [MuscleGroup.hamstrings],
    usesWeight: true,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Hold weights at your sides, step forward into a lunge, lower your back knee, then push back up.',
  ),
  ExercisePoolEntry(
    id: 'legs_homemade_step_up',
    name: 'Homemade Weight Step-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.homemadeWeights,
    targetMuscles: [MuscleGroup.quadriceps, MuscleGroup.glutes],
    secondaryMuscles: [],
    usesWeight: true,
    movementPattern: MovementPattern.lunge,  // remplacé step par lunge
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Stand in front of a sturdy box/step, hold weights, step up onto the box, then step back down.',
  ),
  ExercisePoolEntry(
    id: 'legs_homemade_rdl',
    name: 'Homemade Weight Romanian Deadlift',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.homemadeWeights,
    targetMuscles: [MuscleGroup.hamstrings, MuscleGroup.glutes],
    secondaryMuscles: [MuscleGroup.back],
    usesWeight: true,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Stand with feet hip-width apart, hold weights in front, hinge at hips lowering the weights down your shins, then return to standing.',
  ),
  ExercisePoolEntry(
    id: 'legs_homemade_hip_thrust',
    name: 'Homemade Weight Hip Thrust',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.homemadeWeights,
    targetMuscles: [MuscleGroup.glutes],
    secondaryMuscles: [MuscleGroup.hamstrings],
    usesWeight: true,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Sit on the floor with upper back against a bench, place weights on your hips, drive hips upward, squeeze glutes.',
  ),
];
