import 'package:hive_flutter/hive_flutter.dart';
import 'package:gymgenius/models/hive/user_model.dart';
import 'package:gymgenius/models/hive/training_program_model.dart';
import 'package:gymgenius/models/hive/weekly_workout_model.dart';
import 'package:gymgenius/models/hive/workout_log_model.dart';
import 'package:gymgenius/services/logger_service.dart';

/// Central service for managing Hive database operations
///
/// IMPORTANT: This service operates in SINGLE USER MODE.
/// When a NEW user (different UID) is saved, all existing user data is automatically deleted.
class DatabaseService {
  static const String _usersBox = 'users';
  static const String _programsBox = 'programs';
  static const String _weeklyBox = 'weekly_workouts';
  static const String _workoutLogsBox = 'workout_logs';
  static const String _currentUserBox = 'current_user';

  static DatabaseService? _instance;
  static DatabaseService get instance {
    _instance ??= DatabaseService._();
    return _instance!;
  }

  DatabaseService._();

  Box<UserModel> get users => _users;
  Box<TrainingProgramModel> get programs => _programs;
  Box<WeeklyWorkoutModel> get weeklyWorkouts => _weekly;
  Box<WorkoutLogModel> get workoutLogs => _workoutLogs;

  /// Initialize Hive and register adapters
  static Future<void> initialize() async {
    await Hive.initFlutter();

    // Register adapters (generated by hive_generator)
    Hive.registerAdapter(UserModelAdapter());
    Hive.registerAdapter(TrainingProgramModelAdapter());
    Hive.registerAdapter(WeeklyWorkoutModelAdapter());
    Hive.registerAdapter(WorkoutLogModelAdapter());

    // Open boxes
    await Hive.openBox<UserModel>(_usersBox);
    await Hive.openBox<TrainingProgramModel>(_programsBox);
    await Hive.openBox<WeeklyWorkoutModel>(_weeklyBox);
    await Hive.openBox<WorkoutLogModel>(_workoutLogsBox);
    await Hive.openBox(_currentUserBox);

    Log.debug("DatabaseService: Hive initialized successfully");
  }

  /// Close all boxes
  static Future<void> close() async {
    await Hive.close();
  }

  // --- Private Box Getters ---

  Box<UserModel> get _users => Hive.box<UserModel>(_usersBox);
  Box<TrainingProgramModel> get _programs =>
      Hive.box<TrainingProgramModel>(_programsBox);
  Box<WeeklyWorkoutModel> get _weekly =>
      Hive.box<WeeklyWorkoutModel>(_weeklyBox);
  Box<WorkoutLogModel> get _workoutLogs =>
      Hive.box<WorkoutLogModel>(_workoutLogsBox);
  Box get _currentUser => Hive.box(_currentUserBox);

  // ============================================================
  // USER OPERATIONS
  // ============================================================

  Future<void> saveUser(UserModel user) async {
    Log.debug("DatabaseService: Saving user ${user.uid}...");

    if (_users.isNotEmpty ||
        _programs.isNotEmpty ||
        _weekly.isNotEmpty ||
        _workoutLogs.isNotEmpty) {
      final existingUser = _users.isNotEmpty ? _users.values.first : null;

      Log.warning(
        "DatabaseService: Existing data detected. "
        "SINGLE USER MODE - Clearing ALL data before saving new user.",
      );

      if (existingUser != null) {
        Log.debug(
            "  - Replacing user: ${existingUser.uid} (${existingUser.email})");
      }
      Log.debug("  - With new user: ${user.uid} (${user.email})");

      await clearAllData();
      Log.info("DatabaseService: All existing data cleared");
    }

    await _users.put(user.uid, user);
    Log.info("DatabaseService: User ${user.uid} saved successfully");
  }

  Future<void> updateUser(UserModel user) async {
    Log.debug("DatabaseService: Updating user ${user.uid}...");
    await _users.put(user.uid, user);
    Log.debug("DatabaseService: User ${user.uid} updated");
  }

  UserModel? getUser(String uid) {
    return _users.get(uid);
  }

  Future<void> deleteUser(String uid) async {
    await _users.delete(uid);
    Log.debug("DatabaseService: User $uid deleted");
  }

  Future<void> setCurrentUser(String? uid) async {
    if (uid == null) {
      await _currentUser.delete('uid');
    } else {
      await _currentUser.put('uid', uid);
    }
  }

  String? getCurrentUserId() {
    return _currentUser.get('uid') as String?;
  }

  UserModel? getCurrentUser() {
    final uid = getCurrentUserId();
    return uid != null ? getUser(uid) : null;
  }

  bool hasAnyUser() {
    return _users.isNotEmpty;
  }

  bool hasUser(String uid) {
    return _users.containsKey(uid);
  }

  // ============================================================
  // TRAINING PROGRAM OPERATIONS
  // ============================================================

  Future<void> saveProgram(TrainingProgramModel program) async {
    await _programs.put(program.id, program);
    Log.debug("DatabaseService: Program ${program.id} saved");

    // Auto-generate the first weekly workout if it doesn't exist
    final weeklyKey = 'weekly_${program.id}_1';
    if (!_weekly.containsKey(weeklyKey)) {
      final weekly = WeeklyWorkoutModel.fromProgram(program);
      await _weekly.put(weeklyKey, weekly);
      Log.debug(
          "DatabaseService: Auto-generated weekly workout for program ${program.id}");
    }
  }

  TrainingProgramModel? getProgram(String id) {
    return _programs.get(id);
  }

  List<TrainingProgramModel> getUserPrograms(String userId) {
    return _programs.values.where((p) => p.userId == userId).toList();
  }

  TrainingProgramModel? getCurrentProgram(String userId) {
    final programs = getUserPrograms(userId);
    if (programs.isEmpty) return null;

    programs.sort((a, b) => b.generatedAt.compareTo(a.generatedAt));
    final current = programs.firstWhere(
      (p) => !p.isExpired(),
      orElse: () => programs.first,
    );

    return current.isExpired() ? null : current;
  }

  Future<void> deleteProgram(String id) async {
    // Also delete associated weekly workouts
    final weeklyKeys = _weekly.keys.where(
      (key) => key.toString().startsWith('weekly_${id}_'),
    );
    for (final key in weeklyKeys) {
      await _weekly.delete(key);
    }
    await _programs.delete(id);
    Log.debug(
        "DatabaseService: Program $id and associated weekly workouts deleted");
  }

  // ============================================================
  // WEEKLY WORKOUT OPERATIONS
  // ============================================================

  Future<void> saveWeeklyWorkout(WeeklyWorkoutModel weekly) async {
    await _weekly.put(weekly.id, weekly);
    Log.debug("DatabaseService: Weekly workout ${weekly.id} saved");
  }

  WeeklyWorkoutModel? getWeeklyWorkout(String id) {
    return _weekly.get(id);
  }

  List<WeeklyWorkoutModel> getProgramWeeklyWorkouts(String programId) {
    return _weekly.values.where((w) => w.programId == programId).toList()
      ..sort((a, b) => a.weekNumber.compareTo(b.weekNumber));
  }

  WeeklyWorkoutModel? getCurrentWeeklyWorkout(String programId) {
    final workouts = getProgramWeeklyWorkouts(programId);
    return workouts.where((w) => w.isActive).toList().lastOrNull;
  }

  WeeklyWorkoutModel? getWeeklyWorkoutByWeekNumber(
    String programId,
    int weekNumber,
  ) {
    return _weekly.values
        .where((w) => w.programId == programId && w.weekNumber == weekNumber)
        .toList()
        .lastOrNull;
  }

  Future<void> deactivateWeeklyWorkout(String id) async {
    final weekly = _weekly.get(id);
    if (weekly != null) {
      weekly.isActive = false;
      await weekly.save();
      Log.debug("DatabaseService: Weekly workout $id deactivated");
    }
  }

  Future<void> deleteWeeklyWorkout(String id) async {
    await _weekly.delete(id);
    Log.debug("DatabaseService: Weekly workout $id deleted");
  }

  // ============================================================
  // WORKOUT LOG OPERATIONS
  // ============================================================

  Future<void> saveWorkoutLog(WorkoutLogModel log) async {
    await _workoutLogs.put(log.id, log);
    Log.debug("DatabaseService: Workout log ${log.id} saved");
  }

  WorkoutLogModel? getWorkoutLog(String id) {
    return _workoutLogs.get(id);
  }

  List<WorkoutLogModel> getUserWorkoutLogs(String userId) {
    final logs = _workoutLogs.values.where((l) => l.userId == userId).toList();
    logs.sort((a, b) => b.savedAt.compareTo(a.savedAt));
    return logs;
  }

  List<WorkoutLogModel> getLogsForDay(String userId, DateTime day) {
    final startOfDay = DateTime(day.year, day.month, day.day);
    final endOfDay = startOfDay.add(const Duration(days: 1));

    return _workoutLogs.values
        .where((l) =>
            l.userId == userId &&
            l.savedAt.isAfter(startOfDay) &&
            l.savedAt.isBefore(endOfDay))
        .toList()
      ..sort((a, b) => b.savedAt.compareTo(a.savedAt));
  }

  List<WorkoutLogModel> getUnsyncedLogs(String userId) {
    return _workoutLogs.values
        .where((l) => l.userId == userId && !l.synced)
        .toList();
  }

  Future<void> deleteWorkoutLog(String id) async {
    await _workoutLogs.delete(id);
    Log.debug("DatabaseService: Workout log $id deleted");
  }

  Future<void> markLogAsSynced(String id) async {
    final log = _workoutLogs.get(id);
    if (log != null) {
      log.synced = true;
      await log.save();
    }
  }

  // ============================================================
  // STREAM OPERATIONS
  // ============================================================

  Stream<BoxEvent> watchUser(String uid) {
    return _users.watch(key: uid);
  }

  Stream<BoxEvent> watchPrograms() {
    return _programs.watch();
  }

  Stream<BoxEvent> watchWeeklyWorkouts() {
    return _weekly.watch();
  }

  Stream<BoxEvent> watchWorkoutLogs() {
    return _workoutLogs.watch();
  }

  // ============================================================
  // UTILITY OPERATIONS
  // ============================================================

  Future<void> clearAllData() async {
    Log.warning("═══════════════════════════════════════════════════");
    Log.warning("DatabaseService: CLEARING ALL DATA (SINGLE USER MODE)");
    Log.warning("═══════════════════════════════════════════════════");

    if (_users.isNotEmpty) {
      for (var user in _users.values) {
        Log.debug("  - Deleting user: ${user.uid} (${user.email})");
      }
    }
    if (_programs.isNotEmpty) {
      for (var program in _programs.values) {
        Log.debug("  - Deleting program: ${program.id} (${program.name})");
      }
    }
    if (_weekly.isNotEmpty) {
      Log.debug("  - Deleting ${_weekly.length} weekly workout(s)");
    }
    if (_workoutLogs.isNotEmpty) {
      Log.debug("  - Deleting ${_workoutLogs.length} workout log(s)");
    }

    await _users.clear();
    await _programs.clear();
    await _weekly.clear();
    await _workoutLogs.clear();
    await _currentUser.clear();

    final usersCount = _users.length;
    final programsCount = _programs.length;
    final weeklyCount = _weekly.length;
    final logsCount = _workoutLogs.length;

    Log.debug("DatabaseService: After clear:");
    Log.debug("  - Users: $usersCount");
    Log.debug("  - Programs: $programsCount");
    Log.debug("  - Weekly workouts: $weeklyCount");
    Log.debug("  - Workout logs: $logsCount");

    if (usersCount > 0 ||
        programsCount > 0 ||
        weeklyCount > 0 ||
        logsCount > 0) {
      Log.error("DatabaseService: ⚠️ CRITICAL - Data NOT fully cleared!");
      throw Exception('clearAllData failed - data still present');
    }

    Log.warning("DatabaseService: ✅ ALL DATA CLEARED SUCCESSFULLY");
    Log.warning("═══════════════════════════════════════════════════");
  }

  Future<void> clearUserData(String userId) async {
    await deleteUser(userId);

    final userPrograms = getUserPrograms(userId);
    for (final program in userPrograms) {
      await deleteProgram(program.id);
    }

    final userLogs = getUserWorkoutLogs(userId);
    for (final log in userLogs) {
      await deleteWorkoutLog(log.id);
    }

    final currentUserId = getCurrentUserId();
    if (currentUserId == userId) {
      await setCurrentUser(null);
    }

    Log.debug("DatabaseService: All data for user $userId cleared");
  }
}
