// lib/services/database_service.dart
import 'package:hive_flutter/hive_flutter.dart';
import 'package:gymgenius/models/hive/user_model.dart';
import 'package:gymgenius/models/hive/routine_model.dart';
import 'package:gymgenius/models/hive/workout_log_model.dart';
import 'package:gymgenius/services/logger_service.dart';

/// Central service for managing Hive database operations
///
/// IMPORTANT: This service operates in SINGLE USER MODE.
/// When a NEW user (different UID) is saved, all existing user data is automatically deleted.
class DatabaseService {
  static const String _usersBox = 'users';
  static const String _routinesBox = 'routines';
  static const String _workoutLogsBox = 'workout_logs';
  static const String _currentUserBox = 'current_user';

  static DatabaseService? _instance;
  static DatabaseService get instance {
    _instance ??= DatabaseService._();
    return _instance!;
  }

  DatabaseService._();

  Box<UserModel> get users => _users;
  Box<RoutineModel> get routines => _routines;
  Box<WorkoutLogModel> get workoutLogs => _workoutLogs;

  /// Initialize Hive and register adapters
  static Future<void> initialize() async {
    await Hive.initFlutter();

    // Register adapters (generated by hive_generator)
    Hive.registerAdapter(UserModelAdapter());
    Hive.registerAdapter(RoutineModelAdapter());
    Hive.registerAdapter(WorkoutLogModelAdapter());

    // Open boxes
    await Hive.openBox<UserModel>(_usersBox);
    await Hive.openBox<RoutineModel>(_routinesBox);
    await Hive.openBox<WorkoutLogModel>(_workoutLogsBox);
    await Hive.openBox(_currentUserBox);

    Log.debug("DatabaseService: Hive initialized successfully");
  }

  /// Close all boxes
  static Future<void> close() async {
    await Hive.close();
  }

  // --- User Operations ---

  Box<UserModel> get _users => Hive.box<UserModel>(_usersBox);
  Box get _currentUser => Hive.box(_currentUserBox);

  /// Save a user to the database.
  ///
  /// CRITICAL: This operates in SINGLE USER MODE.
  /// ANY existing data is ALWAYS deleted before saving a new user.
  Future<void> saveUser(UserModel user) async {
    Log.debug("DatabaseService: Saving user ${user.uid}...");

    // In SINGLE USER MODE, if there's ANY data, clear it first
    if (_users.isNotEmpty || _routines.isNotEmpty || _workoutLogs.isNotEmpty) {
      final existingUser = _users.isNotEmpty ? _users.values.first : null;

      Log.warning("DatabaseService: Existing data detected. "
          "SINGLE USER MODE - Clearing ALL data before saving new user.");

      if (existingUser != null) {
        Log.debug(
            "  - Replacing user: ${existingUser.uid} (${existingUser.email})");
      }
      Log.debug("  - With new user: ${user.uid} (${user.email})");

      await clearAllData();
      Log.info("DatabaseService: All existing data cleared");
    }

    // Save the new user
    await _users.put(user.uid, user);
    Log.info(
        "DatabaseService: User ${user.uid} (${user.email}) saved successfully");
  }

  /// Update user WITHOUT clearing data (for same user updates)
  Future<void> updateUser(UserModel user) async {
    Log.debug("DatabaseService: Updating user ${user.uid}...");
    await _users.put(user.uid, user);
    Log.debug("DatabaseService: User ${user.uid} updated");
  }

  UserModel? getUser(String uid) {
    return _users.get(uid);
  }

  Future<void> deleteUser(String uid) async {
    await _users.delete(uid);
    Log.debug("DatabaseService: User $uid deleted");
  }

  Future<void> setCurrentUser(String? uid) async {
    if (uid == null) {
      await _currentUser.delete('uid');
    } else {
      await _currentUser.put('uid', uid);
    }
  }

  String? getCurrentUserId() {
    return _currentUser.get('uid') as String?;
  }

  UserModel? getCurrentUser() {
    final uid = getCurrentUserId();
    return uid != null ? getUser(uid) : null;
  }

  /// Check if any user exists in the database
  bool hasAnyUser() {
    return _users.isNotEmpty;
  }

  /// Check if a specific user exists in the database
  bool hasUser(String uid) {
    return _users.containsKey(uid);
  }

  // --- Routine Operations ---

  Box<RoutineModel> get _routines => Hive.box<RoutineModel>(_routinesBox);

  Future<void> saveRoutine(RoutineModel routine) async {
    await _routines.put(routine.id, routine);
    Log.debug("DatabaseService: Routine ${routine.id} saved");
  }

  RoutineModel? getRoutine(String id) {
    return _routines.get(id);
  }

  List<RoutineModel> getUserRoutines(String userId) {
    return _routines.values.where((r) => r.userId == userId).toList();
  }

  RoutineModel? getCurrentRoutine(String userId) {
    final routines = getUserRoutines(userId);
    if (routines.isEmpty) return null;

    // Return the most recent non-expired routine
    routines.sort((a, b) => b.generatedAt.compareTo(a.generatedAt));
    final current = routines.firstWhere(
      (r) => !r.isExpired(),
      orElse: () => routines.first,
    );

    return current.isExpired() ? null : current;
  }

  Future<void> deleteRoutine(String id) async {
    await _routines.delete(id);
    Log.debug("DatabaseService: Routine $id deleted");
  }

  // --- Workout Log Operations ---

  Box<WorkoutLogModel> get _workoutLogs =>
      Hive.box<WorkoutLogModel>(_workoutLogsBox);

  Future<void> saveWorkoutLog(WorkoutLogModel log) async {
    await _workoutLogs.put(log.id, log);
    Log.debug("DatabaseService: Workout log ${log.id} saved");
  }

  WorkoutLogModel? getWorkoutLog(String id) {
    return _workoutLogs.get(id);
  }

  List<WorkoutLogModel> getUserWorkoutLogs(String userId) {
    final logs = _workoutLogs.values.where((l) => l.userId == userId).toList();
    logs.sort((a, b) => b.savedAt.compareTo(a.savedAt));
    return logs;
  }

  List<WorkoutLogModel> getLogsForDay(String userId, DateTime day) {
    final startOfDay = DateTime(day.year, day.month, day.day);
    final endOfDay = startOfDay.add(const Duration(days: 1));

    return _workoutLogs.values
        .where((l) =>
            l.userId == userId &&
            l.savedAt.isAfter(startOfDay) &&
            l.savedAt.isBefore(endOfDay))
        .toList()
      ..sort((a, b) => b.savedAt.compareTo(a.savedAt));
  }

  List<WorkoutLogModel> getUnsyncedLogs(String userId) {
    return _workoutLogs.values
        .where((l) => l.userId == userId && !l.synced)
        .toList();
  }

  Future<void> deleteWorkoutLog(String id) async {
    await _workoutLogs.delete(id);
    Log.debug("DatabaseService: Workout log $id deleted");
  }

  Future<void> markLogAsSynced(String id) async {
    final log = _workoutLogs.get(id);
    if (log != null) {
      log.synced = true;
      await log.save();
    }
  }

  // --- Stream Operations ---

  Stream<BoxEvent> watchUser(String uid) {
    return _users.watch(key: uid);
  }

  Stream<BoxEvent> watchRoutines() {
    return _routines.watch();
  }

  Stream<BoxEvent> watchWorkoutLogs() {
    return _workoutLogs.watch();
  }

  // --- Utility Operations ---

  /// Clear ALL data from the database (users, routines, workout logs, current user)
  /// This is the ONLY way to maintain SINGLE USER MODE
  Future<void> clearAllData() async {
    Log.warning("═══════════════════════════════════════════════════");
    Log.warning("DatabaseService: CLEARING ALL DATA (SINGLE USER MODE)");
    Log.warning("═══════════════════════════════════════════════════");

    // Log what we're deleting
    if (_users.isNotEmpty) {
      for (var user in _users.values) {
        Log.debug("  - Deleting user: ${user.uid} (${user.email})");
      }
    }
    if (_routines.isNotEmpty) {
      for (var routine in _routines.values) {
        Log.debug("  - Deleting routine: ${routine.id} (${routine.name})");
      }
    }
    if (_workoutLogs.isNotEmpty) {
      Log.debug("  - Deleting ${_workoutLogs.length} workout log(s)");
    }

    // Clear all boxes
    await _users.clear();
    await _routines.clear();
    await _workoutLogs.clear();
    await _currentUser.clear();

    // Verify everything is empty
    final usersCount = _users.length;
    final routinesCount = _routines.length;
    final logsCount = _workoutLogs.length;

    Log.debug("DatabaseService: After clear:");
    Log.debug("  - Users: $usersCount");
    Log.debug("  - Routines: $routinesCount");
    Log.debug("  - Workout logs: $logsCount");

    if (usersCount > 0 || routinesCount > 0 || logsCount > 0) {
      Log.error("DatabaseService: ⚠️ CRITICAL - Data NOT fully cleared!");
      throw Exception('clearAllData failed - data still present');
    }

    Log.warning("DatabaseService: ✅ ALL DATA CLEARED SUCCESSFULLY");
    Log.warning("═══════════════════════════════════════════════════");
  }

  /// Clear all data for a specific user
  Future<void> clearUserData(String userId) async {
    // Delete user
    await deleteUser(userId);

    // Delete user's routines
    final userRoutines = getUserRoutines(userId);
    for (final routine in userRoutines) {
      await deleteRoutine(routine.id);
    }

    // Delete user's workout logs
    final userLogs = getUserWorkoutLogs(userId);
    for (final log in userLogs) {
      await deleteWorkoutLog(log.id);
    }

    // Clear current user if it's this user
    final currentUserId = getCurrentUserId();
    if (currentUserId == userId) {
      await setCurrentUser(null);
    }

    Log.debug("DatabaseService: All data for user $userId cleared");
  }
}
