import 'package:hive/hive.dart';

part 'training_program_model.g.dart';

/// A multi-week Training Program generated by the Workout Engine.
///
/// A Training Program defines a complete training strategy over several weeks,
/// including the weekly schedule and progression rules.
@HiveType(typeId: 1)
class TrainingProgramModel extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String userId;

  @HiveField(2)
  String name;

  @HiveField(3)
  int durationInWeeks;

  /// Weekly schedule: dayOfWeek (monday, tuesday, etc.) → list of exercises.
  @HiveField(4)
  Map<String, dynamic> weeklySchedule;

  @HiveField(5)
  DateTime generatedAt;

  @HiveField(6)
  DateTime expiresAt;

  @HiveField(7)
  String? goal;

  @HiveField(8)
  String? splitType;

  TrainingProgramModel({
    required this.id,
    required this.userId,
    required this.name,
    required this.durationInWeeks,
    required this.weeklySchedule,
    required this.generatedAt,
    required this.expiresAt,
    this.goal,
    this.splitType,
  });

  bool isExpired() => DateTime.now().isAfter(expiresAt);

  int get currentWeek {
    final daysSinceStart = DateTime.now().difference(generatedAt).inDays;
    return (daysSinceStart ~/ 7) + 1;
  }

  bool get isActive => !isExpired() && currentWeek <= durationInWeeks;

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'userId': userId,
      'name': name,
      'durationInWeeks': durationInWeeks,
      'weeklySchedule': weeklySchedule,
      'generatedAt': generatedAt.millisecondsSinceEpoch,
      'expiresAt': expiresAt.millisecondsSinceEpoch,
      'goal': goal,
      'splitType': splitType,
    };
  }

  factory TrainingProgramModel.fromMap(Map<String, dynamic> map) {
    return TrainingProgramModel(
      id: map['id'] as String,
      userId: map['userId'] as String,
      name: map['name'] as String,
      durationInWeeks: map['durationInWeeks'] as int,
      weeklySchedule: map['weeklySchedule'] as Map<String, dynamic>,
      generatedAt:
          DateTime.fromMillisecondsSinceEpoch(map['generatedAt'] as int),
      expiresAt: DateTime.fromMillisecondsSinceEpoch(map['expiresAt'] as int),
      goal: map['goal'] as String?,
      splitType: map['splitType'] as String?,
    );
  }
}
