import 'package:flutter/material.dart';
import 'package:gymgenius/domain/entities/recovery_status.dart';
import 'package:gymgenius/domain/enums/recommended_intensity.dart';

/// Read-only screen displaying the full recovery status for today.
class RecoveryScreen extends StatelessWidget {
  final RecoveryStatus status;

  const RecoveryScreen({super.key, required this.status});

  static Route<void> route(RecoveryStatus status) {
    return MaterialPageRoute(
      builder: (_) => RecoveryScreen(status: status),
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final cs = theme.colorScheme;
    final tt = theme.textTheme;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Recovery Status'),
        backgroundColor: cs.surface,
        foregroundColor: cs.onSurface,
        elevation: 0,
      ),
      body: ListView(
        padding: const EdgeInsets.all(20),
        children: [
          _ScoreGauge(
            label: 'Readiness',
            score: status.readinessScore,
            color: _readinessColor(cs, status.readinessScore),
          ),
          const SizedBox(height: 16),
          Row(
            children: [
              Expanded(
                child: _SmallScore(
                  label: 'Recovery',
                  score: status.recoveryScore,
                  icon: Icons.favorite_rounded,
                  color: cs.primary,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: _SmallScore(
                  label: 'Fatigue',
                  score: status.fatigueScore,
                  icon: Icons.battery_alert_rounded,
                  color: cs.error,
                  invertColor: true,
                ),
              ),
            ],
          ),
          const SizedBox(height: 20),
          _IntensityBadge(intensity: status.recommendedIntensity, cs: cs),
          if (status.requiresVolumeReduction) ...[
            const SizedBox(height: 8),
            Card(
              color: cs.errorContainer.withValues(alpha: 0.45),
              child: Padding(
                padding:
                    const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                child: Row(
                  children: [
                    Icon(Icons.info_outline_rounded,
                        color: cs.onErrorContainer, size: 20),
                    const SizedBox(width: 10),
                    Expanded(
                      child: Text(
                        'Training volume reduced by '
                        '${((1 - status.volumeMultiplier) * 100).round()} % '
                        'to match your readiness.',
                        style: tt.bodyMedium
                            ?.copyWith(color: cs.onErrorContainer),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
          const SizedBox(height: 20),
          if (status.reasons.isNotEmpty) ...[
            Text('Engine Insights',
                style: tt.titleMedium
                    ?.copyWith(fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            ...status.reasons.map(
              (r) => Padding(
                padding: const EdgeInsets.only(bottom: 6),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Icon(Icons.circle, size: 8, color: cs.primary),
                    const SizedBox(width: 10),
                    Expanded(
                      child: Text(r, style: tt.bodyMedium),
                    ),
                  ],
                ),
              ),
            ),
          ],
          const SizedBox(height: 24),
          Text(
            'Generated by ${status.generatedBy}',
            style:
                tt.bodySmall?.copyWith(color: cs.onSurface.withValues(alpha: 0.45)),
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }

  Color _readinessColor(ColorScheme cs, int score) {
    if (score >= 80) return cs.primary;
    if (score >= 60) return cs.tertiary;
    if (score >= 40) return Colors.orange;
    return cs.error;
  }
}

class _ScoreGauge extends StatelessWidget {
  final String label;
  final int score;
  final Color color;

  const _ScoreGauge({
    required this.label,
    required this.score,
    required this.color,
  });

  @override
  Widget build(BuildContext context) {
    final tt = Theme.of(context).textTheme;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text(label,
                style: tt.titleMedium?.copyWith(fontWeight: FontWeight.w600)),
            Text('$score / 100',
                style: tt.titleMedium?.copyWith(
                    fontWeight: FontWeight.bold, color: color)),
          ],
        ),
        const SizedBox(height: 8),
        ClipRRect(
          borderRadius: BorderRadius.circular(8),
          child: LinearProgressIndicator(
            value: score / 100.0,
            minHeight: 12,
            color: color,
            backgroundColor: color.withValues(alpha: 0.18),
          ),
        ),
      ],
    );
  }
}

class _SmallScore extends StatelessWidget {
  final String label;
  final int score;
  final IconData icon;
  final Color color;
  final bool invertColor;

  const _SmallScore({
    required this.label,
    required this.score,
    required this.icon,
    required this.color,
    this.invertColor = false,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final cs = theme.colorScheme;
    final tt = theme.textTheme;
    return Card(
      color: cs.surfaceContainerHigh,
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
        child: Row(
          children: [
            Icon(icon, color: color, size: 22),
            const SizedBox(width: 10),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(label, style: tt.bodySmall),
                Text(
                  '$score',
                  style: tt.titleMedium?.copyWith(
                    fontWeight: FontWeight.bold,
                    color: invertColor
                        ? (score > 60 ? color : cs.onSurface)
                        : (score >= 60 ? color : cs.onSurface),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class _IntensityBadge extends StatelessWidget {
  final RecommendedIntensity intensity;
  final ColorScheme cs;

  const _IntensityBadge({required this.intensity, required this.cs});

  @override
  Widget build(BuildContext context) {
    final tt = Theme.of(context).textTheme;
    final color = _color();
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.15),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: color.withValues(alpha: 0.4)),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(_icon(), color: color, size: 22),
          const SizedBox(width: 10),
          Text(
            'Recommended: ${intensity.displayName}',
            style: tt.titleMedium?.copyWith(
              fontWeight: FontWeight.bold,
              color: color,
            ),
          ),
        ],
      ),
    );
  }

  Color _color() {
    switch (intensity) {
      case RecommendedIntensity.max:
        return cs.primary;
      case RecommendedIntensity.high:
        return cs.tertiary;
      case RecommendedIntensity.moderate:
        return Colors.orange;
      case RecommendedIntensity.light:
        return Colors.blueGrey;
      case RecommendedIntensity.rest:
        return cs.error;
    }
  }

  IconData _icon() {
    switch (intensity) {
      case RecommendedIntensity.max:
        return Icons.bolt_rounded;
      case RecommendedIntensity.high:
        return Icons.trending_up_rounded;
      case RecommendedIntensity.moderate:
        return Icons.self_improvement_rounded;
      case RecommendedIntensity.light:
        return Icons.directions_walk_rounded;
      case RecommendedIntensity.rest:
        return Icons.hotel_rounded;
    }
  }
}
