import 'package:gymgenius/domain/enums/budget_level.dart';
import 'package:gymgenius/domain/enums/meal_objective.dart';
import 'package:gymgenius/domain/value_objects/macro_targets.dart';
import '../../../models/meal_template.dart';

const List<MealTemplate> cameroonTraditionalAndSoups = [
  MealTemplate(
    id: 'cm_meal_ndole',
    name: 'Ndolé with plantain',
    objective: MealObjective.highEnergy,
    ingredientIds: [
      'cm_ndole_leaves',
      'cm_groundnuts',
      'cm_beef',
      'cm_plantain_boiled'
    ],
    ingredientNames: ['Ndolé leaves', 'Groundnuts', 'Beef', 'Plantain'],
    baseMacros: MacroTargets(calories: 700, proteinG: 35, carbsG: 55, fatG: 35),
    minBudget: BudgetLevel.medium,
    allergens: ['peanut'],
    tags: ['traditional', 'dinner'],
  ),
  MealTemplate(
    id: 'cm_meal_eru_fufu',
    name: 'Water fufu and Eru',
    objective: MealObjective.highEnergy,
    ingredientIds: ['cm_fufu', 'cm_eru_leaves', 'cm_smoked_fish', 'cm_beef'],
    ingredientNames: ['Water fufu', 'Eru', 'Smoked fish', 'Beef'],
    baseMacros: MacroTargets(calories: 750, proteinG: 40, carbsG: 70, fatG: 28),
    minBudget: BudgetLevel.medium,
    allergens: ['fish'],
    tags: ['traditional', 'dinner'],
  ),
  MealTemplate(
    id: 'cm_meal_fish_sweet_potato',
    name: 'Fish with sweet potatoes',
    objective: MealObjective.recovery,
    ingredientIds: ['cm_fish', 'cm_sweet_potato', 'cm_spinach'],
    ingredientNames: ['Fresh fish', 'Sweet potato', 'Spinach'],
    baseMacros: MacroTargets(calories: 480, proteinG: 40, carbsG: 45, fatG: 8),
    allergens: ['fish'],
    tags: ['lunch', 'dinner', 'recovery'],
  ),
  MealTemplate(
    id: 'cm_meal_sardines_potato',
    name: 'Sardines with Irish potatoes',
    objective: MealObjective.highProtein,
    ingredientIds: ['cm_sardines', 'cm_irish_potato', 'cm_onion'],
    ingredientNames: ['Sardines', 'Irish potato', 'Onion'],
    baseMacros: MacroTargets(calories: 500, proteinG: 30, carbsG: 45, fatG: 18),
    allergens: ['fish'],
    tags: ['lunch', 'dinner'],
  ),
  MealTemplate(
    id: 'cm_meal_achu',
    name: 'Achu (cocoyam yellow soup)',
    objective: MealObjective.highEnergy,
    ingredientIds: ['cm_cocoyam', 'cm_beef', 'cm_fish', 'cm_palm_oil'],
    ingredientNames: ['Cocoyam', 'Beef', 'Fish', 'Palm oil'],
    baseMacros: MacroTargets(calories: 720, proteinG: 38, carbsG: 60, fatG: 30),
    minBudget: BudgetLevel.medium,
    allergens: ['fish'],
    tags: ['traditional', 'dinner'],
  ),
  MealTemplate(
    id: 'cm_meal_veggie_soup',
    name: 'Vegetable soup with eggs',
    objective: MealObjective.light,
    ingredientIds: ['cm_spinach', 'cm_okra', 'cm_tomato', 'cm_eggs'],
    ingredientNames: ['Spinach', 'Okra', 'Tomato', 'Eggs'],
    baseMacros: MacroTargets(calories: 280, proteinG: 18, carbsG: 15, fatG: 14),
    allergens: ['egg'],
    tags: ['light', 'dinner'],
  ),
  MealTemplate(
    id: 'cm_meal_poulet_dg',
    name: 'Poulet DG (DG Chicken with plantains)',
    objective: MealObjective.highEnergy,
    ingredientIds: [
      'cm_chicken_dg',
      'cm_plantain_fried',
      'cm_carrot',
      'cm_tomato',
      'cm_palm_oil',
      'cm_onion'
    ],
    ingredientNames: [
      'DG Chicken',
      'Fried plantain',
      'Carrot',
      'Tomato',
      'Palm oil',
      'Onion'
    ],
    baseMacros: MacroTargets(calories: 780, proteinG: 42, carbsG: 65, fatG: 38),
    minBudget: BudgetLevel.medium,
    tags: ['traditional', 'lunch', 'dinner', 'special'],
  ),
  MealTemplate(
    id: 'cm_meal_kondre_bobolo',
    name: 'Kondré (cow skin stew) with Bobolo',
    objective: MealObjective.highProtein,
    ingredientIds: [
      'cm_beef_kondre',
      'cm_cassava_bobolo',
      'cm_palm_oil',
      'cm_tomato',
      'cm_onion'
    ],
    ingredientNames: ['Kondré', 'Bobolo', 'Palm oil', 'Tomato', 'Onion'],
    baseMacros: MacroTargets(calories: 680, proteinG: 35, carbsG: 60, fatG: 30),
    minBudget: BudgetLevel.medium,
    tags: ['traditional', 'dinner', 'lunch'],
  ),
  MealTemplate(
    id: 'cm_meal_smoked_fish_miondo',
    name: 'Smoked fish with Miondo',
    objective: MealObjective.recovery,
    ingredientIds: ['cm_smoked_fish', 'cm_cassava_bobolo', 'cm_spinach'],
    ingredientNames: ['Smoked fish', 'Miondo', 'Spinach'],
    baseMacros: MacroTargets(calories: 480, proteinG: 38, carbsG: 50, fatG: 12),
    minBudget: BudgetLevel.low,
    allergens: ['fish'],
    tags: ['traditional', 'dinner', 'recovery'],
  ),
  MealTemplate(
    id: 'cm_meal_sanga',
    name: 'Sanga (Maize porridge with beans)',
    objective: MealObjective.highEnergy,
    ingredientIds: ['cm_corn_flour', 'cm_beans', 'cm_palm_oil', 'cm_spinach'],
    ingredientNames: ['Corn flour', 'Beans', 'Palm oil', 'Spinach'],
    baseMacros: MacroTargets(calories: 480, proteinG: 16, carbsG: 78, fatG: 12),
    tags: ['traditional', 'dinner', 'vegetarian', 'porridge'],
  ),
  MealTemplate(
    id: 'cm_meal_mbongo_tchobi',
    name: 'Mbongo Tchobi (Ragoût noir aux épices)',
    objective: MealObjective.highProtein,
    ingredientIds: [
      'cm_beef',
      'cm_fish',
      'cm_onion',
      'cm_tomato',
      'cm_hot_pepper'
    ],
    ingredientNames: ['Beef', 'Fish', 'Onion', 'Tomato', 'Hot pepper'],
    baseMacros: MacroTargets(calories: 450, proteinG: 35, carbsG: 14, fatG: 28),
    minBudget: BudgetLevel.medium,
    allergens: ['fish'],
    tags: ['traditional', 'dinner', 'spicy'],
  ),
  MealTemplate(
    id: 'cm_meal_pepe_soup',
    name: 'Pèpè Soup (Soupe pimentée au poisson/viande)',
    objective: MealObjective.recovery,
    ingredientIds: ['cm_fish', 'cm_onion', 'cm_hot_pepper', 'cm_tomato'],
    ingredientNames: ['Fish', 'Onion', 'Hot pepper', 'Tomato'],
    baseMacros: MacroTargets(calories: 280, proteinG: 28, carbsG: 9, fatG: 14),
    minBudget: BudgetLevel.low,
    allergens: ['fish'],
    tags: ['soup', 'dinner', 'spicy', 'recovery'],
  ),
  MealTemplate(
    id: 'cm_meal_kwem',
    name: 'Kwem (Purée de feuilles de manioc)',
    objective: MealObjective.light,
    ingredientIds: ['cm_cassava', 'cm_spinach', 'cm_palm_oil', 'cm_onion'],
    ingredientNames: ['Cassava', 'Spinach', 'Palm oil', 'Onion'],
    baseMacros: MacroTargets(calories: 350, proteinG: 12, carbsG: 30, fatG: 18),
    tags: ['traditional', 'vegetarian', 'dinner'],
  ),
  MealTemplate(
    id: 'cm_meal_grilled_fish_plantain',
    name: 'Poisson braisé avec plantain',
    objective: MealObjective.recovery,
    ingredientIds: [
      'cm_fish',
      'cm_plantain_boiled',
      'cm_onion',
      'cm_hot_pepper'
    ],
    ingredientNames: ['Grilled fish', 'Boiled plantain', 'Onion', 'Hot pepper'],
    baseMacros: MacroTargets(calories: 480, proteinG: 35, carbsG: 40, fatG: 14),
    allergens: ['fish'],
    tags: ['street_food', 'dinner', 'recovery'],
  ),
];
