// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwnlGW16v5QCzr6u7iMmMNUAzrN_cMN0k',
    appId: '1:100863523566:web:2c3dc3d93594764e57d1ff',
    messagingSenderId: '100863523566',
    projectId: 'gymgenius-1332f',
    authDomain: 'gymgenius-1332f.firebaseapp.com',
    storageBucket: 'gymgenius-1332f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfd866P8uM_dKCltI3sN84zGKXldcml1E',
    appId: '1:100863523566:android:bb322c80c20d0ccd57d1ff',
    messagingSenderId: '100863523566',
    projectId: 'gymgenius-1332f',
    storageBucket: 'gymgenius-1332f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeDe3Y4vO89lR_iCt7_Tce1EAfqRSwFVQ',
    appId: '1:100863523566:ios:c005755257f68f8c57d1ff',
    messagingSenderId: '100863523566',
    projectId: 'gymgenius-1332f',
    storageBucket: 'gymgenius-1332f.firebasestorage.app',
    iosBundleId: 'com.example.gymgenius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeDe3Y4vO89lR_iCt7_Tce1EAfqRSwFVQ',
    appId: '1:100863523566:ios:c005755257f68f8c57d1ff',
    messagingSenderId: '100863523566',
    projectId: 'gymgenius-1332f',
    storageBucket: 'gymgenius-1332f.firebasestorage.app',
    iosBundleId: 'com.example.gymgenius',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwnlGW16v5QCzr6u7iMmMNUAzrN_cMN0k',
    appId: '1:100863523566:web:d16fdf5f8605bc9357d1ff',
    messagingSenderId: '100863523566',
    projectId: 'gymgenius-1332f',
    authDomain: 'gymgenius-1332f.firebaseapp.com',
    storageBucket: 'gymgenius-1332f.firebasestorage.app',
  );
}
