import 'package:gymgenius/domain/enums/equipment_type.dart';
import 'package:gymgenius/domain/enums/muscle_group.dart';
import 'package:gymgenius/engines/workout_engine/shared/exercise_pool_entry.dart';

import 'splits/exports.dart';

/// Central repository of exercises, aggregated from individual split files.
///
/// IMPORTANT:
///
/// - [allowedEquipment] is a HARD constraint.
/// - [excludeMuscles] is a HARD constraint.
/// - A normal split uses its dedicated exercise pool.
/// - A specialized "Focused: ..." split uses only exercises whose PRIMARY
///   target muscles belong to the requested focus scope.
///
/// This allows the Workout Engine to support both:
///
///   Push / Pull / Legs / Chest / ...
///
/// and strict focus programs such as:
///
///   Focused: Abs / Core Day 1
///   Focused: Glutes Day 2
///   Focused: Glutes & Abs / Core Day 3
class ExercisePool {
  ExercisePool._();

  // ============================================================
  // Public API
  // ============================================================

  static List<ExercisePoolEntry> getExercises({
    required String splitName,
    required List<EquipmentType> allowedEquipment,
    List<MuscleGroup>? focusMuscles,
    List<MuscleGroup>? excludeMuscles,
  }) {
    final normalizedSplitName = splitName.trim();

    final isFocusedSplit = _isFocusedSplit(normalizedSplitName);

    final sourcePool = isFocusedSplit
        ? _focusedExercisePool(normalizedSplitName)
        : (_exercisePools[normalizedSplitName] ?? _exercisePools['Push']!);

    var filtered = sourcePool
        .where(
          (entry) => allowedEquipment.contains(entry.equipmentType),
        )
        .toList();

    // ------------------------------------------------------------
    // Avoided muscles
    // ------------------------------------------------------------

    if (excludeMuscles != null && excludeMuscles.isNotEmpty) {
      filtered = filtered.where((entry) {
        return !entry.targetMuscles.any(
          excludeMuscles.contains,
        );
      }).toList();
    }

    // ------------------------------------------------------------
    // Explicit focus preference
    //
    // For standard splits this remains a SOFT preference.
    //
    // Focused splits are already HARD-scoped by _focusedExercisePool(),
    // therefore we only use this sorting step here.
    // ------------------------------------------------------------

    if (focusMuscles != null && focusMuscles.isNotEmpty) {
      final focusSet = focusMuscles.toSet();

      filtered.sort((a, b) {
        final scoreA = _focusScore(
          entry: a,
          focusMuscles: focusSet,
          strict: isFocusedSplit,
        );

        final scoreB = _focusScore(
          entry: b,
          focusMuscles: focusSet,
          strict: isFocusedSplit,
        );

        return scoreB.compareTo(scoreA);
      });
    }

    return filtered;
  }

  // ============================================================
  // Exercise lookup
  // ============================================================

  static ExercisePoolEntry? findByName(
    String name, {
    required List<EquipmentType> allowedEquipment,
  }) {
    final normalized = name.trim().toLowerCase();

    if (normalized.isEmpty) {
      return null;
    }

    for (final entries in _exercisePools.values) {
      for (final entry in entries) {
        if (entry.name.toLowerCase() == normalized &&
            allowedEquipment.contains(entry.equipmentType)) {
          return entry;
        }
      }
    }

    return null;
  }

  static ExercisePoolEntry? findAlternative({
    required List<MuscleGroup> targetMuscles,
    required List<EquipmentType> allowedEquipment,
    Set<String> excludeNames = const {},
    List<MuscleGroup> excludeMuscles = const [],
  }) {
    ExercisePoolEntry? bestCandidate;
    var bestScore = -1;

    final targetSet = targetMuscles.toSet();

    for (final entries in _exercisePools.values) {
      for (final entry in entries) {
        if (!allowedEquipment.contains(entry.equipmentType)) {
          continue;
        }

        if (excludeNames.contains(entry.name)) {
          continue;
        }

        if (excludeMuscles.isNotEmpty &&
            entry.targetMuscles.any(excludeMuscles.contains)) {
          continue;
        }

        final score = entry.targetMuscles.where(targetSet.contains).length;

        if (score == 0) {
          continue;
        }

        if (score > bestScore) {
          bestScore = score;
          bestCandidate = entry;
        }
      }
    }

    return bestCandidate;
  }

  // ============================================================
  // Focused split support
  // ============================================================

  /// Returns true when the split name was generated by FocusSplitFactory.
  ///
  /// Expected format:
  ///
  ///   Focused: Abs / Core Day 1
  ///   Focused: Glutes Day 2
  ///   Focused: Glutes & Abs / Core Day 3
  static bool _isFocusedSplit(
    String splitName,
  ) {
    return splitName.toLowerCase().startsWith('focused:');
  }

  /// Builds the exercise pool for a strict focus split.
  ///
  /// Only exercises whose PRIMARY target muscles are entirely contained in
  /// the requested focus scope are accepted.
  ///
  /// This is intentionally stricter than ordinary split filtering.
  static List<ExercisePoolEntry> _focusedExercisePool(
    String splitName,
  ) {
    final focusMuscles = _parseFocusedMuscles(splitName);

    if (focusMuscles.isEmpty) {
      return const [];
    }

    final focusSet = focusMuscles.toSet();

    final allEntries = <ExercisePoolEntry>[];

    for (final entries in _exercisePools.values) {
      allEntries.addAll(entries);
    }

    return _dedupeByName(
      allEntries.where((entry) {
        if (entry.targetMuscles.isEmpty) {
          return false;
        }

        // Strict mode:
        //
        // every PRIMARY target must belong to the selected focus scope.
        //
        // Example:
        //
        // Focus = [Abs/Core]
        //
        // Crunch
        //   targetMuscles = [Abs/Core]        -> allowed
        //
        // Squat
        //   targetMuscles = [Quadriceps,
        //                    Glutes]           -> rejected
        //
        // This prevents unrelated primary muscles from entering a
        // specialized program.
        return entry.targetMuscles.every(
          focusSet.contains,
        );
      }).toList(),
    );
  }

  /// Parses focus muscles from names generated by FocusSplitFactory.
  ///
  /// Examples:
  ///
  ///   Focused: Abs / Core Day 1
  ///   Focused: Glutes Day 2
  ///   Focused: Glutes & Abs / Core Day 3
  static List<MuscleGroup> _parseFocusedMuscles(
    String splitName,
  ) {
    final lower = splitName.toLowerCase();

    if (!lower.startsWith('focused:')) {
      return const [];
    }

    var value = splitName.substring(
      splitName.indexOf(':') + 1,
    );

    final dayIndex = value.toLowerCase().lastIndexOf(' day ');

    if (dayIndex != -1) {
      value = value.substring(0, dayIndex);
    }

    value = value.trim();

    if (value.isEmpty) {
      return const [];
    }

    final result = <MuscleGroup>[];

    // FocusSplitFactory joins muscles with " & ".
    final parts = value
        .split(RegExp(r'\s*&\s*'))
        .map((part) => part.trim())
        .where((part) => part.isNotEmpty);

    for (final part in parts) {
      final muscle = _muscleFromDisplayName(part);

      if (muscle != null && !result.contains(muscle)) {
        result.add(muscle);
      }
    }

    return result;
  }

  static MuscleGroup? _muscleFromDisplayName(
    String value,
  ) {
    final normalized =
        value.trim().toLowerCase().replaceAll('-', ' ').replaceAll('_', ' ');

    for (final muscle in MuscleGroup.values) {
      final display = muscle.displayName
          .toLowerCase()
          .replaceAll('-', ' ')
          .replaceAll('_', ' ');

      if (display == normalized) {
        return muscle;
      }

      if (muscle == MuscleGroup.absCore &&
          (normalized == 'abs/core' ||
              normalized == 'abs core' ||
              normalized == 'core' ||
              normalized == 'abs')) {
        return MuscleGroup.absCore;
      }
    }

    return null;
  }

  static int _focusScore({
    required ExercisePoolEntry entry,
    required Set<MuscleGroup> focusMuscles,
    required bool strict,
  }) {
    final matchingPrimary =
        entry.targetMuscles.where(focusMuscles.contains).length;

    if (!strict) {
      return matchingPrimary;
    }

    final allPrimaryMatch = entry.targetMuscles.isNotEmpty &&
        entry.targetMuscles.every(focusMuscles.contains);

    return allPrimaryMatch ? matchingPrimary : 0;
  }

  // ============================================================
  // Combined pools
  // ============================================================

  /// Pool for the 'Shoulders & Core' split – combines shoulder + core.
  static final List<ExercisePoolEntry> _shouldersAndCoreExercises =
      _dedupeByName([
    ...shouldersExercises,
    ...coreExercises,
  ]);

  /// 'Full Body' split composition.
  static final List<ExercisePoolEntry> _fullBodyExercises = _dedupeByName([
    ...pushExercises,
    ...pullExercises,
    ...legsExercises,
    ...shouldersExercises,
    ...coreExercises,
  ]);

  static List<ExercisePoolEntry> _dedupeByName(
    List<ExercisePoolEntry> entries,
  ) {
    final seenNames = <String>{};
    final result = <ExercisePoolEntry>[];

    for (final entry in entries) {
      if (seenNames.add(entry.name)) {
        result.add(entry);
      }
    }

    return result;
  }

  // ============================================================
  // Main mapping
  // ============================================================

  static final Map<String, List<ExercisePoolEntry>> _exercisePools = {
    'Push': pushExercises,
    'Pull': pullExercises,
    'Legs': legsExercises,
    'Chest': chestExercises,
    'Back': backExercises,
    'Arms': armsExercises,
    'Chest & Triceps': chestTricepsExercises,
    'Back & Biceps': backBicepsExercises,
    'Shoulders & Core': _shouldersAndCoreExercises,
    'Upper Body': upperBodyExercises,
    'Lower Body': lowerBodyExercises,
    'Full Body': _fullBodyExercises,
  };
}
