import 'package:gymgenius/domain/entities/food_item.dart';
import 'package:gymgenius/domain/enums/food_category.dart';

const List<FoodItem> cameroonFruitsAndSweeteners = [
  FoodItem(
    id: 'cm_banana',
    name: 'Banana',
    country: 'Cameroon',
    category: FoodCategory.fruit,
    caloriesPer100g: 89,
    proteinGPer100g: 1.1,
    carbsGPer100g: 23,
    fatGPer100g: 0.3,
    defaultPortionLabel: '1 medium',
    defaultPortionGrams: 120,
    tags: ['snack'],
  ),
  FoodItem(
    id: 'cm_mango',
    name: 'Mango',
    country: 'Cameroon',
    category: FoodCategory.fruit,
    caloriesPer100g: 60,
    proteinGPer100g: 0.8,
    carbsGPer100g: 15,
    fatGPer100g: 0.4,
    defaultPortionLabel: '1 fruit',
    defaultPortionGrams: 200,
    tags: ['snack'],
  ),
  FoodItem(
    id: 'cm_papaya',
    name: 'Papaya',
    country: 'Cameroon',
    category: FoodCategory.fruit,
    caloriesPer100g: 43,
    proteinGPer100g: 0.5,
    carbsGPer100g: 11,
    fatGPer100g: 0.3,
    defaultPortionLabel: '1 cup',
    defaultPortionGrams: 150,
    tags: ['snack'],
  ),
  FoodItem(
    id: 'cm_pineapple',
    name: 'Pineapple',
    country: 'Cameroon',
    category: FoodCategory.fruit,
    caloriesPer100g: 50,
    proteinGPer100g: 0.5,
    carbsGPer100g: 13,
    fatGPer100g: 0.1,
    defaultPortionLabel: '1 cup',
    defaultPortionGrams: 165,
    tags: ['snack'],
  ),
  FoodItem(
    id: 'cm_orange',
    name: 'Orange',
    country: 'Cameroon',
    category: FoodCategory.fruit,
    caloriesPer100g: 47,
    proteinGPer100g: 0.9,
    carbsGPer100g: 12,
    fatGPer100g: 0.1,
    defaultPortionLabel: '1 fruit',
    defaultPortionGrams: 130,
    tags: ['snack'],
  ),
  FoodItem(
    id: 'cm_watermelon',
    name: 'Watermelon',
    country: 'Cameroon',
    category: FoodCategory.fruit,
    caloriesPer100g: 30,
    proteinGPer100g: 0.6,
    carbsGPer100g: 7.6,
    fatGPer100g: 0.2,
    defaultPortionLabel: '1 cup',
    defaultPortionGrams: 150,
    tags: ['snack'],
  ),
  FoodItem(
    id: 'cm_sugar',
    name: 'Granulated sugar',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 387,
    proteinGPer100g: 0,
    carbsGPer100g: 100,
    fatGPer100g: 0,
    defaultPortionLabel: '1 tbsp (15g)',
    defaultPortionGrams: 15,
    tags: ['sweetener'],
  ),
];
