import 'package:gymgenius/domain/entities/food_item.dart';
import 'package:gymgenius/domain/enums/food_category.dart';

const List<FoodItem> cameroonVegetables = [
  FoodItem(
    id: 'cm_spinach',
    name: 'Spinach / leafy greens',
    country: 'Cameroon',
    category: FoodCategory.vegetable,
    caloriesPer100g: 23,
    proteinGPer100g: 2.9,
    carbsGPer100g: 3.6,
    fatGPer100g: 0.4,
    fiberGPer100g: 2.2,
    defaultPortionLabel: '1 cup cooked',
    defaultPortionGrams: 180,
  ),
  FoodItem(
    id: 'cm_eru_leaves',
    name: 'Eru leaves',
    country: 'Cameroon',
    category: FoodCategory.vegetable,
    caloriesPer100g: 35,
    proteinGPer100g: 3.5,
    carbsGPer100g: 5,
    fatGPer100g: 0.5,
    defaultPortionLabel: '1 serving',
    defaultPortionGrams: 150,
    tags: ['traditional'],
  ),
  FoodItem(
    id: 'cm_ndole_leaves',
    name: 'Ndole leaves',
    country: 'Cameroon',
    category: FoodCategory.vegetable,
    caloriesPer100g: 40,
    proteinGPer100g: 4,
    carbsGPer100g: 5,
    fatGPer100g: 0.5,
    defaultPortionLabel: '1 serving',
    defaultPortionGrams: 150,
    tags: ['traditional'],
  ),
  FoodItem(
    id: 'cm_okra',
    name: 'Okra',
    country: 'Cameroon',
    category: FoodCategory.vegetable,
    caloriesPer100g: 33,
    proteinGPer100g: 1.9,
    carbsGPer100g: 7.5,
    fatGPer100g: 0.2,
    defaultPortionLabel: '1 cup',
    defaultPortionGrams: 100,
  ),
  FoodItem(
    id: 'cm_cabbage',
    name: 'Cabbage',
    country: 'Cameroon',
    category: FoodCategory.vegetable,
    caloriesPer100g: 25,
    proteinGPer100g: 1.3,
    carbsGPer100g: 5.8,
    fatGPer100g: 0.1,
    defaultPortionLabel: '1 cup',
    defaultPortionGrams: 90,
  ),
  FoodItem(
    id: 'cm_tomato',
    name: 'Tomato',
    country: 'Cameroon',
    category: FoodCategory.vegetable,
    caloriesPer100g: 18,
    proteinGPer100g: 0.9,
    carbsGPer100g: 3.9,
    fatGPer100g: 0.2,
    defaultPortionLabel: '1 medium',
    defaultPortionGrams: 120,
  ),
  FoodItem(
    id: 'cm_carrot',
    name: 'Carrot',
    country: 'Cameroon',
    category: FoodCategory.vegetable,
    caloriesPer100g: 41,
    proteinGPer100g: 0.9,
    carbsGPer100g: 10,
    fatGPer100g: 0.2,
    defaultPortionLabel: '1 medium',
    defaultPortionGrams: 60,
  ),
  FoodItem(
    id: 'cm_onion',
    name: 'Onion',
    country: 'Cameroon',
    category: FoodCategory.vegetable,
    caloriesPer100g: 40,
    proteinGPer100g: 1.1,
    carbsGPer100g: 9.3,
    fatGPer100g: 0.1,
    defaultPortionLabel: '1 medium',
    defaultPortionGrams: 110,
  ),
  FoodItem(
    id: 'cm_hot_pepper',
    name: 'Hot pepper',
    country: 'Cameroon',
    category: FoodCategory.vegetable,
    caloriesPer100g: 30,
    proteinGPer100g: 1.5,
    carbsGPer100g: 6,
    fatGPer100g: 0.3,
    defaultPortionLabel: '1 piece',
    defaultPortionGrams: 10,
    tags: ['spice'],
  ),
];
