// lib/engines/workout_engine/shared/exercises/catalog/definitions/arms_exercises.dart
// ⚠️ AUTO-GENERATED – DO NOT EDIT MANUALLY

import 'package:gymgenius/domain/enums/exports.dart';
import 'package:gymgenius/engines/workout_engine/shared/exercise_pool_entry.dart';

/// Canonical definitions for arms exercises.
const List<ExercisePoolEntry> armsDefinitions = [
  ExercisePoolEntry(
    id: 'arms_band_bicep_curl',
    name: 'Band Bicep Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand on the middle of a resistance band, holding a handle in each hand, arms straight down.\n2. Keeping your elbows pinned to your sides, curl the handles up towards your shoulders.\n3. Squeeze your biceps at the top, then lower with control against the band tension.\n4. Avoid using momentum; keep the movement slow and controlled.\n5. For added tension, step further onto the band or use a thicker band.',
  ),
  ExercisePoolEntry(
    id: 'arms_band_concentration_curl',
    name: 'Band Concentration Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps (Peak)**\n\n1. Sit on a chair, place the band under your foot, and hold the handle with one hand.\n2. Rest your elbow against your inner thigh, arm extended, and let the handle hang down.\n3. Curl the handle up towards your shoulder, squeezing your biceps at the top.\n4. Lower with control, fully extending your arm at the bottom.\n5. Complete all reps on one side before switching to the other.',
  ),
  ExercisePoolEntry(
    id: 'arms_band_hammer_curl',
    name: 'Band Hammer Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms**\n\n1. Stand on the middle of a resistance band, holding the handles with a neutral grip (palms facing each other).\n2. Keeping your elbows pinned to your sides, curl the handles up towards your shoulders without rotating your wrists.\n3. Squeeze your biceps and forearms at the top, then lower with control.\n4. This variation targets the brachialis and brachioradialis muscles.\n5. Maintain constant tension on the band throughout the movement.',
  ),
  ExercisePoolEntry(
    id: 'arms_band_kickbacks',
    name: 'Band Tricep Kickbacks',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Hinge forward at the hips with a flat back, placing a band under your foot on the opposite side.\n2. Hold the band handle with one hand, keeping your upper arm parallel to the floor.\n3. Extend your arm backward until it is straight, squeezing your triceps.\n4. Lower with control, keeping your upper arm stationary throughout.\n5. Complete all reps on one side before switching to the other.',
  ),
  ExercisePoolEntry(
    id: 'arms_band_overhead_tricep_extension',
    name: 'Band Overhead Tricep Extension',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Anchor a band low, stand facing away from the anchor.\n2. Hold the band overhead with your hands, arms bent, hands behind your head.\n3. Extend your arms upward until they are straight, squeezing your triceps.\n4. Lower the band back behind your head with control, keeping your upper arms stationary.\n5. Focus on the full extension of the triceps at the top of the movement.',
  ),
  ExercisePoolEntry(
    id: 'arms_band_reverse_curl',
    name: 'Band Reverse Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms**\n\n1. Stand on the middle of a resistance band, holding the handles with an overhand grip (palms facing down).\n2. Keeping your elbows pinned to your sides, curl the handles up towards your shoulders.\n3. Squeeze your biceps and forearms at the top, then lower with control.\n4. This variation targets the brachioradialis and forearm extensors.\n5. Perform the movement slowly for maximum muscle engagement.',
  ),
  ExercisePoolEntry(
    id: 'arms_band_tricep_pushdown',
    name: 'Band Tricep Pushdown',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
      'Chest & Triceps',
      'Push',
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Anchor a band overhead (e.g., to a pull‑up bar or door frame hook).\n2. Grip the band or handles with both hands, elbows pinned to your sides.\n3. Push the handles down until your arms are straight, squeezing your triceps.\n4. Return slowly, resisting the band tension.\n5. Keep your upper arms stationary throughout the movement.',
  ),
  ExercisePoolEntry(
    id: 'arms_band_wrist_curls',
    name: 'Band Wrist Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Forearms**\n\n1. Sit on a bench with your forearms resting on your thighs, holding the ends of a band that is anchored under your feet.\n2. Your hands should hang off your knees, palms facing up, with the band under tension.\n3. Curl your wrists upward, squeezing your forearm muscles at the top.\n4. Lower with control, feeling the stretch in your forearms.\n5. To target the other side, perform with palms facing down (wrist extensions).',
  ),
  ExercisePoolEntry(
    id: 'arms_bb_close_grip_bench_press',
    name: 'Close-Grip Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Arms',
      'Chest',
      'Chest & Triceps',
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Chest**\n\n1. Lie on a flat bench with your eyes directly under the bar and your feet planted on the floor.\n2. Grip the bar with your hands shoulder‑width apart or slightly narrower, with your elbows tucked close to your body.\n3. Unrack the bar and lower it to your lower chest (just below the sternum) with control.\n4. Keep your elbows pinned to your sides throughout the descent to maximise triceps engagement.\n5. Press the bar back up powerfully, extending your arms fully at the top.\n6. Avoid flaring your elbows; this variation targets the triceps more than the standard bench press.',
  ),
  ExercisePoolEntry(
    id: 'arms_bb_preacher_curls',
    name: 'Preacher Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Adjust the preacher bench so your armpits rest comfortably against the top pad and your upper arms are fully supported.\n2. Grip the barbell with an underhand grip, hands shoulder‑width apart, and let your arms hang straight down.\n3. Curl the barbell up towards your shoulders by contracting your biceps, keeping your upper arms stationary on the pad.\n4. Squeeze your biceps at the peak contraction for a second.\n5. Lower the bar with control until your arms are fully extended, feeling a stretch in your biceps.\n6. Avoid using momentum or lifting your upper arms off the pad.',
  ),
  ExercisePoolEntry(
    id: 'arms_bb_reverse_curl',
    name: 'Reverse Barbell Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms**\n\n1. Stand upright with feet shoulder‑width apart, holding a barbell with an overhand grip (palms facing down), hands shoulder‑width apart.\n2. Let the bar hang at arm\'s length in front of your thighs, with your elbows fully extended.\n3. Keeping your elbows pinned to your sides, curl the bar up towards your shoulders by contracting your biceps and forearms.\n4. Squeeze at the top, then lower the bar with control back to the starting position.\n5. This grip places more emphasis on the brachioradialis (forearm) and the brachialis.\n6. Avoid using momentum; keep the movement slow and controlled.',
  ),
  ExercisePoolEntry(
    id: 'arms_bb_skull_crushers',
    name: 'Skull Crushers',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
      'Chest & Triceps',
      'Push',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Lie on a flat bench holding a barbell with an overhand grip, arms extended above your chest, hands shoulder‑width apart.\n2. Keeping your upper arms fixed and perpendicular to the floor, bend your elbows to lower the bar towards your forehead.\n3. Lower the bar until it is just above your forehead (or just behind your head for a deeper stretch).\n4. Extend your arms back up to the starting position, squeezing your triceps at the top.\n5. Keep your elbows stationary throughout the movement; only your forearms should move.\n6. Use a light weight to maintain control and avoid injury.',
  ),
  ExercisePoolEntry(
    id: 'arms_bb_standing_curl',
    name: 'Standing Barbell Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand upright with feet shoulder‑width apart, holding a barbell with an underhand grip, hands shoulder‑width apart.\n2. Let the bar hang at arm\'s length in front of your thighs, with your elbows fully extended.\n3. Keeping your elbows pinned to your sides, curl the bar up towards your chest by contracting your biceps.\n4. Squeeze your biceps at the top of the movement, then lower the bar with control back to the starting position.\n5. Avoid swinging your body or using momentum; keep your torso stable.\n6. For a stricter variation, perform the exercise with your back against a wall.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_bench_dips',
    name: 'Bench Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Arms',
      'Chest & Triceps',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Shoulders**\n\n1. Sit on the edge of a sturdy chair or bench, hands gripping the edge beside your hips, fingers pointing forward.\n2. Slide your hips off the seat and lower your body by bending your elbows until your arms form a 90° angle.\n3. Push back up to the starting position, keeping your body close to the bench.\n4. To increase difficulty, extend your legs further or place weight on your lap.\n5. Keep your shoulders down and avoid shrugging.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_bicep_isometric_hold',
    name: 'Bicep Isometric Hold',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand with your arms bent at 90°, flexing your biceps as hard as possible.\n2. Hold this contracted position, squeezing your biceps with maximum effort.\n3. Keep your shoulders down and your core engaged.\n4. Hold for the prescribed time, focusing on the mind‑muscle connection.\n5. This can also be performed with one arm at a time for more intensity.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_close_grip_pushups',
    name: 'Close-Grip Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Inner Chest**\n\n1. Place your hands directly under your chest, with your thumbs and index fingers touching to form a diamond shape.\n2. Keep your body in a straight line from head to heels, core engaged.\n3. Lower your chest towards your hands, keeping your elbows close to your body.\n4. Push back up to the starting position, focusing on the triceps and inner chest squeeze.\n5. Avoid flaring your elbows out to the sides.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_diamond_pushups',
    name: 'Diamond Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Arms',
      'Chest',
      'Chest & Triceps',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Inner Chest**\n\n1. Place your hands together under your chest, forming a diamond shape with your thumbs and index fingers.\n2. Keep your elbows close to your body and lower your chest towards your hands.\n3. Push back up, focusing on the triceps and inner chest squeeze.\n4. Maintain a straight body line throughout the movement.\n5. This variation places maximum emphasis on the triceps.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_forearm_plank',
    name: 'Forearm Plank Hold',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.forearms,
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Forearms, Core**\n\n1. Lie on your stomach, then prop yourself up on your forearms, with your elbows directly under your shoulders.\n2. Keep your body in a straight line from head to heels, core engaged.\n3. Hold this position for the prescribed time, maintaining tension in your forearms and core.\n4. Avoid letting your hips sag or pike up.\n5. To increase difficulty, extend your arms further forward or lift one leg.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_incline_pushups',
    name: 'Incline Push-Up (Tricep Focus)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Arms',
      'Chest',
      'Chest & Triceps',
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Chest**\n\n1. Place your hands on a sturdy bench, chair, or step, shoulder‑width apart, with your body in a plank position.\n2. Keep your elbows tucked close to your body as you lower your chest towards the bench.\n3. Push back up, focusing on the triceps and chest squeeze.\n4. This incline variation reduces the load, making it suitable for beginners.\n5. To increase difficulty, lower the height of the surface.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_reverse_plank',
    name: 'Reverse Plank Hold',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.glutes,
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Rear Delts**\n\n1. Sit on the floor with your legs extended and your hands on the floor behind your hips, fingers pointing towards your body.\n2. Press through your hands and lift your hips until your body forms a straight line from your shoulders to your heels.\n3. Keep your chest open, shoulders down, and core engaged.\n4. Hold for the prescribed time, focusing on triceps and rear delt engagement.\n5. Avoid letting your hips drop; keep them elevated.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_tricep_isometric_hold',
    name: 'Tricep Isometric Hold',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Start in a push‑up position, but lower yourself about halfway down, so your elbows are bent at approximately 90°.\n2. Hold this position, keeping your body straight and core engaged.\n3. Hold for the prescribed time, maintaining tension in your triceps.\n4. If this is too difficult, perform the hold with your knees on the floor for support.\n5. Focus on keeping your elbows tucked close to your body.',
  ),
  ExercisePoolEntry(
    id: 'arms_cable_curls',
    name: 'Cable Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Attach a straight bar to a low pulley on a cable machine.\n2. Stand facing the machine, grip the bar with an underhand grip, hands shoulder‑width apart.\n3. Step back to create tension, keeping your elbows pinned to your sides.\n4. Curl the bar up towards your shoulders, squeezing your biceps at the top.\n5. Lower with control back to the starting position, maintaining tension throughout.',
  ),
  ExercisePoolEntry(
    id: 'arms_cable_hammer_curl',
    name: 'Cable Hammer Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
      'Back & Biceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms**\n\n1. Attach a rope or straight bar to a low pulley.\n2. Grip the handle with a neutral grip (palms facing each other), step back to create tension.\n3. Curl the handle up towards your shoulders without rotating your wrists.\n4. Squeeze your biceps and forearms at the top, then lower with control.\n5. This variation targets the brachialis and brachioradialis muscles.',
  ),
  ExercisePoolEntry(
    id: 'arms_cable_overhead_tricep_extension',
    name: 'Cable Overhead Tricep Extension',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
      'Chest & Triceps',
      'Push',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Attach a rope to a low pulley and face away from the machine.\n2. Hold the rope overhead with your arms bent, hands behind your head.\n3. Extend your arms upward, straightening them fully, squeezing your triceps.\n4. Lower the rope back behind your head with control, keeping your upper arms stationary.\n5. Focus on the full extension of the triceps at the top of the movement.',
  ),
  ExercisePoolEntry(
    id: 'arms_cable_single_arm_pushdown',
    name: 'Single-Arm Cable Pushdown',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps (Unilateral)**\n\n1. Attach a D‑handle to a high pulley.\n2. Stand close to the machine, grip the handle with one hand, and keep your elbow pinned to your side.\n3. Push the handle down until your arm is fully extended, squeezing your triceps.\n4. Return slowly to the starting position, resisting the weight.\n5. Complete all reps on one side before switching to the other.',
  ),
  ExercisePoolEntry(
    id: 'arms_cable_tricep_pushdowns',
    name: 'Tricep Pushdowns',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
      'Chest & Triceps',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Attach a rope or straight bar to a high pulley.\n2. Stand close to the machine, grip the handle, and keep your elbows pinned to your sides.\n3. Push the handle down until your arms are fully extended, squeezing your triceps at the bottom.\n4. Return slowly to the starting position, resisting the weight.\n5. For increased isolation, lean forward slightly and keep your upper arms stationary.',
  ),
  ExercisePoolEntry(
    id: 'arms_db_bicep_curls',
    name: 'Bicep Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand with feet shoulder‑width apart, holding a dumbbell in each hand, palms facing forward.\n2. Keeping your elbows pinned to your sides, curl the dumbbells up towards your shoulders.\n3. Squeeze your biceps at the top, then lower the weights with control back to the starting position.\n4. Avoid swinging your body; use strict form.\n5. Perform the movement slowly to maximise muscle tension.',
  ),
  ExercisePoolEntry(
    id: 'arms_db_concentration_curls',
    name: 'Concentration Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps (Peak)**\n\n1. Sit on a bench, spread your legs, and rest your elbow against your inner thigh on the same side.\n2. Hold a dumbbell in your hand, arm extended, and let it hang between your legs.\n3. Curl the dumbbell up towards your shoulder, squeezing your biceps at the top.\n4. Lower with control, fully extending your arm at the bottom.\n5. Complete all reps on one side before switching to the other.',
  ),
  ExercisePoolEntry(
    id: 'arms_db_hammer_curls',
    name: 'Hammer Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps (Brachialis), Forearms**\n\n1. Stand with feet shoulder‑width apart, holding a dumbbell in each hand with a neutral grip (palms facing each other).\n2. Keeping your elbows pinned to your sides, curl the dumbbells up towards your shoulders without rotating your wrists.\n3. Squeeze your biceps and forearms at the top, then lower with control.\n4. This variation places more emphasis on the brachialis and brachioradialis.\n5. Perform the movement slowly for maximum muscle engagement.',
  ),
  ExercisePoolEntry(
    id: 'arms_db_overhead_tricep_extension',
    name: 'Overhead Tricep Extension',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
      'Chest & Triceps',
      'Push',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Hold a dumbbell with both hands overhead, arms extended.\n2. Keeping your upper arms close to your head, bend your elbows to lower the dumbbell behind your head.\n3. Extend your arms back up to the starting position, squeezing your triceps.\n4. Keep your elbows stationary throughout the movement.\n5. Use a light weight to maintain control and focus on the stretch.',
  ),
  ExercisePoolEntry(
    id: 'arms_db_wrist_curls',
    name: 'Wrist Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Forearms**\n\n1. Sit on a bench with your forearm resting on your thigh, palm facing up, holding a dumbbell.\n2. Your wrist should hang just past your knee, allowing a full range of motion.\n3. Curl the weight up using only your wrist, squeezing your forearm muscles at the top.\n4. Lower with control back to the starting position.\n5. Complete all reps on one side before switching to the other.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_kb_bicep_curl',
    name: 'Kettlebell Bicep Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand with feet shoulder‑width apart, holding a kettlebell in each hand with an underhand grip.\n2. Keeping your elbows pinned to your sides, curl the kettlebells up towards your shoulders.\n3. Squeeze your biceps at the top, then lower with control.\n4. Avoid swinging your body; use strict form.\n5. Perform the movement slowly for maximum biceps activation.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_kb_hammer_curl',
    name: 'Kettlebell Hammer Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms**\n\n1. Stand with feet shoulder‑width apart, holding a kettlebell in each hand with a neutral grip (palms facing each other).\n2. Keeping your elbows pinned to your sides, curl the kettlebells up towards your shoulders without rotating your wrists.\n3. Squeeze your biceps and forearms at the top, then lower with control.\n4. This variation targets the brachialis and brachioradialis muscles.\n5. Perform the movement slowly for maximum muscle engagement.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_selector_preacher_curl',
    name: 'Selectorized Preacher Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Sit at the preacher curl machine, rest your upper arms on the pad, and grip the handles with an underhand grip.\n2. Curl the handles up towards your shoulders by contracting your biceps, keeping your upper arms stationary on the pad.\n3. Squeeze your biceps at the top, then lower the handles with control until your arms are fully extended.\n4. Avoid using momentum; keep the movement slow and controlled.\n5. This machine isolates the biceps effectively and minimises cheating.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_smith_bicep_curl',
    name: 'Smith Machine Bicep Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Set the Smith machine bar at thigh height and load a light weight.\n2. Stand facing the bar, grip it with an underhand grip, hands shoulder‑width apart.\n3. Curl the bar up towards your shoulders, keeping your elbows pinned to your sides.\n4. Squeeze your biceps at the top, then lower the bar with control back to the starting position.\n5. The fixed bar path helps maintain strict form and isolate the biceps effectively.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_db_kickbacks',
    name: 'Dumbbell Kickbacks',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Bend forward at the waist, keeping your back flat, holding a dumbbell in one hand.\n2. Keep your upper arm parallel to the floor and fixed, extend your forearm backward until your arm is straight.\n3. Squeeze your triceps at the top, then lower with control.\n4. Complete all reps on one side before switching.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_dip_tricep_dips',
    name: 'Tricep Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Keep your torso as upright as possible on the bars.\n2. Lower your body until your elbows form a 90° angle, keeping them close to your sides.\n3. Push back up to full extension, squeezing your triceps.\n4. Avoid leaning forward to keep the focus on the triceps.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_selector_tricep_extension_machine',
    name: 'Tricep Extension Machine',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Sit at the tricep extension machine, adjust the seat so the handles are at shoulder height.\n2. Grip the handles and press downward until your arms are fully extended.\n3. Squeeze your triceps at the bottom, then return slowly.\n4. Keep your back flat against the pad.',
  ),
  ExercisePoolEntry(
    id: 'push_smith_close_grip_press',
    name: 'Smith Machine Close-Grip Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Chest**\n\n1. Use a flat bench, grip the Smith bar with hands shoulder‑width apart or slightly narrower.\n2. Lower the bar to your lower chest, keeping your elbows tucked in.\n3. Press back up, focusing on triceps and inner chest.\n4. The fixed path helps maintain proper form.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_core_bb_zottman_curl',
    name: 'Barbell Zottman Curl (for shoulder stability)',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms, Shoulder Stabilizers**\n\n1. Stand upright holding a barbell with an underhand grip (palms up) at your thighs.\n2. Curl the bar up to shoulder height, squeezing your biceps.\n3. At the top, rotate your wrists so your palms face down (overhand grip).\n4. Lower the bar back to the starting position with palms down, controlling the descent.\n5. This builds forearm strength and shoulder stability.',
  ),
];
