// lib/engines/workout_engine/shared/exercises/catalog/definitions/arms_exercises.dart
// ⚠️ AUTO-GENERATED – DO NOT EDIT MANUALLY

import 'package:gymgenius/domain/enums/exports.dart';
import 'package:gymgenius/engines/workout_engine/shared/exercise_pool_entry.dart';

/// Canonical definitions for arms exercises.
const List<ExercisePoolEntry> armsDefinitions = [
  ExercisePoolEntry(
    id: 'arms_band_bicep_curl',
    name: 'Band Bicep Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand on a resistance band, holding the handles.\n2. Curl the handles up towards your shoulders.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'arms_band_concentration_curl',
    name: 'Band Concentration Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Anchor the band under your foot and brace your elbow on your thigh.\n2. Curl the handle up.\n3. Lower slowly.',
  ),
  ExercisePoolEntry(
    id: 'arms_band_hammer_curl',
    name: 'Band Hammer Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms**\n\n1. Stand on the band with a neutral grip (palms facing each other).\n2. Curl the handles up without rotating wrists.',
  ),
  ExercisePoolEntry(
    id: 'arms_band_kickbacks',
    name: 'Band Tricep Kickbacks',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Hinge forward with a band under your foot.\n2. Extend the arm back until straight.\n3. Return with control.',
  ),
  ExercisePoolEntry(
    id: 'arms_band_overhead_tricep_extension',
    name: 'Band Overhead Tricep Extension',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Hold one end of the band overhead, the other behind your back.\n2. Extend your arms straight up.\n3. Lower the band behind your head, then extend again.',
  ),
  ExercisePoolEntry(
    id: 'arms_band_reverse_curl',
    name: 'Band Reverse Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms**\n\n1. Stand on the band with an overhand grip (palms down).\n2. Curl the handles up towards your shoulders.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'arms_band_tricep_pushdown',
    name: 'Band Tricep Pushdown',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Anchor a band overhead (e.g., at a pull-up bar).\n2. Pull the band down until arms are straight.\n3. Squeeze triceps, then return slowly.',
  ),
  ExercisePoolEntry(
    id: 'arms_band_wrist_curls',
    name: 'Band Wrist Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Forearms**\n\n1. Sit with forearms on thighs, band under feet.\n2. Curl wrists upward against band tension.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'arms_bb_close_grip_bench_press',
    name: 'Close-Grip Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Chest**\n\n1. Grip the bar with hands shoulder-width apart.\n2. Lower to your lower chest, elbows tucked.\n3. Press back up.',
  ),
  ExercisePoolEntry(
    id: 'arms_bb_preacher_curls',
    name: 'Preacher Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Rest your upper arms on a preacher bench.\n2. Curl the bar up towards your shoulders.\n3. Lower slowly to full extension.',
  ),
  ExercisePoolEntry(
    id: 'arms_bb_reverse_curl',
    name: 'Reverse Barbell Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms**\n\n1. Hold the bar with an overhand grip (palms down).\n2. Curl the bar up towards your shoulders.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'arms_bb_skull_crushers',
    name: 'Skull Crushers',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Lie on a bench holding a barbell above your chest.\n2. Lower the bar towards your forehead.\n3. Extend back up.',
  ),
  ExercisePoolEntry(
    id: 'arms_bb_standing_curl',
    name: 'Standing Barbell Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand holding a barbell with an underhand grip, hands shoulder-width apart.\n2. Curl the bar up towards your chest, keeping elbows fixed.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_bench_dips',
    name: 'Bench Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Shoulders**\n\n1. Sit on the edge of a bench or chair, hands gripping the edge beside your hips.\n2. Slide your hips off and lower your body by bending your elbows.\n3. Push back up to full extension.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_bicep_isometric_hold',
    name: 'Bicep Isometric Hold',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Flex biceps in a curled position.\n2. Hold for time, squeezing hard.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_chair_tricep_extensions',
    name: 'Chair Tricep Extensions',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Place hands on a chair behind you, fingers forward.\n2. Bend elbows to lower hips.\n3. Extend arms to lift back up.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_close_grip_pushups',
    name: 'Close-Grip Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Inner Chest**\n\n1. Hands close together under chest.\n2. Lower chest towards hands.\n3. Press up.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_diamond_pushups',
    name: 'Diamond Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Inner Chest**\n\n1. Hands in diamond shape under chest.\n2. Lower chest towards hands.\n3. Press up.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_forearm_plank',
    name: 'Forearm Plank Hold',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.forearms,
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Forearms, Core**\n\n1. Hold a forearm plank with shoulders stacked over elbows.\n2. Maintain a straight line from head to heels.\n3. Hold for time.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_incline_pushups',
    name: 'Incline Push-ups (Tricep Focus)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Chest**\n\n1. Place hands on a bench or sturdy surface.\n2. Keep elbows tucked and lower your chest.\n3. Press back up.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_reverse_plank',
    name: 'Reverse Plank Hold',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.glutes,
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Rear Delts**\n\n1. Sit with legs extended, hands behind hips.\n2. Lift hips until body forms a straight line.\n3. Hold while keeping chest open.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_tricep_dips_chair',
    name: 'Tricep Dips (chair)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Shoulders**\n\n1. Sit on a chair, hands on the edge.\n2. Slide hips off and lower body.\n3. Push back up.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_tricep_isometric_hold',
    name: 'Tricep Isometric Hold',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Halfway down in a push-up position.\n2. Hold for time, keeping body straight.',
  ),
  ExercisePoolEntry(
    id: 'arms_cable_curls',
    name: 'Cable Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Attach a straight bar to a low pulley.\n2. Curl the bar up towards your shoulders.',
  ),
  ExercisePoolEntry(
    id: 'arms_cable_hammer_curl',
    name: 'Cable Hammer Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms**\n\n1. Attach a rope or straight bar to a low pulley.\n2. Curl the weight up with a neutral grip (palms facing each other).\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'arms_cable_overhead_tricep_extension',
    name: 'Cable Overhead Tricep Extension',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Attach a rope to a low pulley, stand facing away.\n2. Hold the rope overhead and extend your arms straight up.\n3. Lower the rope behind your head, then extend back up.',
  ),
  ExercisePoolEntry(
    id: 'arms_cable_single_arm_pushdown',
    name: 'Single-Arm Cable Pushdown',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps (unilateral)**\n\n1. Attach a D-handle to a high pulley.\n2. Pull down with one arm, keeping elbow fixed.\n3. Squeeze triceps at the bottom, return slowly.\n4. Switch sides.',
  ),
  ExercisePoolEntry(
    id: 'arms_cable_tricep_pushdowns',
    name: 'Tricep Pushdowns',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Attach a rope to a high pulley.\n2. Pull down until arms are straight.\n3. Squeeze triceps, then return slowly.',
  ),
  ExercisePoolEntry(
    id: 'arms_db_bicep_curls',
    name: 'Bicep Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand with dumbbells at your sides, palms facing forward.\n2. Curl the weights up to shoulder height.\n3. Lower them back down with control.',
  ),
  ExercisePoolEntry(
    id: 'arms_db_concentration_curls',
    name: 'Concentration Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps (peak)**\n\n1. Sit on a bench, elbow braced against your inner thigh.\n2. Curl the weight up towards your shoulder.',
  ),
  ExercisePoolEntry(
    id: 'arms_db_hammer_curls',
    name: 'Hammer Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms**\n\n1. Hold dumbbells with a neutral grip.\n2. Curl up without rotating your wrists.',
  ),
  ExercisePoolEntry(
    id: 'arms_db_overhead_tricep_extension',
    name: 'Overhead Tricep Extension',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Hold a dumbbell with both hands overhead.\n2. Lower it behind your head.\n3. Extend back up to full extension.',
  ),
  ExercisePoolEntry(
    id: 'arms_db_wrist_curls',
    name: 'Wrist Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Arms',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Forearms**\n\n1. Sit with your forearm resting on your thigh, palm facing up, dumbbell in hand.\n2. Curl the weight up using only your wrist.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_band_bicep_curl',
    name: 'Band Bicep Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand on band, hold handles.\n2. Curl up towards shoulders.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bb_preacher_curls',
    name: 'Preacher Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Rest upper arms on a preacher bench.\n2. Curl the bar up towards your shoulders.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_cable_curls',
    name: 'Cable Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Attach a straight bar to a low pulley.\n2. Curl up towards your shoulders.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_cable_hammer_curl',
    name: 'Cable Hammer Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms**\n\n1. Attach rope to low pulley.\n2. Curl with neutral grip.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_db_bicep_curls',
    name: 'Bicep Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand with dumbbells.\n2. Curl up to shoulder height.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_db_concentration_curls',
    name: 'Concentration Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps (peak)**\n\n1. Elbow braced against inner thigh while seated.\n2. Curl the weight towards your shoulder.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_db_hammer_curls',
    name: 'Hammer Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps (brachialis), Forearms**\n\n1. Neutral grip.\n2. Curl without rotation.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_kb_bicep_curl',
    name: 'Kettlebell Bicep Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand with kettlebell in each hand.\n2. Curl up to shoulder height.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_kb_hammer_curl',
    name: 'Kettlebell Hammer Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms**\n\n1. Hold kettlebells with neutral grip.\n2. Curl without rotating wrists.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_selector_preacher_curl',
    name: 'Preacher Curl Machine',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Sit at the preacher curl machine, rest upper arms on pad.\n2. Curl handles up towards shoulders.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_smith_bicep_curl',
    name: 'Smith Machine Bicep Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand with Smith bar at thigh height.\n2. Curl bar up towards shoulders.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_band_overhead_tricep_extension',
    name: 'Band Overhead Tricep Extension',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Anchor a band low, stand facing away.\n2. Hold band overhead, extend arms up.\n3. Lower behind head, extend back.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_band_tricep_pushdown',
    name: 'Band Tricep Pushdown',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Anchor a band overhead.\n2. Pull down until arms are straight.\n3. Squeeze triceps, return.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_bb_close_grip_bench_press',
    name: 'Close-Grip Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Chest**\n\n1. Grip the bar with hands shoulder-width apart.\n2. Lower to your lower chest, elbows tucked.\n3. Press back up.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_bb_skull_crushers',
    name: 'Skull Crushers',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Lie on a bench holding a barbell above your chest.\n2. Lower the bar towards your forehead.\n3. Extend back up.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_bw_bench_dips',
    name: 'Bench Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Shoulders**\n\n1. Sit on the edge of a bench or chair, hands gripping the edge beside your hips.\n2. Slide your hips off and lower your body by bending your elbows.\n3. Push back up to full extension.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_bw_diamond_pushups',
    name: 'Diamond Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Inner Chest**\n\n1. Form a diamond shape with your hands under your chest.\n2. Lower your chest towards your hands.\n3. Press back up to full extension.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_cable_overhead_tricep_extension',
    name: 'Cable Overhead Tricep Extension',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Attach rope to low pulley, stand facing away.\n2. Hold rope overhead, extend arms up.\n3. Lower behind head, extend back.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_cable_tricep_pushdowns',
    name: 'Tricep Pushdowns',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Attach rope to high pulley.\n2. Pull down to full extension.\n3. Squeeze triceps at bottom.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_chair_bench_dips',
    name: 'Bench Dips (chair)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Shoulders**\n\n1. Sit on the edge of a chair, hands gripping the edge beside your hips.\n2. Slide hips off and lower body.\n3. Push back up.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_chair_diamond_push_ups',
    name: 'Diamond Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Inner Chest**\n\n1. Hands together under chest, form a diamond.\n2. Lower chest towards hands.\n3. Press up.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_db_kickbacks',
    name: 'Dumbbell Kickbacks',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Bend forward with a flat back, holding a dumbbell in one hand.\n2. Extend the arm straight back, squeezing triceps.\n3. Lower with control, switch sides.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_db_overhead_tricep_extension',
    name: 'Overhead Tricep Extension',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Hold a dumbbell overhead with both hands.\n2. Lower behind your head.\n3. Extend back up.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_dip_tricep_dips',
    name: 'Tricep Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Keep torso upright on the dip bars.\n2. Lower until elbows are at 90°.\n3. Press up.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_selector_tricep_extension_machine',
    name: 'Tricep Extension Machine',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Sit at the machine, grip handles at shoulder height.\n2. Press down to full extension.\n3. Return slowly.',
  ),
  ExercisePoolEntry(
    id: 'pull_band_bicep_curls',
    name: 'Band Bicep Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand on the band, holding a handle in each hand.\n2. Curl your hands towards your shoulders.\n3. Lower with control against the band tension.',
  ),
  ExercisePoolEntry(
    id: 'pull_bb_preacher_curls',
    name: 'Preacher Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Rest your upper arms on a preacher bench, gripping a barbell.\n2. Curl the bar up towards your shoulders.\n3. Lower slowly to full extension.',
  ),
  ExercisePoolEntry(
    id: 'pull_cable_curls',
    name: 'Cable Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Attach a straight bar to a low pulley.\n2. Curl the bar up towards your shoulders, keeping elbows fixed.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'pull_db_bicep_curls',
    name: 'Bicep Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand with dumbbells at your sides, palms facing forward.\n2. Curl the weights up to shoulder height, squeezing biceps.\n3. Lower them back down with control.',
  ),
  ExercisePoolEntry(
    id: 'pull_db_concentration_curls',
    name: 'Concentration Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps (peak)**\n\n1. Sit on a bench, elbow braced against your inner thigh, dumbbell in hand.\n2. Curl the weight up towards your shoulder.\n3. Lower slowly with full control.',
  ),
  ExercisePoolEntry(
    id: 'pull_db_hammer_curls',
    name: 'Hammer Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps (brachialis), Forearms**\n\n1. Hold dumbbells with a neutral grip (palms facing each other).\n2. Curl up without rotating your wrists.',
  ),
  ExercisePoolEntry(
    id: 'pull_selector_preacher_curl',
    name: 'Selectorized Preacher Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Sit at the preacher curl machine, rest your upper arms on the pad.\n2. Curl the handles up towards your shoulders.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'push_band_tricep_pushdown',
    name: 'Band Tricep Pushdown',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Anchor a band overhead.\n2. Pull down until arms are straight.\n3. Squeeze triceps, return.',
  ),
  ExercisePoolEntry(
    id: 'push_bb_close_grip_bench_press',
    name: 'Close-Grip Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Chest**\n\n1. Lie on a flat bench, grip the bar with hands shoulder-width apart.\n2. Lower the bar to your lower chest, keeping elbows tucked in.\n3. Press back up focusing on triceps.',
  ),
  ExercisePoolEntry(
    id: 'push_bb_skull_crushers',
    name: 'Skull Crushers',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Lie on a bench holding a barbell above your chest.\n2. Bend your elbows to lower the bar towards your forehead.\n3. Extend back up without moving your upper arms.',
  ),
  ExercisePoolEntry(
    id: 'push_bw_diamond_push_ups',
    name: 'Diamond Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Inner Chest**\n\n1. Start in a plank with hands together under your chest, forming a diamond shape.\n2. Lower your chest towards your hands, keeping elbows close to your body.\n3. Press back up to full extension.',
  ),
  ExercisePoolEntry(
    id: 'push_cable_overhead_tricep_extension',
    name: 'Cable Overhead Tricep Extension',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Attach a rope to a low pulley, stand facing away.\n2. Hold the rope overhead, extend arms up.\n3. Lower the rope behind your head, then extend back.',
  ),
  ExercisePoolEntry(
    id: 'push_cable_tricep_pushdowns',
    name: 'Tricep Pushdowns',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Attach a rope or bar to a high pulley.\n2. Grip the handle and pull down until arms are straight.\n3. Squeeze triceps at the bottom, then return slowly.',
  ),
  ExercisePoolEntry(
    id: 'push_chair_bench_dips',
    name: 'Bench Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Shoulders**\n\n1. Sit on the edge of a bench or chair, hands gripping the edge beside your hips.\n2. Slide your hips off and lower your body by bending your elbows.\n3. Push back up to full extension.',
  ),
  ExercisePoolEntry(
    id: 'push_chair_diamond_push_ups',
    name: 'Diamond Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Inner Chest**\n\n1. Hands together under chest, form a diamond.\n2. Lower chest towards hands.\n3. Press up.',
  ),
  ExercisePoolEntry(
    id: 'push_db_overhead_tricep_extension',
    name: 'Overhead Tricep Extension',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Hold a dumbbell with both hands overhead.\n2. Lower it behind your head by bending your elbows.\n3. Extend back up to full extension.',
  ),
  ExercisePoolEntry(
    id: 'push_dip_tricep_dips',
    name: 'Tricep Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Keep torso upright on the dip bars.\n2. Lower until elbows are at 90°.\n3. Press up.',
  ),
  ExercisePoolEntry(
    id: 'push_smith_close_grip_press',
    name: 'Smith Machine Close-Grip Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Chest**\n\n1. Grip the Smith bar with hands shoulder-width apart.\n2. Perform a press with elbows tucked.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_core_bb_zottman_curl',
    name: 'Barbell Zottman Curl (for shoulder stability)',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms, Shoulder Stabilizers**\n\n1. Curl the barbell up with palms facing up.\n2. At the top, rotate palms down.\n3. Lower the bar with palms facing down.',
  ),
  ExercisePoolEntry(
    id: 'upper_band_bicep_curl',
    name: 'Band Bicep Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.forearms,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand on band.\n2. Curl handles up.',
  ),
  ExercisePoolEntry(
    id: 'upper_band_tricep_pushdown',
    name: 'Band Tricep Pushdown',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Anchor band overhead.\n2. Pull down to full extension.',
  ),
  ExercisePoolEntry(
    id: 'upper_bb_curl',
    name: 'Barbell Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.forearms,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand with bar.\n2. Curl up to shoulders.',
  ),
  ExercisePoolEntry(
    id: 'upper_bw_bench_dips',
    name: 'Bench Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Shoulders**\n\n1. Sit on edge of chair/bench, hands beside hips.\n2. Slide hips off and lower body.\n3. Push back up.',
  ),
  ExercisePoolEntry(
    id: 'upper_bw_diamond_push_ups',
    name: 'Diamond Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps, Inner Chest**\n\n1. Hands in diamond shape under chest.\n2. Lower chest towards hands.\n3. Press up.',
  ),
  ExercisePoolEntry(
    id: 'upper_cable_tricep_pushdowns',
    name: 'Tricep Pushdowns',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Triceps**\n\n1. Attach rope to high pulley.\n2. Pull down to full extension.',
  ),
  ExercisePoolEntry(
    id: 'upper_db_bicep_curls',
    name: 'Bicep Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.forearms,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand with dumbbells.\n2. Curl up to shoulder height.',
  ),
  ExercisePoolEntry(
    id: 'upper_db_hammer_curls',
    name: 'Hammer Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.biceps,
      MuscleGroup.forearms,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps, Forearms**\n\n1. Neutral grip.\n2. Curl without rotation.',
  ),
  ExercisePoolEntry(
    id: 'upper_smith_curl',
    name: 'Smith Machine Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.forearms,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Biceps**\n\n1. Stand with bar at thigh height.\n2. Curl bar up to shoulders.',
  ),
];
