// lib/engines/workout_engine/shared/exercises/catalog/definitions/back_exercises.dart
// ⚠️ AUTO-GENERATED – DO NOT EDIT MANUALLY

import 'package:gymgenius/domain/enums/exports.dart';
import 'package:gymgenius/engines/workout_engine/shared/exercise_pool_entry.dart';

/// Canonical definitions for back exercises.
const List<ExercisePoolEntry> backDefinitions = [
  ExercisePoolEntry(
    id: 'back_band_face_pulls',
    name: 'Band Face Pulls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.traps,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts, Traps**\n\n1. Anchor a band at face height.\n2. Pull the band towards your face, elbows high.\n3. Squeeze shoulder blades, then return.',
  ),
  ExercisePoolEntry(
    id: 'back_band_lat_pulldown',
    name: 'Band Lat Pulldown',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats, Biceps**\n\n1. Anchor a band overhead (e.g., to a pull-up bar).\n2. Pull the band down towards your chest, squeezing lats.\n3. Return with control.',
  ),
  ExercisePoolEntry(
    id: 'back_band_pull_aparts',
    name: 'Band Pull-Aparts',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts, Upper Back**\n\n1. Hold a band in front of you with arms straight.\n2. Pull the band apart by moving your hands out to the sides.\n3. Squeeze shoulder blades, then return.',
  ),
  ExercisePoolEntry(
    id: 'back_band_rows',
    name: 'Band Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Anchor a band at chest height and step back to create tension.\n2. Pull the handles towards your torso, squeezing your shoulder blades.\n3. Return slowly with control.',
  ),
  ExercisePoolEntry(
    id: 'back_band_straight_arm_pulldown',
    name: 'Band Straight-Arm Pulldown',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Back',
      'Pull',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats**\n\n1. Anchor a band overhead.\n2. With arms straight, pull the band down to your thighs.\n3. Squeeze lats, then return.',
  ),
  ExercisePoolEntry(
    id: 'back_bb_bent_over_row',
    name: 'Barbell Bent-Over Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Bend at the hips, keeping back flat, holding a barbell.\n2. Pull the bar towards your lower chest.\n3. Squeeze shoulder blades, then lower.',
  ),
  ExercisePoolEntry(
    id: 'back_bb_deadlift',
    name: 'Barbell Deadlift',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Full Posterior Chain**\n\n1. Stand with feet hip-width apart, barbell over midfoot.\n2. Hinge down, grip the bar, keep back flat.\n3. Drive through heels to stand up, then lower with control.',
  ),
  ExercisePoolEntry(
    id: 'back_bb_pendlay_row',
    name: 'Pendlay Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back**\n\n1. Stand with a barbell over midfoot, bend over with a flat back.\n2. Pull the bar explosively to your chest.\n3. Lower the bar back to the floor with control.',
  ),
  ExercisePoolEntry(
    id: 'back_bb_rack_pull',
    name: 'Rack Pull',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.hamstrings,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Back, Glutes**\n\n1. Set the barbell on safety pins at knee height.\n2. Hinge down, grip the bar, stand up with a flat back.\n3. Lower back to the pins.',
  ),
  ExercisePoolEntry(
    id: 'back_bb_t_bar_row',
    name: 'T-Bar Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Stand over a T-bar row machine or landmine attachment.\n2. Pull the handle towards your chest.\n3. Squeeze shoulder blades, then lower.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bb_barbell_rows',
    name: 'Barbell Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Bent-over position, overhand grip.\n2. Pull bar to lower chest.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_prone_i_raises',
    name: 'Prone I-Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Traps, Rhomboids**\n\n1. Lie face down, arms straight overhead (I position).\n2. Raise arms off the floor, squeezing shoulder blades.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_prone_t_raises',
    name: 'Prone T-Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Mid Traps, Rear Delts**\n\n1. Lie face down, arms out to the sides (T position).\n2. Raise arms off the floor, squeezing shoulder blades.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_prone_w_raises',
    name: 'Prone W-Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Mid/Lower Traps, Rhomboids**\n\n1. Lie face down, arms bent at 90° (W position).\n2. Raise arms off the floor, squeezing shoulder blades.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_prone_y_raises',
    name: 'Prone Y-Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Traps, Rear Delts**\n\n1. Lie face down, arms in Y position.\n2. Raise arms off the floor.\n3. Squeeze shoulder blades and lower.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_reverse_snow_angels',
    name: 'Reverse Snow Angels',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts, Upper Back**\n\n1. Lie face down, arms out to sides.\n2. Raise arms and squeeze shoulder blades together.\n3. Lower slowly.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_scapular_push_ups',
    name: 'Scapular Push-ups',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Traps, Serratus**\n\n1. Plank position, arms straight.\n2. Push your upper back towards the ceiling (without bending elbows).\n3. Return to neutral.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_supermans',
    name: 'Supermans',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Glutes**\n\n1. Lie face down, arms extended forward.\n2. Lift chest, arms, and legs off the ground.\n3. Hold briefly, then lower.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_table_rows',
    name: 'Table Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Lie under a sturdy table or bar, grip the edge.\n2. Pull your chest towards the table.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_cable_face_pulls',
    name: 'Face Pulls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.traps,
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts, Traps**\n\n1. Attach rope to high pulley.\n2. Pull towards face, elbows high.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_cable_lat_pulldowns',
    name: 'Lat Pulldowns',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Sit at machine, grip wide.\n2. Pull bar to upper chest.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_cable_seated_cable_row',
    name: 'Seated Cable Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Sit at cable row station, knees slightly bent.\n2. Pull handle towards torso.\n3. Extend arms back out.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_db_dumbbell_rows',
    name: 'Dumbbell Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Support one knee and hand on bench.\n2. Row dumbbell towards hip.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_db_reverse_flyes',
    name: 'Reverse Flyes',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts, Upper Back**\n\n1. Bend forward at the hips.\n2. Raise your arms out to the sides.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_kb_deadlift',
    name: 'Kettlebell Deadlift',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Full Posterior Chain**\n\n1. Stand over the kettlebell, hinge down and grip the handle.\n2. Drive through heels to stand up straight.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_kb_kettlebell_rows',
    name: 'Kettlebell Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Hinge forward, one hand on bench, other holding kettlebell.\n2. Pull kettlebell towards hip.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_kb_single_arm_swing',
    name: 'Single-Arm Kettlebell Swing',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Glutes, Hamstrings**\n\n1. Stand with feet shoulder-width apart, hold kettlebell with one hand.\n2. Hinge at hips, swing kettlebell back between legs.\n3. Drive hips forward to swing it up to chest height.\n4. Repeat and switch sides.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_pullup_chin_ups',
    name: 'Chin-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Underhand grip.\n2. Pull up to chin over bar.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_pullup_commando',
    name: 'Commando Pull-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps, Core**\n\n1. Grip bar with one hand in front of the other.\n2. Pull up, alternating lead hand each rep.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_pullup_neutral_grip',
    name: 'Neutral-Grip Pull-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Use parallel handles or neutral grip.\n2. Pull up, keeping elbows close.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_pullup_pull_ups',
    name: 'Pull-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Hang from bar.\n2. Pull up until chin over bar.\n3. Lower slowly.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_pullup_wide_grip',
    name: 'Wide-Grip Pull-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats (width)**\n\n1. Grip the bar wider than shoulder-width.\n2. Pull your chest towards the bar.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_selector_chest_supported_row',
    name: 'Chest-Supported Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back**\n\n1. Lie chest-down on the machine, grip handles.\n2. Pull handles towards your chest.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_selector_lat_pulldown',
    name: 'Selectorized Lat Pulldown',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats, Biceps**\n\n1. Sit at machine, grip wide bar.\n2. Pull down to upper chest.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_selector_machine_row',
    name: 'Machine Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Sit at the row machine, chest against the pad.\n2. Pull the handles towards your torso.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_selector_rear_delt_fly',
    name: 'Rear Delt Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts**\n\n1. Sit on the machine, arms against the pads.\n2. Push pads back and out, squeezing shoulder blades.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_smith_bent_over_row',
    name: 'Smith Machine Bent-Over Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Set bar at waist height, bend over with flat back.\n2. Pull bar towards lower chest.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_smith_deadlift',
    name: 'Smith Machine Deadlift',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Full Posterior Chain**\n\n1. Position Smith bar over midfoot.\n2. Hinge down, grip, drive through heels to stand.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_smith_inverted_rows',
    name: 'Smith Machine Inverted Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Set bar at hip height, lie under and grip.\n2. Pull chest towards bar.',
  ),
  ExercisePoolEntry(
    id: 'back_bw_prone_iy_t_raises',
    name: 'Prone I-Y-T Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Mid/Lower Traps, Rear Delts**\n\n1. Lie face down, arms in I, then Y, then T positions.\n2. Lift arms off the floor in each position.\n3. Squeeze shoulder blades.',
  ),
  ExercisePoolEntry(
    id: 'back_cable_face_pull',
    name: 'Cable Face Pull',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.traps,
    ],
    compatibleSplits: {
      'Back',
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts, Traps**\n\n1. Attach a rope to a high pulley.\n2. Pull the rope towards your face, elbows high.\n3. Squeeze shoulder blades, then return.',
  ),
  ExercisePoolEntry(
    id: 'back_cable_lat_pulldown',
    name: 'Lat Pulldown',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats, Biceps**\n\n1. Sit at a lat pulldown machine, hands on the bar.\n2. Pull the bar down to your upper chest.\n3. Squeeze lats, then return.',
  ),
  ExercisePoolEntry(
    id: 'back_cable_pullover',
    name: 'Cable Pullover',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats, Chest**\n\n1. Attach a rope to a low pulley, stand facing away.\n2. Pull the rope overhead and down towards your hips.\n3. Squeeze lats, then return.',
  ),
  ExercisePoolEntry(
    id: 'back_cable_seated_row',
    name: 'Cable Seated Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Sit at a cable row machine, feet braced.\n2. Pull the handle towards your abdomen.\n3. Squeeze shoulder blades, then return.',
  ),
  ExercisePoolEntry(
    id: 'back_cable_straight_arm_pulldown',
    name: 'Cable Straight-Arm Pulldown',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats**\n\n1. Attach a straight bar to a high pulley.\n2. With arms straight, pull the bar down to your thighs.\n3. Squeeze lats, then return.',
  ),
  ExercisePoolEntry(
    id: 'back_db_bent_over_row',
    name: 'Bent-Over Dumbbell Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Bend at the hips, keeping back flat, holding dumbbells.\n2. Pull dumbbells towards your lower chest.\n3. Squeeze shoulder blades, then lower.',
  ),
  ExercisePoolEntry(
    id: 'back_db_incline_row',
    name: 'Incline Dumbbell Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Back, Biceps**\n\n1. Lie face down on an incline bench, holding dumbbells.\n2. Pull dumbbells up towards your chest.\n3. Squeeze shoulder blades, then lower.',
  ),
  ExercisePoolEntry(
    id: 'back_db_pullover',
    name: 'Dumbbell Pullover',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats, Chest**\n\n1. Lie on a bench, hold a dumbbell with both hands above your chest.\n2. Lower the dumbbell behind your head in an arc.\n3. Pull it back to the starting position using your lats.',
  ),
  ExercisePoolEntry(
    id: 'back_db_rear_delt_fly',
    name: 'Dumbbell Rear Delt Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts**\n\n1. Bend forward with a flat back, holding dumbbells with palms facing each other.\n2. Raise arms out to the sides, squeezing shoulder blades.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'back_db_single_arm_row',
    name: 'Single-Arm Dumbbell Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps (unilateral)**\n\n1. Place one knee and hand on a bench, other foot on the floor.\n2. Pull the dumbbell up towards your hip.\n3. Squeeze your lat, then lower.\n4. Switch sides.',
  ),
  ExercisePoolEntry(
    id: 'back_selector_pulldown_wide_grip',
    name: 'Wide-Grip Lat Pulldown',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats (width)**\n\n1. Use a wide grip on the lat pulldown bar.\n2. Pull down to your upper chest.\n3. Squeeze lats, then return.',
  ),
  ExercisePoolEntry(
    id: 'back_selector_rear_delt_fly',
    name: 'Selectorized Rear Delt Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Pull',
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts**\n\n1. Sit on the machine, arms against the pads.\n2. Push the pads back and out, squeezing shoulder blades.\n3. Return with control.',
  ),
  ExercisePoolEntry(
    id: 'back_selector_seated_row',
    name: 'Selectorized Seated Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Sit on the machine, chest against the pad.\n2. Pull the handles towards your torso.\n3. Squeeze shoulder blades, then return.',
  ),
  ExercisePoolEntry(
    id: 'pull_band_single_arm_row',
    name: 'Band Single-Arm Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Anchor the band at chest height.\n2. Pull one handle to your hip while keeping torso stable.\n3. Alternate or complete all reps on one side.',
  ),
  ExercisePoolEntry(
    id: 'pull_bw_bird_dog_row',
    name: 'Bird Dog Row Hold',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Glutes, Core**\n\n1. On all fours, extend opposite arm and leg.\n2. Hold while keeping hips square and spine neutral.\n3. Switch sides after the interval.',
  ),
  ExercisePoolEntry(
    id: 'pull_bw_door_frame_rows',
    name: 'Door Frame Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Grip both sides of a sturdy door frame at chest height.\n2. Lean back with a straight body and pull your chest toward the frame.\n3. Lower under control.',
  ),
  ExercisePoolEntry(
    id: 'pull_bw_inverted_row_feet_elevated',
    name: 'Feet-Elevated Inverted Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Set up an inverted row with feet on a bench or chair.\n2. Pull your chest to the bar or table edge.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'pull_bw_superman_hold',
    name: 'Superman Hold',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Glutes**\n\n1. Lie face down with arms extended.\n2. Lift chest, arms, and legs and hold.\n3. Maintain tension for the prescribed time.',
  ),
  ExercisePoolEntry(
    id: 'pull_bw_towel_rows',
    name: 'Towel Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.forearms,
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps, Forearms**\n\n1. Loop a towel around a post or handle and grip both ends.\n2. Pull your torso toward the anchor point.\n3. Return slowly.',
  ),
  ExercisePoolEntry(
    id: 'pull_bw_wall_angels',
    name: 'Wall Angels',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Back, Rear Delts**\n\n1. Stand with back flat against a wall, arms in a W shape.\n2. Slide arms overhead while keeping contact with the wall.\n3. Return to the W position with control.',
  ),
  ExercisePoolEntry(
    id: 'pull_cable_single_arm_lat_pulldown',
    name: 'Single-Arm Lat Pulldown',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats, Biceps**\n\n1. Attach a single handle to a high pulley.\n2. Pull down and towards your hip with one arm.\n3. Return with control, then switch sides.',
  ),
  ExercisePoolEntry(
    id: 'pull_db_renegade_rows',
    name: 'Renegade Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.absCore,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Core, Biceps**\n\n1. Start in a plank holding a dumbbell in each hand.\n2. Row one dumbbell up towards your hip while stabilizing with the other arm.\n3. Lower and repeat on the other side.',
  ),
  ExercisePoolEntry(
    id: 'pull_kb_renagade_row',
    name: 'Kettlebell Renegade Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.absCore,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Core, Biceps**\n\n1. Start in a plank holding a kettlebell in each hand.\n2. Row one kettlebell up towards your hip while stabilizing with the other.\n3. Lower and repeat on the other side.',
  ),
  ExercisePoolEntry(
    id: 'pull_selector_chest_supported_row',
    name: 'Selectorized Chest-Supported Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back**\n\n1. Lie chest-down on the machine, grip handles.\n2. Pull handles towards your chest.\n3. Squeeze shoulder blades, then return.',
  ),
  ExercisePoolEntry(
    id: 'pull_selector_machine_row',
    name: 'Selectorized Machine Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Sit at the row machine, chest against the pad.\n2. Pull the handles towards your torso.\n3. Return slowly to the starting position.',
  ),
  ExercisePoolEntry(
    id: 'pull_smith_single_arm_row',
    name: 'Smith Single-Arm Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps (unilateral)**\n\n1. Set the bar at waist height, stand sideways, grip the bar with one hand.\n2. Pull the bar towards your hip, squeezing your lat.\n3. Lower with control, then switch sides.',
  ),
  ExercisePoolEntry(
    id: 'upper_bb_bent_over_row',
    name: 'Barbell Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Bend over, overhand grip.\n2. Pull bar to lower chest.',
  ),
  ExercisePoolEntry(
    id: 'upper_smith_row',
    name: 'Smith Machine Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Set bar at waist height.\n2. Bend over, pull bar to chest.',
  ),
];
