// lib/engines/workout_engine/shared/exercises/catalog/definitions/back_exercises.dart
// ⚠️ AUTO-GENERATED – DO NOT EDIT MANUALLY

import 'package:gymgenius/domain/enums/exports.dart';
import 'package:gymgenius/engines/workout_engine/shared/exercise_pool_entry.dart';

/// Canonical definitions for back exercises.
const List<ExercisePoolEntry> backDefinitions = [
  ExercisePoolEntry(
    id: 'back_band_face_pulls',
    name: 'Band Face Pulls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.traps,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Chest & Triceps',
      'Pull',
      'Push',
      'Shoulders',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts, Traps**\n\n1. Anchor a band at face height (e.g., to a door handle or pole).\n2. Hold the band with both hands, arms extended, and step back to create tension.\n3. Pull the band towards your face, keeping your elbows high and your hands near your ears.\n4. Squeeze your shoulder blades together at the peak, then return slowly.\n5. This exercise is excellent for correcting rounded shoulders and improving posture.',
  ),
  ExercisePoolEntry(
    id: 'back_band_lat_pulldown',
    name: 'Band Lat Pulldown',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats, Biceps**\n\n1. Anchor a resistance band overhead (e.g., to a pull‑up bar or door frame).\n2. Kneel or sit, grab the band with both hands, arms extended overhead, and lean back slightly.\n3. Pull the band down towards your chest, driving your elbows down and back, squeezing your lats.\n4. Pause at the bottom, then return slowly, keeping tension on the band.\n5. Use a moderate band to allow for controlled reps.',
  ),
  ExercisePoolEntry(
    id: 'back_band_pull_aparts',
    name: 'Band Pull-Aparts',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts, Upper Back**\n\n1. Hold a resistance band in front of you with both hands, arms extended straight out, shoulder‑width apart.\n2. Keeping your arms straight, pull the band apart by moving your hands out to the sides, stretching the band.\n3. Squeeze your shoulder blades together at the peak, then slowly return to the starting position.\n4. This is a great warm‑up or finishing exercise for shoulder health and posture.\n5. Perform controlled reps, avoiding rapid jerks.',
  ),
  ExercisePoolEntry(
    id: 'back_band_rows',
    name: 'Band Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Anchor a resistance band at chest height around a sturdy post or door frame.\n2. Step back to create tension, hold the handles (or the band) with both hands, arms extended.\n3. Pull the band handles towards your torso, squeezing your shoulder blades together.\n4. Pause, then return slowly with control, keeping tension on the band throughout.\n5. Maintain a flat back and core engagement to avoid lower back strain.',
  ),
  ExercisePoolEntry(
    id: 'back_band_straight_arm_pulldown',
    name: 'Band Straight-Arm Pulldown',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Back',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats**\n\n1. Anchor a band overhead (e.g., to a pull‑up bar).\n2. Stand facing the anchor, grab the band with both hands, arms extended straight out in front.\n3. Keeping your arms straight, push the band down towards your thighs by hinging at the shoulders, squeezing your lats.\n4. Pause at the bottom, then return slowly to the starting position.\n5. Keep a slight bend in your elbows to maintain tension on the lats.',
  ),
  ExercisePoolEntry(
    id: 'back_bb_bent_over_row',
    name: 'Barbell Bent-Over Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Stand with feet shoulder‑width apart, holding a barbell with an overhand grip, hands slightly wider than shoulders.\n2. Bend at your hips, keeping your back flat and chest up, until your torso is nearly parallel to the floor.\n3. Pull the barbell towards your lower chest, driving your elbows back and squeezing your shoulder blades together.\n4. Pause at the top, then lower the bar with control back to the starting position.\n5. Keep your core braced and avoid rounding your back.',
  ),
  ExercisePoolEntry(
    id: 'back_bb_deadlift',
    name: 'Barbell Deadlift',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Legs',
      'Lower Body',
      'Pull',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Full Posterior Chain**\n\n1. Stand with feet hip‑width apart, barbell over the middle of your feet, shins touching the bar.\n2. Hinge at your hips and bend your knees, grip the bar just outside your knees with a shoulder‑width grip (mixed or overhand).\n3. Keep your back flat, chest up, and drive through your heels to stand up, pulling the bar up along your shins and thighs.\n4. Lock out at the top by squeezing your glutes and standing tall, then lower the bar back to the floor with control, maintaining a flat back.\n5. Reset each rep from a dead stop on the floor.',
  ),
  ExercisePoolEntry(
    id: 'back_bb_pendlay_row',
    name: 'Pendlay Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back (Explosive Strength)**\n\n1. Set a barbell on the floor and stand over it with feet hip‑width apart, shins near the bar.\n2. Bend at the hips with a flat back, grip the bar just outside your knees, and keep your head up.\n3. Pull the bar explosively towards your chest, keeping your elbows high and back flat.\n4. Lower the bar back to the floor with control; each rep starts from a dead stop.\n5. Reset your position between reps for maximal back engagement.',
  ),
  ExercisePoolEntry(
    id: 'back_bb_rack_pull',
    name: 'Rack Pull',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.hamstrings,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Back, Glutes**\n\n1. Set the barbell on safety pins in a power rack at knee height (or just below the knees).\n2. Stand over the bar, grip it with a shoulder‑width grip, keep your back flat, chest up.\n3. Drive through your heels to stand up, pulling the bar to full extension, squeezing your glutes and upper back.\n4. Lower the bar back to the pins with control, maintaining a flat back.\n5. This movement is excellent for building lockout strength and upper back thickness.',
  ),
  ExercisePoolEntry(
    id: 'back_bb_t_bar_row',
    name: 'T-Bar Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Set up a T‑bar row station or landmine attachment with a barbell loaded on one end.\n2. Straddle the bar, bend at the hips with a flat back, and grip the handles or the bar end.\n3. Pull the handle towards your chest, driving your elbows back and squeezing your shoulder blades.\n4. Lower with control, feeling the stretch in your lats.\n5. Keep your core tight and avoid using momentum.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_prone_i_raises',
    name: 'Prone I-Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Traps, Rhomboids**\n\n1. Lie face down on the floor with your arms extended straight overhead, thumbs pointing up (I position).\n2. Lift your arms off the floor, squeezing your shoulder blades together and down.\n3. Hold at the top for 1‑2 seconds, then lower slowly.\n4. Keep your neck relaxed and your chest on the floor.\n5. This exercise strengthens the lower traps and improves shoulder stability.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_prone_t_raises',
    name: 'Prone T-Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Mid Traps, Rear Delts**\n\n1. Lie face down on the floor with your arms extended straight out to the sides, thumbs pointing up (T position).\n2. Lift your arms off the floor, squeezing your shoulder blades together.\n3. Hold at the top for 1‑2 seconds, then lower slowly.\n4. Keep your chest and core engaged to maintain stability.\n5. This strengthens the mid‑traps and rear deltoids, essential for good posture.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_prone_w_raises',
    name: 'Prone W-Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Mid/Lower Traps, Rhomboids**\n\n1. Lie face down on the floor with your arms bent at 90°, elbows in line with your shoulders (W position).\n2. Lift your arms off the floor, squeezing your shoulder blades together and down.\n3. Hold at the top for 1‑2 seconds, then lower slowly.\n4. Keep your neck relaxed and your chest on the floor.\n5. This variation targets the mid‑lower traps and rhomboids for better posture.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_prone_y_raises',
    name: 'Prone Y-Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Traps, Rear Delts**\n\n1. Lie face down on the floor with your arms extended in a "Y" position, thumbs pointing up.\n2. Lift your arms off the floor, squeezing your shoulder blades together and down.\n3. Hold at the top for 1‑2 seconds, then lower slowly.\n4. Keep your neck relaxed and your chest on the floor.\n5. This exercise specifically targets the lower trapezius and improves shoulder posture.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_reverse_snow_angels',
    name: 'Reverse Snow Angels',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts, Upper Back**\n\n1. Lie face down on the floor with your arms extended out to the sides at shoulder height, forming a "T" shape.\n2. Keeping your arms straight, raise them off the floor as high as possible, squeezing your shoulder blades together.\n3. Slowly rotate your arms backward and upward, as if making a snow angel in reverse, until your hands are near your hips.\n4. Reverse the movement to return to the starting position.\n5. Perform the movement slowly and with control for maximum muscle engagement.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_scapular_push_ups',
    name: 'Scapular Push-ups',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Traps, Serratus Anterior**\n\n1. Start in a high plank position with your arms straight, hands directly under your shoulders.\n2. Without bending your elbows, push your upper back towards the ceiling by protracting your shoulder blades (rounding your upper back).\n3. Then, retract your shoulder blades by pulling your chest towards the floor, squeezing your traps.\n4. Move only your shoulder blades, keeping your arms and body straight.\n5. This small movement improves scapular control and strengthens the traps.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_supermans',
    name: 'Supermans',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Glutes**\n\n1. Lie face down on the floor with your arms extended forward and legs straight.\n2. Simultaneously lift your arms, chest, and legs off the floor as high as possible.\n3. Squeeze your glutes and lower back muscles at the top, hold for 2 seconds.\n4. Lower back to the starting position with control.\n5. Keep your neck neutral by looking down at the floor.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bw_table_rows',
    name: 'Table Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Lie under a sturdy table or bar, grip the edge with an overhand grip, hands shoulder‑width apart.\n2. With your body straight and heels on the floor, pull your chest towards the table by driving your elbows back.\n3. Squeeze your shoulder blades together at the top, then lower your body with control back to the starting position.\n4. Keep your core tight to maintain a straight body line.\n5. To increase difficulty, elevate your feet or use a lower bar.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_cable_face_pulls',
    name: 'Cable Face Pull',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.traps,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts, Traps**\n\n1. Attach a rope to a high pulley and set the weight to a light to moderate load.\n2. Step back, grab the rope with an overhand grip, and stand with your arms extended.\n3. Pull the rope towards your face, keeping your elbows high (parallel to the floor) and your hands near your ears.\n4. Squeeze your shoulder blades together at the peak, then slowly return to the starting position.\n5. This exercise is excellent for shoulder health and posture.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_cable_lat_pulldowns',
    name: 'Lat Pulldown',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Sit at the lat pulldown machine, secure your thighs under the pads, and grip the bar with an overhand grip slightly wider than shoulder‑width.\n2. Lean back slightly, keep your chest up, and pull the bar down to your upper chest, driving your elbows down and back.\n3. Squeeze your lats at the bottom, then let the bar rise slowly back to the starting position.\n4. Control the movement throughout; do not use momentum.\n5. Variations: use a wide grip, neutral grip, or underhand grip for different muscle emphasis.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_cable_seated_cable_row',
    name: 'Cable Seated Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Sit at a cable row station with your feet braced against the footplates, knees slightly bent.\n2. Grip the handle (V‑grip or wide bar) and keep your back straight, chest up.\n3. Pull the handle towards your abdomen, driving your elbows back and squeezing your shoulder blades together.\n4. Pause at the peak contraction, then slowly return to the starting position, feeling the stretch in your lats.\n5. Avoid leaning back excessively; keep your torso relatively still.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_db_dumbbell_rows',
    name: 'Single-Arm Dumbbell Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Place one knee and one hand on a flat bench, with your other foot on the floor for stability.\n2. With your free hand, grab a dumbbell and let it hang straight down, palm facing your body.\n3. Pull the dumbbell up towards your hip, keeping your elbow close to your body and squeezing your lat.\n4. Lower with control, feeling the stretch in your lat, then complete all reps on one side before switching.\n5. Keep your back flat and your core engaged throughout.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_db_reverse_flyes',
    name: 'Dumbbell Rear Delt Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts, Upper Back**\n\n1. Bend forward at the hips with a flat back, holding a light dumbbell in each hand, palms facing each other.\n2. Let your arms hang straight down, then raise them out to the sides in a wide arc, squeezing your shoulder blades together.\n3. Pause when your arms are parallel to the floor, then lower with control.\n4. Keep a slight bend in your elbows throughout the movement.\n5. Use light weight to focus on form and the contraction of the rear delts.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_kb_deadlift',
    name: 'Kettlebell Deadlift',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Legs',
      'Lower Body',
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Full Posterior Chain**\n\n1. Stand with feet hip‑width apart, a kettlebell on the floor between your feet.\n2. Hinge at your hips and bend your knees, grip the kettlebell handle with both hands, and keep your back flat.\n3. Drive through your heels to stand up, squeezing your glutes and lats at the top.\n4. Lower the kettlebell back to the floor with control, maintaining a flat back.\n5. Reset each rep from a dead stop on the floor.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_kb_kettlebell_rows',
    name: 'Kettlebell Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Place one knee and one hand on a flat bench, with your other foot on the floor for stability.\n2. With your free hand, grab a kettlebell and let it hang straight down.\n3. Pull the kettlebell up towards your hip, keeping your elbow close to your body and squeezing your lat.\n4. Lower with control, feeling the stretch in your lat, then complete all reps on one side before switching.\n5. Keep your back flat and your core engaged throughout.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_kb_single_arm_swing',
    name: 'Single-Arm Kettlebell Swing',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Glutes, Hamstrings**\n\n1. Stand with feet shoulder‑width apart, holding a kettlebell in one hand between your legs.\n2. Hinge at your hips, swing the kettlebell back between your legs, keeping your back flat.\n3. Drive your hips forward explosively to swing the kettlebell up to chest height, squeezing your glutes and lats.\n4. Allow the kettlebell to swing back down between your legs with control.\n5. Complete all reps on one side before switching.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_pullup_chin_ups',
    name: 'Chin-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Grip the bar with an underhand grip (palms facing you), hands shoulder‑width apart.\n2. Hang with arms straight, then pull your chest towards the bar by driving your elbows down.\n3. Pull up until your chin clears the bar, then lower with control.\n4. Keep your core tight and avoid swinging.\n5. Chin‑ups are generally easier than pull‑ups due to greater biceps involvement.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_pullup_commando',
    name: 'Commando Pull-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps, Core**\n\n1. Grip the bar with one hand in front of the other (palms facing you or away), about shoulder‑width apart.\n2. Hang with arms straight, then pull yourself up, alternating the lead hand at the top of each rep.\n3. Continue alternating with each repetition, keeping your core engaged to prevent twisting.\n4. Pull up until your chin is above the bar, then lower with control.\n5. This variation challenges your core and shoulder stability.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_pullup_neutral_grip',
    name: 'Neutral-Grip Pull-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Use parallel handles or a neutral‑grip attachment on the bar, palms facing each other.\n2. Hang with arms straight, then pull yourself up, keeping your elbows close to your body.\n3. Pull up until your chin clears the handles, then lower with control.\n4. This grip is shoulder‑friendly and often allows more strength output.\n5. Focus on squeezing your lats at the top.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_pullup_pull_ups',
    name: 'Pull-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Hang from a pull‑up bar with an overhand grip, hands slightly wider than shoulder‑width.\n2. Engage your lats and pull your chest towards the bar, driving your elbows down and back.\n3. Pull up until your chin clears the bar, then lower with control to a dead hang.\n4. Avoid swinging; use a strict, controlled tempo.\n5. If you cannot complete full reps, use a band or assisted machine.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_pullup_wide_grip',
    name: 'Wide-Grip Pull-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats (Width)**\n\n1. Grip the bar with a very wide overhand grip, well outside shoulder‑width.\n2. Hang with arms straight, then pull your chest towards the bar, keeping your elbows flared.\n3. Pull up until your chin is over the bar, then lower with control.\n4. This variation emphasises the outer lats and upper back.\n5. Use a controlled tempo to maximise muscle activation.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_selector_chest_supported_row',
    name: 'Selectorized Chest-Supported Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back**\n\n1. Lie chest‑down on the chest‑supported row machine, gripping the handles at chest height.\n2. Pull the handles towards your chest, driving your elbows back and squeezing your shoulder blades together.\n3. Pause at the peak contraction, then slowly release the weight back to the starting position.\n4. Keep your chest against the pad and avoid lifting your torso.\n5. This machine removes lower back strain, allowing you to focus entirely on the back muscles.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_selector_lat_pulldown',
    name: 'Selectorized Lat Pulldown',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats, Biceps**\n\n1. Sit at the lat pulldown machine, secure your thighs under the pads, and grip the bar with an overhand grip slightly wider than shoulder‑width.\n2. Lean back slightly, keep your chest up, and pull the bar down to your upper chest, driving your elbows down and back.\n3. Squeeze your lats at the bottom, then let the bar rise slowly back to the starting position.\n4. Control the movement; do not use momentum.\n5. Variations: use a wide grip, neutral grip, or underhand grip for different muscle emphasis.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_selector_machine_row',
    name: 'Selectorized Machine Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Sit on the seated row machine, brace your feet against the footplates, and keep your knees slightly bent.\n2. Grasp the V‑handle or bar, lean forward slightly at the hips, and then pull the handle towards your abdomen.\n3. Squeeze your shoulder blades together at the peak contraction, then return slowly with control.\n4. Keep your back straight and avoid using excessive momentum.\n5. Adjust the seat height so the handles are at chest level for optimal range of motion.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_selector_rear_delt_fly',
    name: 'Selectorized Rear Delt Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
      'Back & Biceps',
      'Pull',
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts**\n\n1. Sit on the rear delt machine, adjust the seat so your arms are parallel to the floor when you grip the handles.\n2. Position your elbows against the pads and grasp the handles.\n3. Push the handles back and outward, squeezing your shoulder blades together.\n4. Pause at the peak contraction, then return with control.\n5. Use a light weight to focus on strict form and the mind‑muscle connection.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_smith_bent_over_row',
    name: 'Smith Machine Bent-Over Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Set the Smith machine bar at waist height and load the desired weight.\n2. Stand over the bar, bend at the hips with a flat back, and grip the bar with an overhand grip, hands slightly wider than shoulders.\n3. Pull the bar towards your lower chest, driving your elbows back and squeezing your shoulder blades together.\n4. Pause at the peak contraction, then lower the bar with control back to the starting position.\n5. Keep your core tight and your back flat throughout the movement.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_smith_deadlift',
    name: 'Smith Machine Deadlift',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Lower Body',
      'Pull',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Full Posterior Chain**\n\n1. Position the Smith machine bar over the middle of your feet and load the desired weight.\n2. Hinge at your hips and bend your knees, grip the bar with a shoulder‑width grip, and keep your back flat.\n3. Drive through your heels to stand up, squeezing your glutes and lats at the top.\n4. Lower the bar back to the starting position with control, maintaining a flat back.\n5. The Smith machine\'s fixed bar path helps maintain proper form throughout the movement.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_smith_inverted_rows',
    name: 'Smith Machine Inverted Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Set the Smith machine bar at hip height and load no weight (or a very light weight).\n2. Lie under the bar, grip it with an overhand grip, hands shoulder‑width apart, and extend your legs forward with your heels on the floor.\n3. Keeping your body straight, pull your chest towards the bar by driving your elbows back.\n4. Squeeze your shoulder blades together at the top, then lower your body with control.\n5. This is a bodyweight row variation; increase difficulty by elevating your feet or adding weight to the bar.',
  ),
  ExercisePoolEntry(
    id: 'back_bw_prone_iy_t_raises',
    name: 'Prone I-Y-T Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Mid/Lower Traps, Rear Delts**\n\n1. Lie face down on the floor with your arms extended in an "I" position (straight overhead).\n2. Lift your arms and chest off the floor, squeeze your shoulder blades, then lower.\n3. Repeat the same movement with your arms in a "Y" position (angled outward) and then in a "T" position (straight out to the sides).\n4. Perform 10 reps in each position, keeping your core engaged.\n5. This exercise targets the entire upper back and improves posture.',
  ),
  ExercisePoolEntry(
    id: 'back_cable_pullover',
    name: 'Cable Pullover',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats, Chest**\n\n1. Attach a rope to a low pulley and set the weight to a moderate load.\n2. Stand facing away from the machine, grab the rope with both hands, and extend your arms overhead.\n3. Keeping your arms straight, pull the rope down and forward towards your hips, using your lats.\n4. Squeeze your lats at the bottom, then slowly return to the starting position.\n5. Maintain a slight bend in your elbows to keep tension on the lats.',
  ),
  ExercisePoolEntry(
    id: 'back_cable_straight_arm_pulldown',
    name: 'Cable Straight-Arm Pulldown',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats**\n\n1. Attach a straight bar or rope to a high pulley.\n2. Stand facing the machine, take a step back, and grab the bar with an overhand grip, arms straight.\n3. Keeping your arms straight, push the bar down towards your thighs by hinging at the shoulders, squeezing your lats.\n4. Pause at the bottom, then slowly return to the starting position.\n5. Keep a slight bend in your elbows throughout to maintain tension on the lats.',
  ),
  ExercisePoolEntry(
    id: 'back_db_bent_over_row',
    name: 'Dumbbell Bent-Over Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Stand with feet shoulder‑width apart, holding a dumbbell in each hand, palms facing your body.\n2. Bend at the hips with a flat back, torso nearly parallel to the floor, allowing the weights to hang straight down.\n3. Pull the dumbbells towards your lower chest, driving your elbows back and squeezing your shoulder blades.\n4. Pause at the top, then lower the weights with control to the starting position.\n5. Keep your core tight and avoid using momentum.',
  ),
  ExercisePoolEntry(
    id: 'back_db_incline_row',
    name: 'Incline Dumbbell Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Back, Biceps**\n\n1. Set an incline bench to about 30–45° and lie face down on it, holding a dumbbell in each hand, arms hanging straight down.\n2. Pull the dumbbells up towards your chest, driving your elbows back and squeezing your shoulder blades.\n3. Pause at the peak contraction, then lower the weights with control.\n4. Keep your neck relaxed and your chest against the bench.\n5. This variation reduces lower back strain and focuses on upper back development.',
  ),
  ExercisePoolEntry(
    id: 'back_db_pullover',
    name: 'Dumbbell Pullover',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats, Chest**\n\n1. Lie across a flat bench with only your upper back supported, feet firmly on the floor.\n2. Hold a single dumbbell with both hands, arms extended above your chest, palms pressing against the underside of the top plate.\n3. Keeping your arms slightly bent, lower the dumbbell in an arc behind your head until you feel a stretch in your lats.\n4. Use your lats to pull the dumbbell back up to the starting position, squeezing your lats at the top.\n5. Keep your hips low and your core stable throughout.',
  ),
  ExercisePoolEntry(
    id: 'back_selector_pulldown_wide_grip',
    name: 'Wide-Grip Lat Pulldown',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Back',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats (Width)**\n\n1. Use a wide‑grip bar on the lat pulldown machine, with your hands placed much wider than shoulder‑width.\n2. Sit with your thighs secured, lean back slightly, and pull the bar down to your upper chest.\n3. Focus on squeezing your lats and driving your elbows down and outward.\n4. Return slowly, feeling the stretch in your lats.\n5. This variation is excellent for developing lat width and the V‑taper.',
  ),
  ExercisePoolEntry(
    id: 'back_selector_seated_row',
    name: 'Selectorized Seated Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Back',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Sit on the seated row machine, brace your feet against the footplates, and keep your knees slightly bent.\n2. Grasp the V‑handle or bar, lean forward slightly at the hips, and then pull the handle towards your abdomen.\n3. Squeeze your shoulder blades together at the peak contraction, then return slowly with control.\n4. Keep your back straight and avoid using excessive momentum.\n5. Adjust the seat height so the handles are at chest level for optimal range of motion.',
  ),
  ExercisePoolEntry(
    id: 'pull_band_single_arm_row',
    name: 'Band Single-Arm Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Anchor a band at chest height.\n2. Step back, grab the handle with one hand, and stand with your feet shoulder‑width apart.\n3. Pull the handle towards your hip, squeezing your lat, while keeping your torso stable.\n4. Return slowly with control.\n5. Complete all reps on one side before switching.',
  ),
  ExercisePoolEntry(
    id: 'pull_bw_bird_dog_row',
    name: 'Bird Dog Row Hold',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Glutes, Core**\n\n1. Start on all fours with hands under shoulders and knees under hips.\n2. Extend your right arm forward and left leg back, keeping your hips square and spine neutral.\n3. Hold this position for the prescribed time, maintaining stability.\n4. Lower with control, then switch sides.\n5. This improves balance, core strength, and posterior chain activation.',
  ),
  ExercisePoolEntry(
    id: 'pull_bw_door_frame_rows',
    name: 'Door Frame Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Stand facing a sturdy door frame, grip both sides at chest height with an overhand grip.\n2. Lean back with your body straight and heels on the floor, arms fully extended.\n3. Pull your chest toward the door frame by driving your elbows back, squeezing your shoulder blades.\n4. Lower with control to the starting position.\n5. Keep your core tight to maintain a straight body line.',
  ),
  ExercisePoolEntry(
    id: 'pull_bw_inverted_row_feet_elevated',
    name: 'Feet-Elevated Inverted Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Set up an inverted row station (bar or table edge) with your feet elevated on a bench or chair.\n2. Grip the bar with an overhand grip, hands shoulder‑width apart, body straight.\n3. Pull your chest to the bar, squeezing your shoulder blades.\n4. Lower with control to full extension.\n5. The elevated feet increase the load, making the exercise more challenging.',
  ),
  ExercisePoolEntry(
    id: 'pull_bw_superman_hold',
    name: 'Superman Hold',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Glutes**\n\n1. Lie face down on the floor with your arms extended forward and legs straight.\n2. Lift your arms, chest, and legs off the floor simultaneously, squeezing your glutes and lower back.\n3. Hold this position for the prescribed time, maintaining tension.\n4. Keep your neck neutral by looking down.\n5. Breathe steadily and avoid holding your breath.',
  ),
  ExercisePoolEntry(
    id: 'pull_bw_towel_rows',
    name: 'Towel Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.forearms,
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps, Forearms**\n\n1. Loop a towel around a sturdy post or door handle, grab both ends with an overhand grip.\n2. Lean back, keeping your body straight, arms extended.\n3. Pull your torso toward the anchor point by driving your elbows back, squeezing your shoulder blades.\n4. Return slowly with control, keeping tension in the towel.\n5. This also strengthens grip and forearms.',
  ),
  ExercisePoolEntry(
    id: 'pull_bw_wall_angels',
    name: 'Wall Angels',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Back, Rear Delts**\n\n1. Stand with your back flat against a wall, feet about 6 inches from the wall.\n2. Place your arms against the wall in a "W" shape (elbows bent at 90°, hands at shoulder height).\n3. Slowly slide your arms overhead, keeping your wrists and elbows in contact with the wall.\n4. Return to the "W" position with control.\n5. This improves shoulder mobility and strengthens the upper back.',
  ),
  ExercisePoolEntry(
    id: 'pull_cable_single_arm_lat_pulldown',
    name: 'Single-Arm Lat Pulldown',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lats, Biceps**\n\n1. Attach a single D‑handle to a high pulley.\n2. Sit on the machine, grab the handle with one hand, and lean back slightly.\n3. Pull the handle down towards your hip, driving your elbow back and squeezing your lat.\n4. Return slowly with control.\n5. Complete all reps on one side before switching.',
  ),
  ExercisePoolEntry(
    id: 'pull_db_renegade_rows',
    name: 'Renegade Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.absCore,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Core, Biceps**\n\n1. Start in a high plank position with a dumbbell in each hand, hands directly under your shoulders.\n2. Keep your core braced and hips stable, then row the right dumbbell up towards your hip, squeezing your lat.\n3. Lower the dumbbell back to the floor with control.\n4. Repeat on the left side, alternating each rep.\n5. This movement requires significant core stability; use a light weight to maintain form.',
  ),
  ExercisePoolEntry(
    id: 'pull_kb_renagade_row',
    name: 'Kettlebell Renegade Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.absCore,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Core, Biceps**\n\n1. Start in a high plank position with a kettlebell in each hand, hands directly under your shoulders.\n2. Keep your core braced and hips stable, then row the right kettlebell up towards your hip, squeezing your lat.\n3. Lower the kettlebell back to the floor with control.\n4. Repeat on the left side, alternating each rep.\n5. This movement requires significant core stability; use a light weight to maintain form.',
  ),
  ExercisePoolEntry(
    id: 'pull_smith_single_arm_row',
    name: 'Smith Single-Arm Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps (Unilateral)**\n\n1. Set the Smith bar at waist height.\n2. Stand sideways to the bar, grip it with one hand, and keep your feet shoulder‑width apart for balance.\n3. Pull the bar towards your hip, driving your elbow back and squeezing your lat.\n4. Lower with control.\n5. Complete all reps on one side before switching.',
  ),
  ExercisePoolEntry(
    id: 'upper_cable_seated_row',
    name: 'Seated Cable Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Sit at the cable row station with your knees slightly bent and feet braced.\n2. Grip the handle (V‑bar or close‑grip) and extend your arms forward.\n3. Pull the handle towards your torso, squeezing your shoulder blades together.\n4. Pause, then slowly return to the starting position, keeping your back straight.',
  ),
  ExercisePoolEntry(
    id: 'upper_db_dumbbell_rows',
    name: 'Dumbbell Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.back,
      MuscleGroup.biceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Back, Biceps**\n\n1. Place your left knee and hand on a flat bench, keeping your back flat and parallel to the floor.\n2. Hold a dumbbell in your right hand, letting it hang straight down.\n3. Pull the dumbbell up towards your hip, squeezing your lats and biceps.\n4. Lower with control, then complete all reps on one side before switching.',
  ),
];
