// lib/engines/workout_engine/shared/exercises/catalog/definitions/chest_exercises.dart
// ⚠️ AUTO-GENERATED – DO NOT EDIT MANUALLY

import 'package:gymgenius/domain/enums/exports.dart';
import 'package:gymgenius/engines/workout_engine/shared/exercise_pool_entry.dart';

/// Canonical definitions for chest exercises.
const List<ExercisePoolEntry> chestDefinitions = [
  ExercisePoolEntry(
    id: 'chest_band_decline_press',
    name: 'Resistance Band Decline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Band press emphasizing lower chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_band_fly',
    name: 'Resistance Band Chest Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Band fly focusing on chest contraction.',
  ),
  ExercisePoolEntry(
    id: 'chest_band_incline_press',
    name: 'Resistance Band Incline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Incline chest press using anchored resistance bands.',
  ),
  ExercisePoolEntry(
    id: 'chest_band_press',
    name: 'Resistance Band Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Standing chest press using resistance bands.',
  ),
  ExercisePoolEntry(
    id: 'chest_band_single_press',
    name: 'Single Arm Band Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Single-arm chest press improving stability and unilateral strength.',
  ),
  ExercisePoolEntry(
    id: 'chest_bb_close_press',
    name: 'Close Grip Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Close grip variation increasing triceps contribution while training the chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_bb_flat_press',
    name: 'Barbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'The primary strength exercise for chest development.',
  ),
  ExercisePoolEntry(
    id: 'chest_bb_floor_press',
    name: 'Barbell Floor Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Press performed from the floor to reduce shoulder stress.',
  ),
  ExercisePoolEntry(
    id: 'chest_bb_incline_press',
    name: 'Incline Barbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Heavy incline pressing movement emphasizing the upper chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_bb_spoto_press',
    name: 'Spoto Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Paused bench press variation improving control and pressing strength.',
  ),
  ExercisePoolEntry(
    id: 'chest_bench_db_fly',
    name: 'Incline Dumbbell Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.adjustableBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Isolation exercise emphasizing chest stretch.',
  ),
  ExercisePoolEntry(
    id: 'chest_bench_decline_db_press',
    name: 'Decline Bench Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.adjustableBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Decline dumbbell press targeting the lower chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_bench_incline_db_press',
    name: 'Incline Bench Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.adjustableBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Incline bench press emphasizing the upper pectorals.',
  ),
  ExercisePoolEntry(
    id: 'chest_bench_neutral_press',
    name: 'Neutral Grip Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.adjustableBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Neutral grip press reducing shoulder stress.',
  ),
  ExercisePoolEntry(
    id: 'chest_bench_squeeze_press',
    name: 'Dumbbell Squeeze Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.adjustableBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Continuous dumbbell squeeze increases chest activation.',
  ),
  ExercisePoolEntry(
    id: 'chest_bw_archer_push_up',
    name: 'Archer Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Advanced unilateral push-up increasing chest strength.',
  ),
  ExercisePoolEntry(
    id: 'chest_bw_decline_push_up',
    name: 'Decline Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Feet elevated push-up emphasizing the upper chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_bw_diamond_push_up',
    name: 'Diamond Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Close-grip push-up increasing inner chest and triceps activation.',
  ),
  ExercisePoolEntry(
    id: 'chest_bw_plyo_push_up',
    name: 'Plyometric Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Explosive push-up for power development.',
  ),
  ExercisePoolEntry(
    id: 'chest_bw_push_up',
    name: 'Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Classic bodyweight push exercise for chest, shoulders and triceps.',
  ),
  ExercisePoolEntry(
    id: 'chest_bw_wide_push_up',
    name: 'Wide Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Wide hand placement increases chest activation.',
  ),
  ExercisePoolEntry(
    id: 'chest_cable_crossover',
    name: 'Cable Crossover',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Crossover movement providing constant tension on the chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_cable_fly',
    name: 'Cable Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Isolation fly movement for chest contraction and stretch.',
  ),
  ExercisePoolEntry(
    id: 'chest_cable_high_fly',
    name: 'High Cable Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'High-to-low fly emphasizing the lower chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_cable_low_fly',
    name: 'Low Cable Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Low-to-high fly emphasizing the upper chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_cable_single_arm_fly',
    name: 'Single Arm Cable Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Unilateral fly for correcting imbalances and improving control.',
  ),
  ExercisePoolEntry(
    id: 'chest_chair_decline_pushup',
    name: 'Decline Bench Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Feet elevated on a bench to increase upper chest activation.',
  ),
  ExercisePoolEntry(
    id: 'chest_chair_explosive_pushup',
    name: 'Explosive Bench Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Explosive push-up using a bench to develop upper-body power.',
  ),
  ExercisePoolEntry(
    id: 'chest_chair_incline_pushup',
    name: 'Incline Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Hands elevated on a bench to reduce push-up difficulty.',
  ),
  ExercisePoolEntry(
    id: 'chest_chair_offset_pushup',
    name: 'Offset Bench Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'One hand on the bench and one on the floor to challenge stability.',
  ),
  ExercisePoolEntry(
    id: 'chest_chair_staggered_pushup',
    name: 'Staggered Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'One hand elevated on a bench to create asymmetrical loading.',
  ),
  ExercisePoolEntry(
    id: 'chest_db_decline_press',
    name: 'Decline Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Decline dumbbell press targeting the lower chest fibers.',
  ),
  ExercisePoolEntry(
    id: 'chest_db_flat_press',
    name: 'Dumbbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Classic dumbbell press for overall chest development.',
  ),
  ExercisePoolEntry(
    id: 'chest_db_fly',
    name: 'Dumbbell Chest Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Isolation movement providing a deep chest stretch.',
  ),
  ExercisePoolEntry(
    id: 'chest_db_incline_press',
    name: 'Incline Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Incline pressing movement emphasizing the upper chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_db_neutral_press',
    name: 'Neutral Grip Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Neutral grip press reducing shoulder stress.',
  ),
  ExercisePoolEntry(
    id: 'chest_db_single_press',
    name: 'Single Arm Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Unilateral press improving stability and chest strength.',
  ),
  ExercisePoolEntry(
    id: 'chest_dip_band_assisted',
    name: 'Band Assisted Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Dips with a resistance band for assistance to build strength.',
  ),
  ExercisePoolEntry(
    id: 'chest_dip_bench_assisted',
    name: 'Bench Assisted Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Dips with feet on a bench to reduce load and learn the movement.',
  ),
  ExercisePoolEntry(
    id: 'chest_dip_parallel_bars',
    name: 'Chest Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Bodyweight dip with a forward lean to emphasize the chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_dip_ring',
    name: 'Ring Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Dips performed on rings for increased stability demand.',
  ),
  ExercisePoolEntry(
    id: 'chest_dip_weighted',
    name: 'Weighted Chest Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: 'Weighted dip for maximal chest and triceps strength.',
  ),
  ExercisePoolEntry(
    id: 'chest_selector_chest_press',
    name: 'Selectorized Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Machine chest press with a fixed path and selectorized weight stack.',
  ),
  ExercisePoolEntry(
    id: 'chest_selector_decline_press',
    name: 'Selectorized Decline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Decline chest press machine focusing on the lower chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_selector_incline_press',
    name: 'Selectorized Incline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Incline chest press machine targeting the upper chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_selector_pec_deck_fly',
    name: 'Pec Deck Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Machine fly that isolates the chest with constant tension.',
  ),
  ExercisePoolEntry(
    id: 'chest_selector_plate_loaded_press',
    name: 'Plate-Loaded Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Plate-loaded chest press providing a natural feel and heavy loading.',
  ),
  ExercisePoolEntry(
    id: 'chest_smith_close_press',
    name: 'Smith Close Grip Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Close grip press with enhanced stability.',
  ),
  ExercisePoolEntry(
    id: 'chest_smith_decline_press',
    name: 'Smith Decline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Lower chest emphasis using a fixed bar path.',
  ),
  ExercisePoolEntry(
    id: 'chest_smith_flat_press',
    name: 'Smith Machine Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Machine-guided bench press for controlled chest development.',
  ),
  ExercisePoolEntry(
    id: 'chest_smith_incline_press',
    name: 'Smith Incline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Upper chest press performed on the Smith machine.',
  ),
  ExercisePoolEntry(
    id: 'chest_smith_reverse_press',
    name: 'Smith Reverse Grip Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: 'Reverse grip press increasing upper chest activation.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_band_chest_fly',
    name: 'Band Chest Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest**\n\n1. Anchor a band at chest height.\n2. Hold handles, bring hands together in front.\n3. Squeeze chest, return.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_band_chest_press',
    name: 'Band Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Anchor a band at chest height, step forward.\n2. Press handles forward until arms are straight.\n3. Return slowly.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_bb_decline_bench_press',
    name: 'Decline Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Chest, Triceps**\n\n1. Lie on a decline bench.\n2. Lower the bar to your lower chest.\n3. Press back up.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_bb_flat_bench_press',
    name: 'Barbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps, Shoulders**\n\n1. Lie on a flat bench, grip the bar slightly wider than shoulder-width.\n2. Lower the bar to mid-chest.\n3. Press back up to full extension.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_bb_incline_bench_press',
    name: 'Incline Barbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Chest, Shoulders**\n\n1. Set an incline bench at 30-45°.\n2. Press the barbell from shoulder height.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_bw_archer_pushups',
    name: 'Archer Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders (unilateral)**\n\n1. Widen your stance and shift weight to one side.\n2. Lower chest towards that hand.\n3. Push up and alternate sides.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_bw_decline_pushups',
    name: 'Decline Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Chest, Shoulders**\n\n1. Place feet on an elevated surface, hands on the floor.\n2. Lower chest towards the floor with control.\n3. Press back up to full extension.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_bw_incline_pushups',
    name: 'Incline Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Chest, Shoulders**\n\n1. Place hands on an elevated surface (e.g. bench or step).\n2. Lower chest towards the surface.\n3. Press back up.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_bw_plyometric_pushups',
    name: 'Plyometric Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps, Shoulders**\n\n1. Explosive push-up with hands leaving the ground.\n2. Land softly and repeat.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_bw_pushups',
    name: 'Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps, Shoulders**\n\n1. Start in plank position.\n2. Lower chest to floor.\n3. Push back up.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_bw_wide_pushups',
    name: 'Wide Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders**\n\n1. Place hands wider than shoulder-width apart.\n2. Lower chest towards the floor.\n3. Press back up.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_cable_chest_press',
    name: 'Cable Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Set cables at chest height, grip handles.\n2. Press handles forward until arms are extended.\n3. Return slowly.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_cable_crossover',
    name: 'Cable Crossover',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest**\n\n1. Stand between two high pulleys, grip handles.\n2. Pull handles down and together in front of you.\n3. Squeeze chest, return slowly.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_cable_flyes',
    name: 'Cable Flyes',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Fly movement)**\n\n1. Set cables at chest height, grip handles.\n2. Bring hands together in front of your chest.\n3. Squeeze chest and return slowly.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_chair_decline_push_ups',
    name: 'Decline Push-ups (feet on chair)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Chest, Shoulders**\n\n1. Place feet on a chair, hands on the floor.\n2. Perform push-ups with elevated feet.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_chair_incline_push_ups',
    name: 'Incline Push-ups (hands on chair)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders**\n\n1. Place hands on a chair, body in plank.\n2. Lower chest towards the chair.\n3. Press back up.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_chair_plyometric_push_ups',
    name: 'Plyometric Push-ups (hands on chair)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Place hands on a stable chair or bench.\n2. Lower chest towards the chair.\n3. Explosively push up, hands leaving the surface.\n4. Land softly and repeat.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_db_dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps, Shoulders**\n\n1. Lie on a bench with dumbbells.\n2. Press up from chest level.\n3. Lower slowly.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_db_floor_press',
    name: 'Dumbbell Floor Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Lie on the floor with dumbbells in each hand.\n2. Press up from the floor, elbows touching the floor at the bottom.\n3. Extend arms fully.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_db_incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Chest, Shoulders**\n\n1. Incline bench at 30-45°.\n2. Press dumbbells from shoulder height.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_dip_band_assisted_dips',
    name: 'Band-Assisted Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Loop a band around the dip bars.\n2. Place knees or feet in the band for assistance.\n3. Perform dips with reduced load.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_dip_chest_dips',
    name: 'Chest Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest**\n\n1. Lean forward slightly on the dip bars.\n2. Lower until your chest is stretched.\n3. Press up.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_dip_dips',
    name: 'Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps, Shoulders**\n\n1. Hoist on parallel bars.\n2. Lower body until elbows are at 90°.\n3. Push back up.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_dip_weighted_dips',
    name: 'Weighted Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps, Shoulders**\n\n1. Attach weight to a dip belt.\n2. Perform dips with extra load.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_selector_dip_machine',
    name: 'Assisted Dip Machine',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps, Shoulders**\n\n1. Kneel on the assisted dip machine, grip handles.\n2. Lower yourself by bending elbows.\n3. Press back up.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_selector_incline_chest_press',
    name: 'Selectorized Incline Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Chest, Shoulders**\n\n1. Sit at the incline chest press machine.\n2. Press forward and up.\n3. Return with control.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_selector_machine_chest_press',
    name: 'Machine Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders, Triceps**\n\n1. Sit at the machine, grips at chest height.\n2. Press forward until arms are extended.\n3. Return slowly.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_selector_pec_deck_fly',
    name: 'Pec Deck Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest**\n\n1. Sit on the pec deck, forearms against pads.\n2. Squeeze chest to bring pads together.\n3. Return with control.',
  ),
  ExercisePoolEntry(
    id: 'push_band_chest_press',
    name: 'Band Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Anchor a band at chest height, step forward.\n2. Press the handles forward until arms are straight.\n3. Return slowly.',
  ),
  ExercisePoolEntry(
    id: 'push_bb_barbell_bench_press',
    name: 'Barbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders, Triceps**\n\n1. Lie on a flat bench, grip the barbell slightly wider than shoulder-width.\n2. Unrack the bar and lower it to your mid-chest.\n3. Press the bar back up to full extension.',
  ),
  ExercisePoolEntry(
    id: 'push_bb_decline_barbell_bench_press',
    name: 'Decline Barbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Chest, Triceps**\n\n1. Lie on a decline bench, feet secured.\n2. Lower the bar to your lower chest.\n3. Press back up to full extension.',
  ),
  ExercisePoolEntry(
    id: 'push_bw_archer_push_ups',
    name: 'Archer Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders (unilateral)**\n\n1. Widen stance, shift weight to one side.\n2. Lower chest towards one hand.\n3. Push up and alternate sides.',
  ),
  ExercisePoolEntry(
    id: 'push_bw_decline_push_ups',
    name: 'Decline Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Chest, Shoulders**\n\n1. Place your feet on an elevated surface, hands on the floor.\n2. Lower your chest towards the floor with control.\n3. Press back up to full extension.',
  ),
  ExercisePoolEntry(
    id: 'push_bw_plyometric_push_ups',
    name: 'Plyometric Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders, Triceps**\n\n1. Explosive push-up with hands leaving the ground.\n2. Land softly and repeat.',
  ),
  ExercisePoolEntry(
    id: 'push_bw_push_ups',
    name: 'Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders, Triceps**\n\n1. Start in a high plank position with hands slightly wider than shoulders.\n2. Lower your body until your chest nearly touches the floor.\n3. Press back up to the starting position, fully extending arms.\n4. Repeat for desired reps.',
  ),
  ExercisePoolEntry(
    id: 'push_bw_wide_push_ups',
    name: 'Wide Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders**\n\n1. Hands wider than shoulders.\n2. Lower chest towards floor.\n3. Press up.',
  ),
  ExercisePoolEntry(
    id: 'push_cable_chest_fly',
    name: 'Cable Chest Fly (standing)',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest**\n\n1. Set pulleys at chest height, grip handles.\n2. Bring handles together in front of your chest.\n3. Squeeze chest, then return.',
  ),
  ExercisePoolEntry(
    id: 'push_cable_crossover',
    name: 'Cable Crossover',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest**\n\n1. Stand between two high pulleys, grip a handle in each hand.\n2. Pull the handles down and together in front of your body.\n3. Squeeze your chest, then return slowly.',
  ),
  ExercisePoolEntry(
    id: 'push_chair_decline_push_ups',
    name: 'Decline Push-ups (feet on chair)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Chest**\n\n1. Place feet on a chair, hands on the floor.\n2. Perform push-ups with elevated feet.',
  ),
  ExercisePoolEntry(
    id: 'push_chair_incline_push_ups',
    name: 'Incline Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders**\n\n1. Place hands on a bench or chair, body in plank.\n2. Lower chest towards the bench.\n3. Press back up.',
  ),
  ExercisePoolEntry(
    id: 'push_chair_plyometric_push_ups',
    name: 'Plyometric Push-ups (hands on chair)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Place hands on a stable chair or bench.\n2. Lower chest towards the chair.\n3. Explosively push up, hands leaving the surface.\n4. Land softly and repeat.',
  ),
  ExercisePoolEntry(
    id: 'push_db_dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders, Triceps**\n\n1. Lie on a bench with dumbbells in each hand, palms facing forward.\n2. Press the dumbbells up until arms are fully extended.\n3. Lower them slowly to the sides of your chest.\n4. Press back up explosively.',
  ),
  ExercisePoolEntry(
    id: 'push_db_incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Chest, Shoulders**\n\n1. Set an incline bench to about 30-45 degrees.\n2. Press dumbbells from shoulder height upward.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'push_dip_band_assisted_dips',
    name: 'Band-Assisted Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Loop a band around the dip bars.\n2. Place knees or feet in the band for assistance.\n3. Perform dips with reduced load.',
  ),
  ExercisePoolEntry(
    id: 'push_dip_chest_dips',
    name: 'Chest Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest**\n\n1. Lean forward slightly on the dip bars.\n2. Lower until your chest is stretched.\n3. Press up.',
  ),
  ExercisePoolEntry(
    id: 'push_dip_dips',
    name: 'Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps, Shoulders**\n\n1. Hoist yourself up on parallel bars or a dip station.\n2. Lower your body by bending your elbows until shoulders are below elbows.\n3. Push back up to start.',
  ),
  ExercisePoolEntry(
    id: 'push_dip_weighted_dips',
    name: 'Weighted Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps, Shoulders**\n\n1. Attach weight to a dip belt.\n2. Perform dips with extra load.',
  ),
  ExercisePoolEntry(
    id: 'push_kb_kettlebell_floor_press',
    name: 'Kettlebell Floor Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Lie on the floor with a kettlebell in each hand.\n2. Press them up from chest level.\n3. Lower with control, stopping at the floor.',
  ),
  ExercisePoolEntry(
    id: 'push_selector_dips_assisted',
    name: 'Assisted Dip Machine',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps, Shoulders**\n\n1. Kneel on the assisted dip machine, grip the handles.\n2. Lower yourself by bending elbows.\n3. Press back up.',
  ),
  ExercisePoolEntry(
    id: 'push_selector_incline_chest_press',
    name: 'Selectorized Incline Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Chest, Shoulders**\n\n1. Sit at the incline chest press machine.\n2. Press forward and up.\n3. Return with control.',
  ),
  ExercisePoolEntry(
    id: 'push_selector_machine_chest_press',
    name: 'Machine Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders, Triceps**\n\n1. Sit at the chest press machine, grips at chest height.\n2. Press forward until arms are extended.\n3. Return slowly to the starting position.',
  ),
  ExercisePoolEntry(
    id: 'push_selector_pec_deck_fly',
    name: 'Pec Deck Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest**\n\n1. Sit on the pec deck machine, forearms against the pads.\n2. Squeeze your chest to bring the pads together.\n3. Return with control.',
  ),
  ExercisePoolEntry(
    id: 'push_smith_decline_press',
    name: 'Smith Machine Decline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Chest, Triceps**\n\n1. Set a decline bench under the Smith machine.\n2. Press the bar to your lower chest.',
  ),
  ExercisePoolEntry(
    id: 'push_smith_incline_press',
    name: 'Smith Machine Incline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Chest, Shoulders**\n\n1. Set an incline bench under the Smith machine.\n2. Press the bar up and down along the fixed path.',
  ),
  ExercisePoolEntry(
    id: 'push_smith_smith_machine_bench_press',
    name: 'Smith Machine Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders, Triceps**\n\n1. Lie on a flat bench under the Smith machine bar.\n2. Unrack and lower the bar to your chest.\n3. Press back up to full extension along the fixed path.',
  ),
  ExercisePoolEntry(
    id: 'upper_band_chest_press',
    name: 'Band Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Anchor band behind you at chest height.\n2. Press handles forward.',
  ),
  ExercisePoolEntry(
    id: 'upper_bb_bench_press',
    name: 'Barbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Lie on bench, grip slightly wider than shoulders.\n2. Lower bar to mid-chest.\n3. Press up.',
  ),
  ExercisePoolEntry(
    id: 'upper_bw_push_ups',
    name: 'Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders, Triceps**\n\n1. Plank position.\n2. Lower and push up.',
  ),
  ExercisePoolEntry(
    id: 'upper_bw_wide_push_ups',
    name: 'Wide Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders**\n\n1. Place hands wider than shoulder-width.\n2. Lower chest towards floor.\n3. Press up.',
  ),
  ExercisePoolEntry(
    id: 'upper_cable_crossover',
    name: 'Cable Crossover',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest**\n\n1. Stand between two high pulleys.\n2. Bring handles together in front of chest.',
  ),
  ExercisePoolEntry(
    id: 'upper_db_dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders, Triceps**\n\n1. Lie on bench.\n2. Press dumbbells.',
  ),
  ExercisePoolEntry(
    id: 'upper_selector_chest_press',
    name: 'Machine Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Sit at machine, grips at chest height.\n2. Press forward until arms extended.',
  ),
  ExercisePoolEntry(
    id: 'upper_selector_pec_deck',
    name: 'Pec Deck Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest**\n\n1. Sit with forearms against pads.\n2. Squeeze chest to bring pads together.',
  ),
  ExercisePoolEntry(
    id: 'upper_smith_bench_press',
    name: 'Smith Machine Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Lie on bench under bar.\n2. Press up along fixed path.',
  ),
];
