// lib/engines/workout_engine/shared/exercises/catalog/definitions/chest_exercises.dart
// ⚠️ AUTO-GENERATED – DO NOT EDIT MANUALLY

import 'package:gymgenius/domain/enums/exports.dart';
import 'package:gymgenius/engines/workout_engine/shared/exercise_pool_entry.dart';

/// Canonical definitions for chest exercises.
const List<ExercisePoolEntry> chestDefinitions = [
  ExercisePoolEntry(
    id: 'chest_band_decline_press',
    name: 'Resistance Band Decline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Lower Chest (Band)**\n\n1. Anchor the band at waist height behind you.\n2. Hold the band and press forward and slightly downward (decline angle).\n3. Squeeze your lower chest at the end of the movement.\n4. Return with control.',
  ),
  ExercisePoolEntry(
    id: 'chest_band_fly',
    name: 'Resistance Band Chest Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Band Fly)**\n\n1. Anchor the band behind you at shoulder height.\n2. Hold the band ends with arms extended out to the sides, slightly bent elbows.\n3. Bring your hands together in front of your chest, squeezing hard.\n4. Return slowly, resisting the pull of the band.',
  ),
  ExercisePoolEntry(
    id: 'chest_band_incline_press',
    name: 'Resistance Band Incline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Upper Chest (Band)**\n\n1. Anchor the band low (around your feet) and press upward at an incline.\n2. Or anchor behind you at floor level, and press forward and upward.\n3. Focus on the upper chest contraction at the top.',
  ),
  ExercisePoolEntry(
    id: 'chest_band_press',
    name: 'Resistance Band Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Band)**\n\n1. Anchor a resistance band behind you at chest height (e.g., a door frame).\n2. Hold the handles or band ends at chest level, palms forward.\n3. Press forward and inward, extending your arms fully.\n4. Squeeze your chest at the peak, then return slowly, controlling the negative.',
  ),
  ExercisePoolEntry(
    id: 'chest_band_single_press',
    name: 'Single Arm Band Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Unilateral Band)**\n\n1. Anchor the band at chest height on one side.\n2. Step sideways to create tension, grab the handle with one hand.\n3. Press forward and inward, stabilising your core.\n4. Return slowly and switch sides.',
  ),
  ExercisePoolEntry(
    id: 'chest_bb_flat_press',
    name: 'Barbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Overall Mass)**\n\n1. Lie on a flat bench, eyes directly under the bar.\n2. Grip the bar slightly wider than shoulder‑width, wrap your thumbs around.\n3. Unrack the bar and hold it above your chest with arms extended.\n4. Lower the bar to your mid‑chest while keeping your elbows at about 75°.\n5. Drive the bar back up explosively, squeezing your chest.\n6. Keep your feet planted and your back slightly arched.',
  ),
  ExercisePoolEntry(
    id: 'chest_bb_floor_press',
    name: 'Barbell Floor Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Lockout Strength)**\n\n1. Lie on the floor with a barbell held above your chest.\n2. Lower the bar until your upper arms touch the floor.\n3. Pause briefly, then press back up with maximal force.\n4. This limits shoulder range, reducing impingement risk while building lockout power.',
  ),
  ExercisePoolEntry(
    id: 'chest_bb_incline_press',
    name: 'Incline Barbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Upper Chest**\n\n1. Set the bench to a 30–45° incline.\n2. Grip the bar slightly wider than shoulder‑width.\n3. Unrack and lower the bar to your upper chest, just below the collarbone.\n4. Press up with control, driving your upper back into the pad.\n5. Avoid locking your elbows at the top to keep tension on the chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_bb_spoto_press',
    name: 'Spoto Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Pause & Control)**\n\n1. Perform a standard bench press setup.\n2. Lower the bar until it is 1–2 inches above your chest.\n3. Hold that position for a full second, maintaining tightness.\n4. Press the bar back up without bouncing.\n5. This variation improves technique and strength off the chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_bench_db_fly',
    name: 'Incline Dumbbell Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.adjustableBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Stretch & Contraction)**\n\n1. Lie on an incline bench with dumbbells held above your chest, palms facing each other.\n2. Keep a slight bend in your elbows throughout the movement.\n3. Lower the weights out to the sides in a wide arc until you feel a deep stretch in your chest.\n4. Bring them back together in a hugging motion, squeezing your pectorals at the top.\n5. Control the descent and avoid overextending your shoulders.',
  ),
  ExercisePoolEntry(
    id: 'chest_bench_decline_db_press',
    name: 'Decline Bench Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.adjustableBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Lower Chest**\n\n1. Set the bench to a decline position (head lower than hips).\n2. Secure your feet under the pads, hold dumbbells above your chest.\n3. Lower the weights to the sides of your lower chest with a controlled tempo.\n4. Press up forcefully, squeezing your lower pectorals.\n5. Keep your elbows tucked to protect your shoulders.',
  ),
  ExercisePoolEntry(
    id: 'chest_bench_incline_db_press',
    name: 'Incline Bench Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.adjustableBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Upper Chest**\n\n1. Set an adjustable bench to a 30–45° incline.\n2. Lie back with a dumbbell in each hand, resting them on your thighs.\n3. Kick the weights up to shoulder height, palms facing forward.\n4. Lower the dumbbells slowly to the sides of your chest, elbows at about 45°.\n5. Press them back up powerfully, squeezing your upper chest at the top.\n6. Keep your feet flat on the floor and your back slightly arched.',
  ),
  ExercisePoolEntry(
    id: 'chest_bench_neutral_press',
    name: 'Neutral Grip Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.adjustableBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Shoulder‑friendly)**\n\n1. Lie on a flat bench holding dumbbells with palms facing each other (neutral grip).\n2. Press the weights upward from chest level, keeping elbows close to your body.\n3. Lower with control until the dumbbells touch the sides of your chest.\n4. Press back up, focusing on chest contraction without flaring your elbows.',
  ),
  ExercisePoolEntry(
    id: 'chest_bench_squeeze_press',
    name: 'Dumbbell Squeeze Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.adjustableBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Mind‑Muscle Connection)**\n\n1. Hold a single dumbbell vertically between your palms, squeezing it firmly.\n2. Lie on a bench and press the dumbbell upward, maintaining constant inward pressure.\n3. Lower the dumbbell to your chest, keeping the squeeze throughout.\n4. Press back up, focusing on the isometric contraction of your chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_bw_archer_push_up',
    name: 'Archer Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest (Unilateral Strength)**\n\n1. Start in a wide push‑up position.\n2. Shift your weight onto one side, extending the other arm out to the side.\n3. Lower your chest toward the hand of the working side.\n4. Push back up, then repeat on the other side.\n5. This challenges stability and builds unilateral pressing strength.',
  ),
  ExercisePoolEntry(
    id: 'chest_bw_decline_push_up',
    name: 'Decline Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Chest**\n\n1. Place your feet on an elevated surface (bench, chair, step).\n2. Your hands are on the floor, directly under your shoulders.\n3. Perform a push‑up; the elevated feet shift more weight to your upper chest and shoulders.\n4. Lower until your chest is a few inches from the floor, then push up.',
  ),
  ExercisePoolEntry(
    id: 'chest_bw_plyo_push_up',
    name: 'Plyometric Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Power Development**\n\n1. Start in a standard push‑up position.\n2. Lower your chest toward the floor, then explode upward so your hands leave the floor.\n3. Clap your hands (if comfortable) and land softly, absorbing the impact.\n4. Immediately go into the next rep. This builds explosive strength and fast‑twitch fibers.',
  ),
  ExercisePoolEntry(
    id: 'chest_bw_push_up',
    name: 'Standard Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders, Triceps**\n\n1. Start in a high plank with hands slightly wider than shoulders.\n2. Keep your body in a straight line from head to heels, core engaged.\n3. Lower your chest toward the floor until your elbows reach at least 90°.\n4. Push back up to the starting position, exhaling at the top.\n5. Perform controlled reps, avoiding any sagging or arching of your back.',
  ),
  ExercisePoolEntry(
    id: 'chest_bw_wide_push_up',
    name: 'Wide Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest (Outer Pecs)**\n\n1. Place your hands significantly wider than shoulder‑width apart.\n2. As you lower, your elbows will flare out – this increases chest recruitment.\n3. Lower until your chest nearly touches the floor, then push up.\n4. Keep your core tight to prevent your hips from dropping.',
  ),
  ExercisePoolEntry(
    id: 'chest_cable_crossover',
    name: 'Cable Crossover',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Constant Tension)**\n\n1. Set pulleys at chest height, stand between them, grab handles.\n2. Step forward into a staggered stance, arms extended.\n3. Bring your hands together in front of your chest, crossing them slightly if desired.\n4. Hold the contraction for a second, then slowly return to the starting position.\n5. Keep your core braced and your shoulders down.',
  ),
  ExercisePoolEntry(
    id: 'chest_cable_fly',
    name: 'Cable Flyes',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
      'Push',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Isolation & Stretch)**\n\n1. Set both pulleys at shoulder height and attach D‑handles.\n2. Stand in the middle, grab the handles with palms facing down, and step forward into a split stance.\n3. Keeping a slight bend in your elbows, bring your hands together in front of your chest.\n4. Squeeze your chest at the peak contraction, then slowly return to the stretch position.\n5. Control the negative phase for maximum muscle fibre recruitment.',
  ),
  ExercisePoolEntry(
    id: 'chest_cable_high_fly',
    name: 'High Cable Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Lower Chest**\n\n1. Set pulleys to the highest position.\n2. Grab handles with palms facing down, step forward.\n3. Bring your hands downward and together in front of your lower chest.\n4. Squeeze at the bottom, then return slowly.\n5. This high‑to‑low path emphasises the lower sternal head.',
  ),
  ExercisePoolEntry(
    id: 'chest_cable_low_fly',
    name: 'Low Cable Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Upper Chest**\n\n1. Set pulleys to the lowest position, attach handles.\n2. Stand in the centre, grab handles with palms up (underhand grip).\n3. Bring your hands up and together in front of your upper chest.\n4. Squeeze at the top, then lower with control.\n5. This low‑to‑high path targets the upper pectoral fibres.',
  ),
  ExercisePoolEntry(
    id: 'chest_cable_single_arm_fly',
    name: 'Single Arm Cable Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Unilateral Correction)**\n\n1. Set a single pulley at chest height.\n2. Stand sideways, grab the handle with the arm farthest from the stack.\n3. Perform a fly motion across your body, bringing your hand to the centre.\n4. Squeeze and slowly return.\n5. This helps correct imbalances and improves control.',
  ),
  ExercisePoolEntry(
    id: 'chest_chair_decline_pushup',
    name: 'Decline Bench Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Chest**\n\n1. Place your feet on a chair or bench, hands on the floor.\n2. Perform a push‑up; the elevated feet increase the load on the upper chest.\n3. Lower until your chest is near the floor, then press up.',
  ),
  ExercisePoolEntry(
    id: 'chest_chair_explosive_pushup',
    name: 'Explosive Bench Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest (Power)**\n\n1. Place your hands on a sturdy chair, feet on the floor, body in a plank.\n2. Lower into a push‑up, then explode up so your hands leave the chair.\n3. Land softly and immediately go into the next rep.\n4. This builds upper‑body power and rate of force development.',
  ),
  ExercisePoolEntry(
    id: 'chest_chair_offset_pushup',
    name: 'Offset Bench Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest (Stability)**\n\n1. Place one hand on a chair and the other on the floor, but not in line – offset them for instability.\n2. Lower your chest toward the lower hand, then push up.\n3. This variation challenges your core and shoulder stabilisers.',
  ),
  ExercisePoolEntry(
    id: 'chest_chair_staggered_pushup',
    name: 'Staggered Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest (Asymmetrical Loading)**\n\n1. Place one hand on a chair (elevated) and the other on the floor, both in line with your shoulders.\n2. Lower your chest toward the floor, keeping your body straight.\n3. Push up, then switch sides. This creates a one‑sided emphasis and challenges stability.',
  ),
  ExercisePoolEntry(
    id: 'chest_db_decline_press',
    name: 'Decline Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Lower Chest**\n\n1. Set the bench to a decline.\n2. Secure your feet, hold dumbbells above your chest.\n3. Lower them to the sides of your lower chest, elbows tucked.\n4. Press up, squeezing the lower pecs.',
  ),
  ExercisePoolEntry(
    id: 'chest_db_flat_press',
    name: 'Dumbbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Overall)**\n\n1. Lie on a flat bench with dumbbells held at shoulder height, palms forward.\n2. Press the weights up over your chest, keeping them close together at the top.\n3. Lower with control to the sides of your chest, elbows at about 45°.\n4. Press back up, squeezing your chest at the top.\n5. Dumbbells allow a greater range of motion than a barbell.',
  ),
  ExercisePoolEntry(
    id: 'chest_db_fly',
    name: 'Dumbbell Chest Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Stretch & Isolation)**\n\n1. Lie on a flat bench with dumbbells above your chest, palms facing each other.\n2. Keep a slight bend in your elbows.\n3. Lower the weights out to the sides until you feel a stretch.\n4. Bring them back together in a hugging motion, squeezing the chest.\n5. Use light weight to focus on form and contraction.',
  ),
  ExercisePoolEntry(
    id: 'chest_db_incline_press',
    name: 'Incline Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Upper Chest**\n\n1. Set the bench to 30–45° incline.\n2. Lie back with dumbbells, press them above your chest.\n3. Lower them to the sides of your upper chest, keep elbows moderately flared.\n4. Press up, focusing on the upper pectoral squeeze at the top.',
  ),
  ExercisePoolEntry(
    id: 'chest_db_single_press',
    name: 'Single Arm Dumbbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Balance & Core)**\n\n1. Lie on a flat bench holding one dumbbell in one hand.\n2. Press it up, keeping your core engaged to stabilise your body.\n3. Lower and press for the prescribed reps, then switch sides.\n4. This corrects imbalances and builds core stability.',
  ),
  ExercisePoolEntry(
    id: 'chest_dip_band_assisted',
    name: 'Band Assisted Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest (Assisted Strength)**\n\n1. Loop a resistance band around the bars and place a knee or foot in it for support.\n2. Perform dips with a forward lean, using the band to assist at the bottom.\n3. As you get stronger, use a thinner band or do full bodyweight dips.',
  ),
  ExercisePoolEntry(
    id: 'chest_dip_bench_assisted',
    name: 'Bench Assisted Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest (Learning Phase)**\n\n1. Place a bench behind you and place your feet on it.\n2. Grip the parallel bars and lower yourself, using your feet on the bench to reduce the load.\n3. Push up with assistance, focusing on the movement pattern.\n4. Gradually reduce the leg assist as you gain strength.',
  ),
  ExercisePoolEntry(
    id: 'chest_dip_parallel_bars',
    name: 'Chest Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest (Lower Pecs)**\n\n1. Grip the parallel bars, lift yourself up, arms straight.\n2. Lean your torso forward (about 20–30°) to shift emphasis onto the chest.\n3. Lower your body until your shoulders are below your elbows or until you feel a stretch in your chest.\n4. Push back up powerfully, keeping your legs tucked behind you.\n5. Avoid flaring your elbows excessively to protect your shoulders.',
  ),
  ExercisePoolEntry(
    id: 'chest_dip_ring',
    name: 'Ring Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest (Stability)**\n\n1. Hang from gymnastic rings, support yourself with arms straight.\n2. Lean forward to engage the chest, then lower yourself slowly.\n3. At the bottom, your hands should be near your armpits.\n4. Press up, keeping the rings stable – this requires significant shoulder and core stability.',
  ),
  ExercisePoolEntry(
    id: 'chest_dip_weighted',
    name: 'Weighted Chest Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest (Maximal Load)**\n\n1. Attach a dip belt with a weight plate, or hold a dumbbell between your legs.\n2. Perform dips with a forward lean, lowering until a deep stretch in the chest.\n3. Drive up with controlled power.\n4. Use a spotter or safety pins if going to failure.',
  ),
  ExercisePoolEntry(
    id: 'chest_selector_chest_press',
    name: 'Selectorized Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Machine)**\n\n1. Adjust the seat so the handles are at chest height.\n2. Grip the handles, keep your back flat against the pad.\n3. Press forward until your arms are extended, squeezing your chest.\n4. Return slowly, controlling the weight throughout.\n5. This machine provides a fixed path, great for beginners.',
  ),
  ExercisePoolEntry(
    id: 'chest_selector_decline_press',
    name: 'Selectorized Decline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Lower Chest (Machine)**\n\n1. Sit in the decline press machine, handles at lower chest height.\n2. Press downward and forward, focusing on the lower sternal region.\n3. Return slowly and with control.',
  ),
  ExercisePoolEntry(
    id: 'chest_selector_incline_press',
    name: 'Selectorized Incline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Upper Chest (Machine)**\n\n1. Adjust the incline machine seat so handles are at upper chest level.\n2. Press upward and forward, squeezing your upper chest.\n3. Lower with control.\n4. Great for targeting the clavicular head.',
  ),
  ExercisePoolEntry(
    id: 'chest_selector_pec_deck_fly',
    name: 'Pec Deck Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
      'Chest & Triceps',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Isolation Machine)**\n\n1. Sit on the pec deck, position your forearms against the pads.\n2. Keep a slight bend in your elbows, chest out.\n3. Bring the pads together in front of your chest, squeezing hard.\n4. Return with control, feel the stretch.\n5. This isolates the pecs with constant tension.',
  ),
  ExercisePoolEntry(
    id: 'chest_selector_plate_loaded_press',
    name: 'Plate-Loaded Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Plate‑Loaded Machine)**\n\n1. Load plates on the machine, sit and adjust the seat.\n2. Grip the handles and press forward, maintaining a natural arc.\n3. Lower with control.\n4. This machine often feels more natural than selectorized and allows heavy loading.',
  ),
  ExercisePoolEntry(
    id: 'chest_smith_close_press',
    name: 'Smith Close Grip Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest + Triceps (Smith)**\n\n1. Use a flat bench, grip the bar shoulder‑width apart.\n2. Lower the bar to your lower chest, elbows tucked.\n3. Press up, focusing on triceps and inner chest.\n4. The Smith machine allows you to load heavy safely.',
  ),
  ExercisePoolEntry(
    id: 'chest_smith_decline_press',
    name: 'Smith Decline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Lower Chest (Smith)**\n\n1. Set a decline bench under the Smith bar.\n2. Lower the bar to your lower chest, keeping elbows tucked.\n3. Press up, squeezing the lower pecs.\n4. The fixed bar path reduces shoulder stress.',
  ),
  ExercisePoolEntry(
    id: 'chest_smith_flat_press',
    name: 'Smith Machine Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
      'Push',
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Chest (Smith Machine)**\n\n1. Set a bench under the Smith machine bar, align it so the bar lowers to your mid‑chest.\n2. Grip the bar slightly wider than shoulder‑width, unrack it.\n3. Lower the bar to your chest, keeping elbows at 45°.\n4. Press back up, squeezing your chest.\n5. The fixed path provides stability and helps learn the movement pattern.',
  ),
  ExercisePoolEntry(
    id: 'chest_smith_incline_press',
    name: 'Smith Incline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Upper Chest (Smith)**\n\n1. Place an incline bench under the Smith bar.\n2. Lie back, grip the bar, unrack and lower to your upper chest.\n3. Press up, focusing on the upper pectoral contraction.\n4. The guided bar helps maintain proper form.',
  ),
  ExercisePoolEntry(
    id: 'chest_smith_reverse_press',
    name: 'Smith Reverse Grip Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Upper Chest (Reverse Grip)**\n\n1. Grip the bar with palms facing you (reverse/underhand grip), hands shoulder‑width.\n2. Lie on a flat bench, lower the bar to your upper chest.\n3. Press up, squeezing the upper chest.\n4. This grip increases upper pectoral activation.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_band_chest_press',
    name: 'Band Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Anchor a band behind you at chest height (e.g., a door frame or post).\n2. Step forward, grab the handles, and position your hands at chest level.\n3. Press the handles forward until your arms are fully extended, squeezing your chest.\n4. Return slowly, controlling the resistance.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_bb_decline_bench_press',
    name: 'Decline Barbell Bench Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
      'Push',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Chest, Triceps**\n\n1. Set a decline bench and secure your feet under the pads.\n2. Lie back and grip the bar slightly wider than shoulder‑width.\n3. Unrack the bar and lower it to your lower chest, keeping your elbows at a comfortable angle.\n4. Press the bar back up to full extension, squeezing your lower pectorals.\n5. Control the descent and avoid bouncing the bar off your chest.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_cable_chest_press',
    name: 'Cable Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Set the pulleys at chest height, grab a handle in each hand, and stand in the centre.\n2. Press the handles forward until your arms are fully extended, squeezing your chest.\n3. Return slowly to the starting position, controlling the weight throughout.\n4. Keep your core engaged and maintain a slight forward lean.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_db_floor_press',
    name: 'Dumbbell Floor Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Chest & Triceps',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Lie on the floor with a dumbbell in each hand, resting on your chest.\n2. Press the dumbbells upward until your arms are extended.\n3. Lower them with control until your upper arms touch the floor.\n4. Press back up, focusing on chest and triceps engagement.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_dip_dips',
    name: 'Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps, Shoulders**\n\n1. Grip the parallel bars, lift yourself up with straight arms.\n2. Lean your torso slightly forward to emphasise the chest, or keep upright for triceps focus.\n3. Lower your body until your shoulders are below your elbows (or until a comfortable stretch).\n4. Push back up to the starting position, locking out at the top.\n5. Keep your legs bent behind you to maintain balance.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_dip_weighted_dips',
    name: 'Weighted Dips',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.dipStationOrParallelBars,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
      'Push',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps, Shoulders**\n\n1. Attach a dip belt with a weight plate, or hold a dumbbell between your legs.\n2. Perform dips with a forward lean (for chest) or upright (for triceps).\n3. Lower until you feel a deep stretch, then press up powerfully.\n4. Use a spotter or safety pins if going to failure.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_selector_dip_machine',
    name: 'Assisted Dip Machine',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
      'Push',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps, Shoulders**\n\n1. Kneel on the assisted dip machine platform and grip the handles.\n2. Lower your body by bending your elbows, allowing the machine to assist you.\n3. Press back up to the starting position.\n4. Adjust the assistance weight as needed to progress.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_selector_incline_chest_press',
    name: 'Selectorized Incline Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Chest & Triceps',
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Chest, Shoulders**\n\n1. Sit at the incline chest press machine and adjust the seat so the handles are at upper chest level.\n2. Press the handles forward and upward, focusing on the upper pectoral contraction.\n3. Return slowly with control.\n4. Keep your back flat against the pad.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_selector_machine_chest_press',
    name: 'Machine Chest Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Chest & Triceps',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Shoulders, Triceps**\n\n1. Sit on the chest press machine and adjust the seat so the handles are at chest height.\n2. Grip the handles and press forward until your arms are fully extended.\n3. Squeeze your chest at the end of the movement, then return slowly to the starting position.\n4. Keep your back flat against the pad throughout the set.',
  ),
  ExercisePoolEntry(
    id: 'push_kb_kettlebell_floor_press',
    name: 'Kettlebell Floor Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Chest, Triceps**\n\n1. Lie on the floor with a kettlebell in each hand, resting on your chest.\n2. Press the kettlebells upward until your arms are extended.\n3. Lower them with control until your upper arms touch the floor.\n4. Press back up, focusing on chest and triceps engagement.',
  ),
  ExercisePoolEntry(
    id: 'push_smith_decline_press',
    name: 'Smith Machine Decline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Chest, Triceps**\n\n1. Set a decline bench under the Smith bar, secure your feet.\n2. Lower the bar to your lower chest, keeping elbows tucked.\n3. Press back up, squeezing your lower pecs.\n4. The fixed path reduces shoulder stress.',
  ),
  ExercisePoolEntry(
    id: 'push_smith_incline_press',
    name: 'Smith Machine Incline Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.chest,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Chest, Shoulders**\n\n1. Set an incline bench (30–45°) under the Smith bar.\n2. Lie back and grip the bar, lower it to your upper chest.\n3. Press the bar up, focusing on the upper pectoral contraction.\n4. Return with control along the fixed bar path.',
  ),
];
