// lib/engines/workout_engine/shared/exercises/catalog/definitions/core_exercises.dart
// ⚠️ AUTO-GENERATED – DO NOT EDIT MANUALLY

import 'package:gymgenius/domain/enums/exports.dart';
import 'package:gymgenius/engines/workout_engine/shared/exercise_pool_entry.dart';

/// Canonical definitions for core exercises.
const List<ExercisePoolEntry> coreDefinitions = [
  ExercisePoolEntry(
    id: 'core_abwheel_knee_rollouts',
    name: 'Ab Wheel Knee Rollouts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.abWheel,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Core**\n\n1. Start on your knees with the wheel in front.\n2. Roll out only until your shoulders are extended, keeping back flat.\n3. Pull back to the start.',
  ),
  ExercisePoolEntry(
    id: 'core_abwheel_negative_rollouts',
    name: 'Ab Wheel Negative Rollouts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.abWheel,
    targetMuscles: [
      MuscleGroup.absCore,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Core, Shoulders**\n\n1. Roll out as far as possible.\n2. Pause at the bottom for 2-3 seconds.\n3. Pull back with control.',
  ),
  ExercisePoolEntry(
    id: 'core_abwheel_oblique_rollouts',
    name: 'Ab Wheel Oblique Rollouts',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.abWheel,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.rotation,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Obliques**\n\n1. Kneel on the floor, wheel in front.\n2. Roll out diagonally to one side.\n3. Pull back and repeat on the other side.',
  ),
  ExercisePoolEntry(
    id: 'core_abwheel_rollouts',
    name: 'Ab Wheel Rollouts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.abWheel,
    targetMuscles: [
      MuscleGroup.absCore,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Core, Shoulders**\n\n1. Kneel on the floor, gripping the ab wheel handles.\n2. Roll forward slowly, keeping your core braced and back flat.\n3. Roll back to the starting position.',
  ),
  ExercisePoolEntry(
    id: 'core_abwheel_standing_rollouts',
    name: 'Ab Wheel Standing Rollouts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.abWheel,
    targetMuscles: [
      MuscleGroup.absCore,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Core, Shoulders**\n\n1. Stand with feet hip-width apart, holding the wheel.\n2. Roll down towards the floor, keeping back straight.\n3. Roll back up using your core.',
  ),
  ExercisePoolEntry(
    id: 'core_band_crunches',
    name: 'Banded Crunches',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Abs**\n\n1. Anchor a band above you.\n2. Kneel and hold the band behind your neck.\n3. Crunch forward against resistance.\n4. Return with control.',
  ),
  ExercisePoolEntry(
    id: 'core_band_leg_raises',
    name: 'Banded Leg Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Abs**\n\n1. Lie on your back, loop a band around your feet.\n2. Hold the ends of the band for resistance.\n3. Raise your legs straight up.\n4. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'core_band_pallof_press',
    name: 'Band Pallof Press',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Core (anti-rotation)**\n\n1. Anchor a band at chest height.\n2. Stand sideways, hold the band with both hands.\n3. Press straight out, resisting rotation.\n4. Return and switch sides.',
  ),
  ExercisePoolEntry(
    id: 'core_band_russian_twists',
    name: 'Banded Russian Twists',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.rotation,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Obliques**\n\n1. Sit on the floor, knees bent, feet lifted.\n2. Anchor a band at waist height.\n3. Hold the band and rotate side to side.\n4. Control the movement.',
  ),
  ExercisePoolEntry(
    id: 'core_band_woodchop',
    name: 'Band Woodchop',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.rotation,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Core, Shoulders**\n\n1. Anchor a band at low or high position.\n2. Chop diagonally across your body.\n3. Alternate sides.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_bicycle_crunches',
    name: 'Bicycle Crunches',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.rotation,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Abs, Obliques**\n\n1. Lie on your back, hands behind your head.\n2. Bring one elbow towards the opposite knee while extending the other leg.\n3. Alternate sides in a pedaling motion.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_bird_dog',
    name: 'Bird Dog',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.back,
      MuscleGroup.glutes,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.isometric,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Core, Lower Back**\n\n1. Start on all fours.\n2. Extend opposite arm and leg simultaneously.\n3. Hold and switch sides.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_crunches',
    name: 'Crunches',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Abs**\n\n1. Lie on your back, knees bent, feet flat.\n2. Curl your upper body towards your knees.\n3. Lower back down with control.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_dead_bug',
    name: 'Dead Bug',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Deep Core**\n\n1. Lie on your back, arms extended towards ceiling, legs at 90°.\n2. Slowly extend opposite arm and leg.\n3. Return to start and alternate.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_flutter_kicks',
    name: 'Flutter Kicks',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Abs, Hip Flexors**\n\n1. Lie on your back, hands under glutes.\n2. Flutter your legs up and down.\n3. Keep core engaged and back flat.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_heel_touches',
    name: 'Heel Touches',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.rotation,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Obliques**\n\n1. Lie on your back, knees bent, feet flat.\n2. Reach your right hand towards your right heel.\n3. Alternate sides in a controlled manner.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_hollow_body_hold',
    name: 'Hollow Body Hold',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Core**\n\n1. Lie on your back, arms and legs extended.\n2. Lift arms, shoulders, and legs off the floor.\n3. Hold with lower back pressed into the ground.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_leg_raises',
    name: 'Leg Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Abs**\n\n1. Lie on your back, legs straight.\n2. Raise your legs to 90° without bending knees.\n3. Lower them slowly without touching the floor.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_mountain_climbers',
    name: 'Mountain Climbers',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Core, Shoulders**\n\n1. Plank position.\n2. Drive one knee towards chest.\n3. Alternate quickly.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_plank',
    name: 'Plank',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Core**\n\n1. Forearm plank position.\n2. Hold body straight from head to heels.\n3. Engage core and hold for time.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_plank_jacks',
    name: 'Plank Jacks',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.adductors,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Core, Adductors**\n\n1. Plank position.\n2. Jump your feet apart and together.\n3. Keep hips stable.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_reverse_crunches',
    name: 'Reverse Crunches',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Abs**\n\n1. Lie on your back, hands at sides.\n2. Lift your legs and curl your hips off the floor.\n3. Lower back down slowly.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_russian_twists',
    name: 'Russian Twists',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.rotation,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Obliques**\n\n1. Sit with knees bent, torso leaning back slightly, feet off the floor.\n2. Rotate your torso side to side, tapping the floor beside your hips.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_scissor_kicks',
    name: 'Scissor Kicks',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Abs**\n\n1. Lie on your back, legs extended.\n2. Cross one leg over the other in a scissor motion.\n3. Alternate quickly without arching your back.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_side_plank',
    name: 'Side Plank',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Obliques**\n\n1. Side support on forearm.\n2. Hold body straight.\n3. Repeat on other side.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_spiderman_plank',
    name: 'Spiderman Plank',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Core, Hip Flexors**\n\n1. Plank position.\n2. Bring one knee towards the same-side elbow.\n3. Alternate sides.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_toe_touches',
    name: 'Toe Touches',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Upper Abs**\n\n1. Lie on your back, legs straight up towards ceiling.\n2. Reach your hands towards your toes.\n3. Lower back down with control.',
  ),
  ExercisePoolEntry(
    id: 'core_bw_v_ups',
    name: 'V‑Ups',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Full Core**\n\n1. Lie on your back, arms and legs extended.\n2. Lift arms and legs simultaneously to form a V shape.\n3. Lower back down with control.',
  ),
  ExercisePoolEntry(
    id: 'core_cable_crunches',
    name: 'Cable Crunches',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Abs**\n\n1. Kneel below a high pulley, rope behind your head.\n2. Crunch down, bringing elbows towards knees.\n3. Return with control.',
  ),
  ExercisePoolEntry(
    id: 'core_cable_oblique_twist',
    name: 'Cable Oblique Twist',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.rotation,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Obliques**\n\n1. Set cable at waist height with a D-handle.\n2. Stand perpendicular, rotate torso away.\n3. Return and switch sides.',
  ),
  ExercisePoolEntry(
    id: 'core_cable_pallof_press',
    name: 'Cable Pallof Press',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Core (anti-rotation)**\n\n1. Set cable at chest height.\n2. Stand sideways, hold handle with both hands.\n3. Press straight out, resisting rotation.\n4. Return and switch sides.',
  ),
  ExercisePoolEntry(
    id: 'core_cable_side_bend',
    name: 'Cable Side Bend',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Obliques**\n\n1. Set cable at low position with a D-handle.\n2. Stand sideways, hold handle with one hand.\n3. Bend torso sideways, then return.',
  ),
  ExercisePoolEntry(
    id: 'core_cable_woodchops',
    name: 'Cable Woodchops',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.rotation,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Core, Shoulders**\n\n1. Set cable at high or low position.\n2. Chop diagonally across body.',
  ),
  ExercisePoolEntry(
    id: 'core_db_dumbbell_crunches',
    name: 'Dumbbell Crunches',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Abs**\n\n1. Hold a dumbbell on your chest.\n2. Crunch up and squeeze abs.\n3. Lower back down with control.',
  ),
  ExercisePoolEntry(
    id: 'core_db_dumbbell_oblique_crunch',
    name: 'Dumbbell Oblique Crunch',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.rotation,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Obliques**\n\n1. Lie on your side, hold a dumbbell near your chest.\n2. Crunch up, bringing shoulder towards hip.\n3. Lower and repeat on other side.',
  ),
  ExercisePoolEntry(
    id: 'core_db_dumbbell_side_bends',
    name: 'Dumbbell Side Bends',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Obliques**\n\n1. Hold a dumbbell in one hand.\n2. Bend sideways at the waist.\n3. Return to upright and repeat on other side.',
  ),
  ExercisePoolEntry(
    id: 'core_db_dumbbell_v_ups',
    name: 'Dumbbell V-Ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Full Core**\n\n1. Lie on your back holding a dumbbell overhead.\n2. Simultaneously raise legs and torso.\n3. Bring dumbbell towards feet, then lower.',
  ),
  ExercisePoolEntry(
    id: 'core_db_russian_twists_dumbbell',
    name: 'Russian Twists with Dumbbell',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.rotation,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Obliques**\n\n1. Sit with knees bent, torso leaning back, holding a dumbbell.\n2. Rotate side to side, tapping the floor.\n3. Keep core tight throughout.',
  ),
  ExercisePoolEntry(
    id: 'core_pullup_hanging_knee_raises',
    name: 'Hanging Knee Raises',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Abs**\n\n1. Hang from a bar.\n2. Raise knees towards your chest.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'core_pullup_hanging_leg_raises',
    name: 'Hanging Leg Raises',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Abs**\n\n1. Hang from a pull-up bar with arms fully extended.\n2. Raise your legs straight up towards your chest.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'core_pullup_l_sit',
    name: 'L-Sit Hang',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.absCore,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Core, Shoulders**\n\n1. Hang from a bar.\n2. Raise legs to a 90° angle, forming an L-shape.\n3. Hold the position.',
  ),
  ExercisePoolEntry(
    id: 'core_pullup_toes_to_bar',
    name: 'Toes-to-Bar',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.absCore,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Core, Shoulders**\n\n1. Hang from a bar.\n2. Raise straight legs up to touch the bar with your toes.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'core_pullup_windshield_wipers',
    name: 'Windshield Wipers',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.pullUpBarAccessible,
    targetMuscles: [
      MuscleGroup.absCore,
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.rotation,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Obliques, Core**\n\n1. Hang from a bar with legs extended.\n2. Rotate your legs side to side like windshield wipers.\n3. Keep your upper body stable.',
  ),
  ExercisePoolEntry(
    id: 'core_selector_ab_crunch',
    name: 'Selectorized Ab Crunch',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Abs**\n\n1. Sit on the machine, feet under the pads.\n2. Crunch down, bringing elbows towards knees.\n3. Return with control.',
  ),
  ExercisePoolEntry(
    id: 'core_selector_ab_extension',
    name: 'Selectorized Ab Extension (Reverse Crunch)',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Abs**\n\n1. Lie back on the machine, holding handles above.\n2. Curl hips off the pad, bringing knees to chest.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'core_selector_leg_lift',
    name: 'Selectorized Leg Lift',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Lower Abs**\n\n1. Sit on a leg lift machine, arms on pads.\n2. Lift knees towards chest.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'core_selector_oblique_crunch',
    name: 'Selectorized Oblique Crunch',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.rotation,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Obliques**\n\n1. Sit sideways on the machine, one hip against the pad.\n2. Crunch torso towards your hip.\n3. Return and switch sides.',
  ),
  ExercisePoolEntry(
    id: 'core_selector_torso_rotation',
    name: 'Selectorized Torso Rotation',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Core',
      'Legs',
      'Lower Body',
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.rotation,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Obliques**\n\n1. Sit on the machine, grip handles.\n2. Rotate side to side against resistance.\n3. Control the movement.',
  ),
];
