// lib/engines/workout_engine/shared/exercises/catalog/definitions/legs_exercises.dart
// ⚠️ AUTO-GENERATED – DO NOT EDIT MANUALLY

import 'package:gymgenius/domain/enums/exports.dart';
import 'package:gymgenius/engines/workout_engine/shared/exercise_pool_entry.dart';

/// Canonical definitions for legs exercises.
const List<ExercisePoolEntry> legsDefinitions = [
  ExercisePoolEntry(
    id: 'legs_band_calf_raises',
    name: 'Resistance Band Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves**\n\n1. Stand on the middle of a resistance band and hold the ends at shoulder height.\n2. Raise your heels as high as possible against the band tension.\n3. Lower slowly and repeat.',
  ),
  ExercisePoolEntry(
    id: 'legs_band_clamshells',
    name: 'Band Clamshells',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Glutes**\n\n1. Lie on your side with a band above your knees.\n2. Open your knees like a clam shell.',
  ),
  ExercisePoolEntry(
    id: 'legs_band_glute_bridges',
    name: 'Band Glute Bridges',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.hamstrings,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes**\n\n1. Place a band above your knees.\n2. Perform glute bridges, pushing knees apart against the band.',
  ),
  ExercisePoolEntry(
    id: 'legs_band_lateral_walks',
    name: 'Band Lateral Walks',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.adductors,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Glutes, Adductors**\n\n1. Place a band above your knees.\n2. Step sideways, keeping tension on the band.',
  ),
  ExercisePoolEntry(
    id: 'legs_band_leg_curls',
    name: 'Band Leg Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings**\n\n1. Anchor a band, lie face down, loop band around ankles.\n2. Curl your heels towards your glutes.',
  ),
  ExercisePoolEntry(
    id: 'legs_band_single_leg_calf_raises',
    name: 'Single-Leg Band Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves (unilateral)**\n\n1. Stand on one foot on the resistance band.\n2. Hold the band securely and raise your heel against resistance.\n3. Lower slowly and repeat before switching sides.',
  ),
  ExercisePoolEntry(
    id: 'legs_band_squats',
    name: 'Resistance Band Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Stand on a band, hold the handles at shoulder height.\n2. Perform a squat, keeping tension on the band.',
  ),
  ExercisePoolEntry(
    id: 'legs_bb_deadlifts',
    name: 'Barbell Deadlifts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.hamstrings,
      MuscleGroup.glutes,
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
      MuscleGroup.back,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings, Glutes, Lower Back**\n\n1. Stand with feet hip-width apart, barbell over midfoot.\n2. Hinge down and grip the bar, keeping your back flat.\n3. Drive through your heels and stand up straight, bar close to your body.',
  ),
  ExercisePoolEntry(
    id: 'legs_bb_front_squats',
    name: 'Front Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Rest a barbell across the front of your shoulders, elbows high.\n2. Squat down keeping your torso upright.\n3. Drive through heels to stand up.',
  ),
  ExercisePoolEntry(
    id: 'legs_bb_hip_thrusts',
    name: 'Barbell Hip Thrusts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Hamstrings**\n\n1. Sit with your upper back against a bench, a barbell over your hips.\n2. Drive your hips up, squeezing your glutes at the top.\n3. Lower back down with control.',
  ),
  ExercisePoolEntry(
    id: 'legs_bb_romanian_deadlifts',
    name: 'Barbell Romanian Deadlifts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.hamstrings,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings, Glutes**\n\n1. Hold a barbell in front of your thighs, feet hip-width apart.\n2. Hinge at the hips, lowering the bar along your legs.\n3. Return to standing by driving your hips forward.',
  ),
  ExercisePoolEntry(
    id: 'legs_bb_squats',
    name: 'Barbell Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Place a barbell on your upper back, feet shoulder-width apart.\n2. Squat down to parallel or below.\n3. Drive through heels to stand up.',
  ),
  ExercisePoolEntry(
    id: 'legs_bb_sumo_deadlifts',
    name: 'Sumo Deadlifts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
      MuscleGroup.adductors,
      MuscleGroup.back,
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Glutes, Inner Thighs, Hamstrings**\n\n1. Stand with feet wide, toes pointed out, gripping the bar inside your knees.\n2. Drive through your heels, keeping your chest up as you stand.\n3. Lower back down with control.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_calf_raises',
    name: 'Bodyweight Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves**\n\n1. Stand upright with your feet about hip-width apart.\n2. Raise your heels as high as possible.\n3. Pause briefly at the top and lower slowly with control.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_glute_bridges',
    name: 'Glute Bridges',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.hamstrings,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes**\n\n1. Lie on back, knees bent.\n2. Lift hips off floor.\n3. Squeeze glutes at top.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_jump_squats',
    name: 'Jump Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.calves,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Squat down.\n2. Explosively jump up.\n3. Land softly and repeat.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_lunges',
    name: 'Lunges',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Step forward with one leg, lowering your hips until both knees are bent at 90°.\n2. Push back to start and repeat on the other leg.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_pistol_squats_assisted',
    name: 'Pistol Squats (assisted)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.calves,
    ],
    compatibleSplits: {
      'Legs',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes (unilateral)**\n\n1. Stand on one leg, extend the other forward.\n2. Squat down on the standing leg.\n3. Push back up.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_side_lunges',
    name: 'Side Lunges',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.adductors,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Inner Thighs, Glutes**\n\n1. Step to the side, bending the lead knee.\n2. Push back to center.\n3. Alternate sides.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_single_leg_calf_raises',
    name: 'Single-Leg Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves (unilateral)**\n\n1. Stand on one foot while keeping the other foot off the ground.\n2. Raise your heel as high as possible.\n3. Lower slowly and repeat before switching sides.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_single_leg_glute_bridges',
    name: 'Single-Leg Glute Bridges',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.hamstrings,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes (unilateral)**\n\n1. Lie on back, one foot on floor, other leg extended.\n2. Lift hips off floor using the grounded leg.\n3. Squeeze glute, lower with control.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_squats',
    name: 'Bodyweight Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Stand with feet shoulder-width apart.\n2. Lower your hips back and down as if sitting in a chair.\n3. Go as low as you can while keeping chest up.\n4. Push through heels to return to standing.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_sumo_squats',
    name: 'Sumo Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.adductors,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Inner Thighs, Glutes, Quadriceps**\n\n1. Stand with feet wider than shoulder-width, toes pointed out.\n2. Lower your hips straight down, keeping knees tracking over toes.\n3. Push through heels to stand back up.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_walking_lunges',
    name: 'Walking Lunges',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Step forward into a lunge, lowering your back knee towards the floor.\n2. Push off your back foot and step directly into the next lunge.\n3. Continue alternating legs as you move forward.',
  ),
  ExercisePoolEntry(
    id: 'legs_cable_glute_kickbacks',
    name: 'Cable Glute Kickbacks',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes**\n\n1. Attach an ankle strap to a low pulley and secure it around your ankle.\n2. Kick your leg back and up, squeezing your glute.\n3. Return with control, then switch sides.',
  ),
  ExercisePoolEntry(
    id: 'legs_cable_hip_abduction',
    name: 'Cable Hip Abduction',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Glutes, TFL**\n\n1. Attach ankle strap to a low pulley.\n2. Stand sideways and pull your leg away from your body.\n3. Return with control.',
  ),
  ExercisePoolEntry(
    id: 'legs_cable_hip_adduction',
    name: 'Cable Hip Adduction',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.adductors,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Adductors**\n\n1. Attach ankle strap to a low pulley.\n2. Stand sideways and pull your leg across your body.\n3. Return with control.',
  ),
  ExercisePoolEntry(
    id: 'legs_cable_pull_through',
    name: 'Cable Pull-Through',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Hamstrings**\n\n1. Attach a rope to a low pulley, stand facing away.\n2. Hinge at the hips and pull the rope through your legs.\n3. Drive hips forward to stand up.',
  ),
  ExercisePoolEntry(
    id: 'legs_cable_squat_pulldown',
    name: 'Cable Squat Pulldown',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Set a cable at chest height, hold the handle.\n2. Squat down while pulling the cable towards you.\n3. Stand up and return the cable.',
  ),
  ExercisePoolEntry(
    id: 'legs_chair_bulgarian_split_squats',
    name: 'Bulgarian Split Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Stand a couple of feet in front of a bench, resting one foot behind you on it.\n2. Lower your back knee towards the floor by bending your front leg.\n3. Push through your front heel to return to standing.',
  ),
  ExercisePoolEntry(
    id: 'legs_chair_deep_squat_holds',
    name: 'Deep Squat Holds (with bench)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Stand in front of a chair and squat down until you lightly touch the seat.\n2. Hold for 2 seconds, then stand back up.\n3. Focus on control and depth.',
  ),
  ExercisePoolEntry(
    id: 'legs_chair_hip_thrusts',
    name: 'Hip Thrusts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Hamstrings**\n\n1. Sit with your upper back against a bench, knees bent, feet flat.\n2. Drive your hips up towards the ceiling, squeezing your glutes.\n3. Lower back down with control.',
  ),
  ExercisePoolEntry(
    id: 'legs_chair_single_leg_step_ups',
    name: 'Single-Leg Step-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Legs',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Stand on one leg on the bench, the other foot hovering.\n2. Lower yourself by bending the standing leg until the heel of the hovering foot touches the floor.\n3. Drive back up to standing on the bench.',
  ),
  ExercisePoolEntry(
    id: 'legs_chair_step_ups',
    name: 'Step-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Stand in front of a sturdy elevated platform (chair/bench).\n2. Step up with one foot, driving through the heel to stand on top.\n3. Step back down with control and repeat.',
  ),
  ExercisePoolEntry(
    id: 'legs_curl_iso_hold',
    name: 'Leg Curl Isometric Hold',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.legCurlMachine,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings**\n\n1. Curl and hold the top position for 3-5 seconds.\n2. Lower slowly.',
  ),
  ExercisePoolEntry(
    id: 'legs_curl_seated',
    name: 'Seated Leg Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.legCurlMachine,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings**\n\n1. Sit on the machine, pads on front of ankles.\n2. Curl the weight towards your glutes.',
  ),
  ExercisePoolEntry(
    id: 'legs_curl_single_leg',
    name: 'Single-Leg Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.legCurlMachine,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings (unilateral)**\n\n1. Use one leg at a time.',
  ),
  ExercisePoolEntry(
    id: 'legs_curl_standard',
    name: 'Leg Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.legCurlMachine,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings**\n\n1. Lie face down on the leg curl machine, ankles under the pads.\n2. Curl your heels towards your glutes.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'legs_db_bulgarian_split_squats',
    name: 'Dumbbell Bulgarian Split Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Hold a dumbbell in each hand, one foot resting on a bench behind you.\n2. Lower into a lunge until your back knee nearly touches the floor.\n3. Push back up through your front heel.',
  ),
  ExercisePoolEntry(
    id: 'legs_db_calf_raises',
    name: 'Dumbbell Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves**\n\n1. Hold a dumbbell in each hand, stand on the edge of a step.\n2. Raise your heels as high as possible.\n3. Lower slowly below the step for a full stretch.',
  ),
  ExercisePoolEntry(
    id: 'legs_db_goblet_squats',
    name: 'Goblet Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Hold a dumbbell vertically against your chest, hands under the top plate.\n2. Perform a squat, keeping the weight close.',
  ),
  ExercisePoolEntry(
    id: 'legs_db_lunges',
    name: 'Dumbbell Lunges',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Hold dumbbells at your sides.\n2. Perform a lunge as described above.',
  ),
  ExercisePoolEntry(
    id: 'legs_db_romanian_deadlifts',
    name: 'Romanian Deadlifts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.hamstrings,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings, Glutes**\n\n1. Stand with feet hip-width apart, dumbbells in front of thighs.\n2. Hinge at hips, push butt back, lower dumbbells along your shins.\n3. Feel the stretch in hamstrings, then return to start.',
  ),
  ExercisePoolEntry(
    id: 'legs_db_step_ups',
    name: 'Dumbbell Step-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Hold a dumbbell in each hand.\n2. Step up onto a platform, driving through your front heel.\n3. Step back down with control and repeat.',
  ),
  ExercisePoolEntry(
    id: 'legs_ext_drop_set',
    name: 'Leg Extension Drop Set',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.legExtensionMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps**\n\n1. Perform a set to failure, reduce weight, continue.\n2. Repeat for 2-3 drops.',
  ),
  ExercisePoolEntry(
    id: 'legs_ext_iso_hold',
    name: 'Leg Extension Isometric Hold',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.legExtensionMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps**\n\n1. Extend legs and hold the top position for 3-5 seconds.\n2. Lower slowly.',
  ),
  ExercisePoolEntry(
    id: 'legs_ext_partial_reps',
    name: 'Leg Extension Partial Reps',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.legExtensionMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps**\n\n1. Extend only the top half of the movement.\n2. Focus on constant tension.',
  ),
  ExercisePoolEntry(
    id: 'legs_ext_single_leg',
    name: 'Single-Leg Extensions',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.legExtensionMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps (unilateral)**\n\n1. Use one leg at a time to isolate each quad.',
  ),
  ExercisePoolEntry(
    id: 'legs_ext_standard',
    name: 'Leg Extensions',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.legExtensionMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps**\n\n1. Sit on the leg extension machine, shins behind the pad.\n2. Extend your legs until straight.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'legs_hack_narrow_stance',
    name: 'Hack Squat - Narrow Stance',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.hackSquatMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
      MuscleGroup.glutes,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps**\n\n1. Place feet narrow on the platform.\n2. Perform the hack squat.',
  ),
  ExercisePoolEntry(
    id: 'legs_hack_reverse',
    name: 'Reverse Hack Squat',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.hackSquatMachine,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Hamstrings**\n\n1. Face the machine and place shoulders against the pads.\n2. Perform a squat with a hip-dominant emphasis.',
  ),
  ExercisePoolEntry(
    id: 'legs_hack_single_leg',
    name: 'Single-Leg Hack Squat',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.hackSquatMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes (unilateral)**\n\n1. Use one leg on the platform, the other resting.\n2. Perform the movement unilaterally.',
  ),
  ExercisePoolEntry(
    id: 'legs_hack_standard',
    name: 'Hack Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.hackSquatMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Position yourself in the hack squat machine, shoulders under the pads.\n2. Lower down until your knees reach about 90 degrees.\n3. Push through your heels to return to start.',
  ),
  ExercisePoolEntry(
    id: 'legs_hack_wide_stance',
    name: 'Hack Squat - Wide Stance',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.hackSquatMachine,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.adductors,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Adductors**\n\n1. Place feet wide on the platform.\n2. Perform the hack squat.',
  ),
  ExercisePoolEntry(
    id: 'legs_kb_deadlifts',
    name: 'Kettlebell Deadlifts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.hamstrings,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings, Glutes**\n\n1. Stand over a kettlebell, feet hip-width apart.\n2. Hinge at the hips and grip the handle, keeping your back flat.\n3. Drive through your heels to stand up.',
  ),
  ExercisePoolEntry(
    id: 'legs_kb_goblet_squats',
    name: 'Kettlebell Goblet Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Hold a kettlebell by the horns against your chest.\n2. Squat down keeping your chest up and the kettlebell close.\n3. Drive through your heels to stand back up.',
  ),
  ExercisePoolEntry(
    id: 'legs_kb_lunges',
    name: 'Kettlebell Lunges',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Hold a kettlebell by the horns or in the rack position.\n2. Perform a forward lunge, keeping the weight stable.\n3. Push back to start and alternate.',
  ),
  ExercisePoolEntry(
    id: 'legs_kb_single_arm_deadlifts',
    name: 'Single-Arm Kettlebell Deadlifts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.hamstrings,
      MuscleGroup.glutes,
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings, Glutes, Core**\n\n1. Stand over a kettlebell with feet shoulder-width apart.\n2. Hinge and grab the handle with one hand.\n3. Drive up, keeping your back flat and core engaged.',
  ),
  ExercisePoolEntry(
    id: 'legs_kb_swings',
    name: 'Kettlebell Swings',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Hamstrings, Core**\n\n1. Stand with feet shoulder-width apart, kettlebell on the floor in front of you.\n2. Hinge at the hips and swing the kettlebell back between your legs.\n3. Drive your hips forward explosively to swing it up to chest height.',
  ),
  ExercisePoolEntry(
    id: 'legs_lp_high_foot',
    name: 'Leg Press - High Foot Placement',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.legPressMachine,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Hamstrings**\n\n1. Place feet high on the platform.\n2. Lower and press, emphasising hip extension.',
  ),
  ExercisePoolEntry(
    id: 'legs_lp_low_foot',
    name: 'Leg Press - Low Foot Placement',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.legPressMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
      MuscleGroup.glutes,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps**\n\n1. Place feet low on the platform.\n2. Lower and press, focusing on knee extension.',
  ),
  ExercisePoolEntry(
    id: 'legs_lp_narrow_stance',
    name: 'Leg Press - Narrow Stance',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.legPressMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
      MuscleGroup.glutes,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps (outer)**\n\n1. Place feet close together on the platform.\n2. Perform the leg press.',
  ),
  ExercisePoolEntry(
    id: 'legs_lp_single_leg',
    name: 'Single-Leg Leg Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.legPressMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes (unilateral)**\n\n1. Place one foot on the platform, the other resting.\n2. Lower and press with the working leg.\n3. Switch legs.',
  ),
  ExercisePoolEntry(
    id: 'legs_lp_standard',
    name: 'Leg Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.legPressMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Sit on the leg press machine, feet on the platform shoulder-width apart.\n2. Lower the platform until your knees are at 90°.\n3. Press back up without locking your knees.',
  ),
  ExercisePoolEntry(
    id: 'legs_selector_hip_abduction',
    name: 'Hip Abduction Machine',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Glutes, TFL**\n\n1. Sit on the machine with thighs against the pads.\n2. Press outwards against the pads.',
  ),
  ExercisePoolEntry(
    id: 'legs_selector_hip_adduction',
    name: 'Hip Adduction Machine',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.adductors,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Adductors**\n\n1. Sit on the machine with thighs inside the pads.\n2. Squeeze your thighs together.',
  ),
  ExercisePoolEntry(
    id: 'legs_selector_leg_curl_seated',
    name: 'Seated Leg Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings**\n\n1. Sit with pads on front of ankles.\n2. Curl the weight towards you.',
  ),
  ExercisePoolEntry(
    id: 'legs_selector_seated_calf_raises',
    name: 'Seated Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves (soleus)**\n\n1. Sit at the calf raise machine, pads resting on your knees.\n2. Raise your heels as high as possible.\n3. Lower slowly for a full stretch.',
  ),
  ExercisePoolEntry(
    id: 'legs_selector_standing_calf_raises',
    name: 'Standing Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves (gastrocnemius)**\n\n1. Stand on the machine with shoulders under pads.\n2. Raise your heels as high as possible.\n3. Lower slowly.',
  ),
  ExercisePoolEntry(
    id: 'legs_smith_calf_raises',
    name: 'Smith Machine Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves**\n\n1. Place the bar on your shoulders, stand on a step.\n2. Raise your heels as high as possible.\n3. Lower slowly for a full stretch.',
  ),
  ExercisePoolEntry(
    id: 'legs_smith_front_squats',
    name: 'Smith Machine Front Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Place the bar across your front shoulders.\n2. Squat down keeping your torso upright.\n3. Push up through your heels.',
  ),
  ExercisePoolEntry(
    id: 'legs_smith_hip_thrusts',
    name: 'Smith Machine Hip Thrusts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Hamstrings**\n\n1. Sit with your back against a bench, bar over your hips.\n2. Drive your hips up, squeezing your glutes.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'legs_smith_lunges',
    name: 'Smith Machine Lunges',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Place the bar on your upper back.\n2. Lunge forward with one leg, lowering your back knee.\n3. Push back to start and alternate.',
  ),
  ExercisePoolEntry(
    id: 'legs_smith_squats',
    name: 'Smith Machine Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Position the bar across your upper back under the Smith machine.\n2. Squat down along the fixed vertical path.\n3. Drive through your heels to stand back up.',
  ),
  ExercisePoolEntry(
    id: 'legs_stairs_box_jumps',
    name: 'Box Jumps',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.stairsOrStep,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Calves**\n\n1. Stand in front of a sturdy box/step.\n2. Squat down and jump onto the box.\n3. Land softly and step back down.',
  ),
  ExercisePoolEntry(
    id: 'legs_stairs_calf_raises',
    name: 'Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.stairsOrStep,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves**\n\n1. Stand on the edge of a step.\n2. Raise your heels as high as possible.\n3. Lower slowly below the step for a full stretch.',
  ),
  ExercisePoolEntry(
    id: 'legs_stairs_lateral_step_ups',
    name: 'Lateral Step-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.stairsOrStep,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.adductors,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Quadriceps, Glutes, Adductors**\n\n1. Stand sideways to a step.\n2. Step up sideways with the lead foot, then bring the other foot up.\n3. Step down sideways and repeat.',
  ),
  ExercisePoolEntry(
    id: 'lower_band_squats',
    name: 'Band Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Lower Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Stand on band, hold handles at shoulders.\n2. Squat down with band tension.\n3. Stand up.',
  ),
  ExercisePoolEntry(
    id: 'lower_chair_single_leg_hip_thrust',
    name: 'Single-Leg Hip Thrust',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.hamstrings,
    ],
    compatibleSplits: {
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes (unilateral)**\n\n1. Upper back against bench, one foot on floor, other leg extended.\n2. Drive hips up with the grounded leg.\n3. Squeeze glute, lower with control.',
  ),
  ExercisePoolEntry(
    id: 'lower_curl_band_curl',
    name: 'Band Leg Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Lower Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings**\n\n1. Anchor band at floor level.\n2. Lie face down, loop band around ankles.\n3. Curl heels towards glutes.',
  ),
  ExercisePoolEntry(
    id: 'lower_curl_single_leg_curl',
    name: 'Single-Leg Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.legCurlMachine,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings (unilateral)**\n\n1. Use one leg at a time.\n2. Curl fully, squeeze hamstring.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'lower_ext_single_leg_extension',
    name: 'Single-Leg Extension',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.legExtensionMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps (unilateral)**\n\n1. Use one leg at a time.\n2. Extend fully, squeeze quad.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'lower_kb_single_leg_deadlift',
    name: 'Kettlebell Single-Leg Deadlift',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.hamstrings,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings, Glutes (unilateral)**\n\n1. Balance on one leg, kettlebell in opposite hand.\n2. Hinge forward, lowering kettlebell.\n3. Return to standing using glute.\n4. Switch sides.',
  ),
  ExercisePoolEntry(
    id: 'lower_selector_hip_abduction',
    name: 'Selectorized Hip Abduction',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Lower Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Glutes**\n\n1. Sit on machine, thighs against pads.\n2. Press outward against pads.',
  ),
  ExercisePoolEntry(
    id: 'lower_selector_hip_adduction',
    name: 'Selectorized Hip Adduction',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.adductors,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Lower Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Adductors**\n\n1. Sit on machine, thighs inside pads.\n2. Squeeze thighs together.',
  ),
  ExercisePoolEntry(
    id: 'lower_selector_leg_curl',
    name: 'Selectorized Leg Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings**\n\n1. Lie face down, ankles under pads.\n2. Curl heels towards glutes.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'lower_selector_leg_extension',
    name: 'Selectorized Leg Extension',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps**\n\n1. Sit on machine, shins behind pad.\n2. Extend legs fully.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'lower_selector_seated_calf_raise',
    name: 'Selectorized Seated Calf Raise',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves**\n\n1. Sit at machine, pads on knees.\n2. Raise heels as high as possible.\n3. Lower slowly.',
  ),
  ExercisePoolEntry(
    id: 'lower_smith_deadlifts',
    name: 'Smith Machine Deadlifts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.hamstrings,
      MuscleGroup.glutes,
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings, Glutes, Back**\n\n1. Bar over midfoot, hinge down.\n2. Grip bar, keep back flat.\n3. Drive through heels to stand.',
  ),
];
