// lib/engines/workout_engine/shared/exercises/catalog/definitions/legs_exercises.dart
// ⚠️ AUTO-GENERATED – DO NOT EDIT MANUALLY

import 'package:gymgenius/domain/enums/exports.dart';
import 'package:gymgenius/engines/workout_engine/shared/exercise_pool_entry.dart';

/// Canonical definitions for legs exercises.
const List<ExercisePoolEntry> legsDefinitions = [
  ExercisePoolEntry(
    id: 'legs_band_calf_raises',
    name: 'Resistance Band Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Light',
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves**\n\n1. Stand on the middle of a resistance band, holding the ends at shoulder height for balance.\n2. Raise your heels as high as possible against the band tension.\n3. Squeeze your calves at the top, then lower slowly.\n4. Perform on a step for a greater range of motion.\n5. This adds extra resistance to bodyweight calf raises.',
  ),
  ExercisePoolEntry(
    id: 'legs_band_clamshells',
    name: 'Band Clamshells',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Glutes (Medius)**\n\n1. Lie on your side with knees bent at 90°, a band just above your knees.\n2. Keeping your feet together, open your knees like a clamshell, squeezing your glutes.\n3. Hold for a second at the top, then lower with control.\n4. Complete all reps on one side before switching.\n5. This targets the glute medius and is great for warm‑up.',
  ),
  ExercisePoolEntry(
    id: 'legs_band_glute_bridges',
    name: 'Band Glute Bridges',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.hamstrings,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes**\n\n1. Place a resistance band just above your knees, and lie on your back with knees bent, feet flat.\n2. Drive through your heels to lift your hips, squeezing your glutes at the top.\n3. Push your knees apart against the band to increase glute activation.\n4. Lower your hips back down with control.\n5. This variation adds extra resistance to the standard glute bridge.',
  ),
  ExercisePoolEntry(
    id: 'legs_band_lateral_walks',
    name: 'Band Lateral Walks',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.adductors,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Glutes, Adductors**\n\n1. Place a band just above your knees, stand with feet shoulder‑width apart.\n2. Take small steps sideways, keeping tension on the band and maintaining a slight squat position.\n3. Move 10–15 steps in one direction, then return.\n4. Keep your chest up and core tight.\n5. This is an excellent warm‑up or activation exercise.',
  ),
  ExercisePoolEntry(
    id: 'legs_band_leg_curls',
    name: 'Band Leg Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings**\n\n1. Anchor a resistance band at floor level behind you.\n2. Lie face down, loop the band around your ankles.\n3. Curl your heels towards your glutes, squeezing your hamstrings.\n4. Return slowly, resisting the band.\n5. This is a great home alternative to the leg curl machine.',
  ),
  ExercisePoolEntry(
    id: 'legs_band_single_leg_calf_raises',
    name: 'Single-Leg Band Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Light',
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves (Unilateral)**\n\n1. Stand on the band with one foot, hold the band in the same‑side hand for balance.\n2. Raise your heel as high as possible against the band tension.\n3. Squeeze at the top, lower with control.\n4. Complete all reps on one side before switching.\n5. This helps correct calf imbalances.',
  ),
  ExercisePoolEntry(
    id: 'legs_band_squats',
    name: 'Resistance Band Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Stand on a resistance band with feet shoulder‑width apart, holding the handles at shoulder height.\n2. Perform a squat, keeping your chest up and core tight, while maintaining tension on the band.\n3. Descend until your thighs are parallel to the floor.\n4. Drive through your heels to stand back up, keeping the band under tension.\n5. This adds resistance without heavy weights.',
  ),
  ExercisePoolEntry(
    id: 'legs_bb_front_squats',
    name: 'Front Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Rest the barbell across the front of your shoulders, crossing your arms to hold it in place (or using a clean grip with elbows high).\n2. Keep your elbows up and chest proud throughout the movement.\n3. Squat down by pushing your hips back and bending your knees, keeping your torso as upright as possible.\n4. Descend until your thighs are parallel to the floor or deeper.\n5. Drive through your heels to stand back up, keeping the bar stable and your core braced.',
  ),
  ExercisePoolEntry(
    id: 'legs_bb_hip_thrusts',
    name: 'Barbell Hip Thrusts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Hamstrings**\n\n1. Sit on the floor with your upper back resting against a bench, a barbell placed over your hips (use a pad for comfort).\n2. Place your feet flat on the floor, knees bent, about shoulder‑width apart.\n3. Drive through your heels to lift your hips toward the ceiling, squeezing your glutes at the top.\n4. Pause for a second at the top, then lower your hips back down with control.\n5. Keep your chin tucked and your core engaged to protect your spine.',
  ),
  ExercisePoolEntry(
    id: 'legs_bb_romanian_deadlifts',
    name: 'Barbell Romanian Deadlifts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.hamstrings,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings, Glutes**\n\n1. Stand with feet hip‑width apart, holding a barbell in front of your thighs with an overhand grip.\n2. Keeping your knees slightly bent, push your hips back and lower the barbell down your legs, keeping your back flat.\n3. Lower until you feel a deep stretch in your hamstrings (bar around mid‑shin), then drive your hips forward to stand back up.\n4. Keep the bar close to your body throughout the movement.\n5. Avoid rounding your back; the movement is predominantly a hip hinge.',
  ),
  ExercisePoolEntry(
    id: 'legs_bb_squats',
    name: 'Barbell Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Position a barbell across your upper back (low bar or high bar), feet shoulder‑width apart, toes slightly pointed out.\n2. Unrack the bar, brace your core, and initiate the squat by pushing your hips back and bending your knees.\n3. Lower your body until your thighs are at least parallel to the floor, keeping your chest up and back straight.\n4. Drive through your heels to stand back up to the starting position, squeezing your glutes at the top.\n5. Keep your knees tracking over your toes and avoid letting them cave inward.',
  ),
  ExercisePoolEntry(
    id: 'legs_bb_sumo_deadlifts',
    name: 'Sumo Deadlifts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
      MuscleGroup.adductors,
      MuscleGroup.back,
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Glutes, Inner Thighs, Hamstrings**\n\n1. Stand with your feet much wider than shoulder‑width apart, toes pointed out at about 45°.\n2. Position the barbell over the middle of your feet, with your shins touching the bar.\n3. Grip the bar with your hands inside your knees, using a shoulder‑width grip (or slightly narrower).\n4. Keep your chest up, back flat, and drive through your heels to lift the bar, squeezing your glutes at the top.\n5. Lower the bar with control, maintaining tension in your hamstrings and glutes.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_calf_raises',
    name: 'Bodyweight Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves**\n\n1. Stand upright with feet hip‑width apart, holding onto a wall or chair for balance if needed.\n2. Raise your heels as high as possible by pushing through the balls of your feet.\n3. Squeeze your calves at the top, hold for a second.\n4. Lower your heels back to the floor with control.\n5. Perform the movement slowly to maximise muscle tension.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_glute_bridges',
    name: 'Glute Bridges',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.hamstrings,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes**\n\n1. Lie on your back with your knees bent, feet flat on the floor, hip‑width apart.\n2. Place your arms at your sides, palms down.\n3. Press through your heels to lift your hips off the floor until your body forms a straight line from shoulders to knees.\n4. Squeeze your glutes at the top and hold for a second.\n5. Lower your hips back down with control.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_jump_squats',
    name: 'Jump Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.calves,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings (Power)**\n\n1. Start in a squat position with feet shoulder‑width apart.\n2. Squat down until your thighs are parallel to the floor, then explode upward, jumping as high as possible.\n3. Land softly with bent knees to absorb the impact, immediately descending into the next squat.\n4. Keep your chest up and core tight throughout.\n5. Focus on explosive power and controlled landings to protect your joints.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_lunges',
    name: 'Lunges',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Stand upright with feet hip‑width apart, hands on your hips.\n2. Step forward with your right leg, lowering your hips until both knees are bent at 90° (front knee over ankle, back knee hovering just above the floor).\n3. Push through your front heel to return to the starting position.\n4. Repeat with the left leg, alternating each rep.\n5. Keep your torso upright and core engaged throughout.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_pistol_squats_assisted',
    name: 'Pistol Squats (assisted)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.calves,
    ],
    compatibleSplits: {
      'Legs',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes (Unilateral)**\n\n1. Stand on one leg, extending the other leg forward and keeping it off the floor.\n2. Squat down on the standing leg, lowering your hips as far as you can while maintaining balance.\n3. Push through the heel of the standing leg to return to the starting position.\n4. To assist, hold onto a support (e.g., a chair or pole) or use a counterweight.\n5. Keep your chest up and back as straight as possible.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_side_lunges',
    name: 'Side Lunges',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.adductors,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Inner Thighs, Glutes**\n\n1. Stand with feet together, then take a wide step to the right with your right foot.\n2. Bend your right knee and push your hips back, lowering into a lunge while keeping your left leg straight.\n3. Push off your right foot to return to the starting position.\n4. Repeat on the left side, alternating.\n5. Keep your chest up and back straight throughout the movement.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_single_leg_calf_raises',
    name: 'Single-Leg Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves (Unilateral)**\n\n1. Stand on one leg, using a wall or chair for balance.\n2. Raise your heel as high as possible, squeezing the calf.\n3. Hold at the top for a moment, then lower with control.\n4. Complete all reps on one side before switching.\n5. To increase difficulty, perform on the edge of a step for a greater range of motion.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_single_leg_glute_bridges',
    name: 'Single-Leg Glute Bridges',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.hamstrings,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes (Unilateral)**\n\n1. Lie on your back with one foot flat on the floor, the other leg extended straight up.\n2. Drive through the heel of the grounded foot to lift your hips off the floor.\n3. Squeeze your glute at the top, then lower with control.\n4. Complete all reps on one side before switching.\n5. Keep your core braced to maintain stability.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_squats',
    name: 'Bodyweight Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Stand with feet shoulder‑width apart, toes slightly pointed out, arms extended forward for balance.\n2. Push your hips back and bend your knees, lowering your body as if sitting in a chair.\n3. Go as low as you can while keeping your chest up and back straight (ideally thighs parallel or below).\n4. Drive through your heels to return to the starting position, squeezing your glutes at the top.\n5. Keep your knees tracking over your toes and avoid letting them cave inward.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_sumo_squats',
    name: 'Sumo Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.adductors,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Inner Thighs, Glutes, Quadriceps**\n\n1. Stand with feet wider than shoulder‑width apart, toes pointed out at about 45°.\n2. Push your hips back and lower your body straight down, keeping your chest up and back straight.\n3. Descend until your thighs are at least parallel to the floor, feeling the stretch in your inner thighs.\n4. Drive through your heels to stand back up, squeezing your glutes at the top.\n5. Keep your knees tracking over your toes to avoid strain.',
  ),
  ExercisePoolEntry(
    id: 'legs_bw_walking_lunges',
    name: 'Walking Lunges',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Stand with feet together, take a long step forward with your right leg.\n2. Lower your hips until both knees are bent at 90°, with your back knee nearly touching the floor.\n3. Push off your back foot and step forward into the next lunge, alternating legs as you move forward.\n4. Keep your torso upright and core braced.\n5. Continue for the desired number of reps per leg.',
  ),
  ExercisePoolEntry(
    id: 'legs_cable_glute_kickbacks',
    name: 'Cable Glute Kickbacks',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes**\n\n1. Attach an ankle strap to a low pulley on a cable machine and secure it around your right ankle.\n2. Stand facing the machine, holding the support bar for balance, with your weight on your left leg.\n3. Keeping your knee slightly bent, kick your right leg straight back, squeezing your glute at the top.\n4. Return with control to the starting position.\n5. Complete all reps on one side before switching.',
  ),
  ExercisePoolEntry(
    id: 'legs_cable_hip_abduction',
    name: 'Cable Hip Abduction',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Glutes, TFL**\n\n1. Attach an ankle strap to a low pulley on the side of the machine.\n2. Stand with your side facing the machine, secure the strap to the ankle of the leg closest to the pulley.\n3. Keeping your core tight, pull your leg away from your body (abduction), squeezing your glute medius at the peak.\n4. Return slowly with control.\n5. Complete all reps on one side before switching.',
  ),
  ExercisePoolEntry(
    id: 'legs_cable_hip_adduction',
    name: 'Cable Hip Adduction',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.adductors,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Adductors**\n\n1. Attach an ankle strap to a low pulley on the side of the machine.\n2. Stand with your side facing the machine, secure the strap to the ankle of the leg farthest from the pulley.\n3. Keeping your core tight, pull your leg across your body (adduction), squeezing your inner thigh at the peak.\n4. Return slowly with control.\n5. Complete all reps on one side before switching.',
  ),
  ExercisePoolEntry(
    id: 'legs_cable_pull_through',
    name: 'Cable Pull-Through',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Hamstrings**\n\n1. Attach a rope to a low pulley and stand facing away from the machine, feet shoulder‑width apart.\n2. Hinge at the hips, reaching back between your legs to grip the rope, keeping your back flat.\n3. Drive your hips forward to stand up, squeezing your glutes at the top.\n4. Lower the rope back through your legs with control.\n5. Keep your core braced and your knees slightly bent throughout.',
  ),
  ExercisePoolEntry(
    id: 'legs_cable_squat_pulldown',
    name: 'Cable Squat Pulldown',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Set a cable at chest height with a rope or bar attachment.\n2. Take a slight step forward, hold the handle with both hands, and stand with feet shoulder‑width apart.\n3. Squat down as you would in a bodyweight squat, keeping your chest up and core engaged.\n4. As you stand up, pull the cable towards your chest to add resistance.\n5. Perform the movement in a controlled manner, squeezing your glutes at the top.',
  ),
  ExercisePoolEntry(
    id: 'legs_chair_bulgarian_split_squats',
    name: 'Bulgarian Split Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Stand about two feet in front of a sturdy chair or bench, with your back to it.\n2. Place the top of your right foot on the bench, laces down.\n3. Lower your hips by bending your left knee until your right knee nearly touches the floor.\n4. Push through your left heel to return to the starting position.\n5. Complete all reps on one side before switching.',
  ),
  ExercisePoolEntry(
    id: 'legs_chair_deep_squat_holds',
    name: 'Deep Squat Holds (with bench)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Stand in front of a chair (or bench) with feet shoulder‑width apart.\n2. Squat down slowly until your glutes just barely touch the seat, then hold that position for 2–3 seconds.\n3. Drive through your heels to stand back up.\n4. This helps build control and depth in the squat.\n5. Focus on keeping your chest up and knees tracking over your toes.',
  ),
  ExercisePoolEntry(
    id: 'legs_chair_hip_thrusts',
    name: 'Hip Thrusts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Hamstrings**\n\n1. Sit on the floor with your upper back leaning against the edge of a chair or bench, knees bent, feet flat.\n2. Place your arms on the chair for support, keep your chin tucked.\n3. Drive through your heels to lift your hips up until your body forms a straight line from shoulders to knees.\n4. Squeeze your glutes at the top, hold for a second.\n5. Lower your hips back down with control.',
  ),
  ExercisePoolEntry(
    id: 'legs_chair_single_leg_step_ups',
    name: 'Single-Leg Step-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Legs',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Stand on the chair with your right foot, with the left foot hanging off the edge.\n2. Slowly lower your body by bending your right knee until your left heel lightly touches the floor.\n3. Drive through your right heel to return to the standing position on the chair.\n4. Perform all reps on one leg before switching.\n5. Keep your core tight and avoid using momentum.',
  ),
  ExercisePoolEntry(
    id: 'legs_chair_step_ups',
    name: 'Step-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Stand in front of a sturdy chair or step (height about 12–18 inches).\n2. Place your right foot on the chair, drive through your heel to step up and bring your left foot to meet it.\n3. Step back down with your right foot first, then the left.\n4. Alternate the lead leg with each set.\n5. Keep your chest up and core engaged throughout.',
  ),
  ExercisePoolEntry(
    id: 'legs_curl_iso_hold',
    name: 'Leg Curl Isometric Hold',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.legCurlMachine,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings**\n\n1. Perform a standard leg curl, but when you reach the peak contraction, hold the position for 3–5 seconds.\n2. Maintain the hold, squeezing your hamstrings as hard as possible.\n3. Slowly lower the weight back to the starting position.\n4. This increases time under tension and improves mind‑muscle connection.\n5. Use a lighter weight to allow for the hold.',
  ),
  ExercisePoolEntry(
    id: 'legs_curl_seated',
    name: 'Seated Leg Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.legCurlMachine,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings**\n\n1. Sit on the seated leg curl machine, with the pad resting just above your heels (on the front of your ankles).\n2. Grasp the handles and keep your back against the pad.\n3. Curl the weight towards your glutes by flexing your hamstrings.\n4. Squeeze at the peak, then return slowly.\n5. This variation targets the hamstrings from a seated position, which can emphasise the medial head.',
  ),
  ExercisePoolEntry(
    id: 'legs_curl_single_leg',
    name: 'Single-Leg Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.legCurlMachine,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings (Unilateral)**\n\n1. Use the leg curl machine, but only place one leg under the pad, the other resting on the machine.\n2. Perform the curl with the working leg, focusing on the contraction.\n3. Squeeze at the top and lower with control.\n4. Complete all reps on one side before switching.\n5. This helps correct imbalances between legs.',
  ),
  ExercisePoolEntry(
    id: 'legs_curl_standard',
    name: 'Leg Curls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.legCurlMachine,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings**\n\n1. Lie face down on the leg curl machine, with the pad resting just above your heels.\n2. Grasp the handles for stability and keep your hips pressed against the pad.\n3. Curl your heels towards your glutes by flexing your hamstrings, squeezing at the peak.\n4. Lower the weight with control back to the starting position, fully extending your legs.\n5. Avoid using momentum; perform the movement slowly and deliberately.',
  ),
  ExercisePoolEntry(
    id: 'legs_db_bulgarian_split_squats',
    name: 'Dumbbell Bulgarian Split Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Hold a dumbbell in each hand, or a single dumbbell in goblet position, and stand about two feet in front of a bench.\n2. Place the top of one foot on the bench behind you.\n3. Lower into a lunge until your back knee nearly touches the floor, keeping your torso upright.\n4. Push through the front heel to return to the starting position.\n5. Complete all reps on one side before switching.',
  ),
  ExercisePoolEntry(
    id: 'legs_db_calf_raises',
    name: 'Dumbbell Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves**\n\n1. Stand on the edge of a step or a raised surface, holding a dumbbell in each hand for added weight.\n2. Lower your heels down until you feel a stretch in your calves.\n3. Raise your heels as high as possible, squeezing your calves.\n4. Hold at the top for a second, then lower with control.\n5. Perform the movement slowly and with full range of motion.',
  ),
  ExercisePoolEntry(
    id: 'legs_db_goblet_squats',
    name: 'Goblet Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Hold a single dumbbell vertically against your chest, cupping the top plate with both hands.\n2. Stand with feet shoulder‑width apart, keep your elbows pointing down.\n3. Squat down as low as you can while keeping your chest up and the weight close.\n4. Drive through your heels to stand back up.\n5. This movement is great for learning proper squat form.',
  ),
  ExercisePoolEntry(
    id: 'legs_db_lunges',
    name: 'Dumbbell Lunges',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Hold a dumbbell in each hand, arms at your sides.\n2. Step forward with one leg and lower your hips until both knees are bent at 90°.\n3. Push through the front heel to return to the starting position.\n4. Repeat with the other leg, alternating each rep.\n5. Keep your torso upright and core engaged.',
  ),
  ExercisePoolEntry(
    id: 'legs_db_romanian_deadlifts',
    name: 'Dumbbell Romanian Deadlifts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.hamstrings,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings, Glutes**\n\n1. Stand with feet hip‑width apart, holding a dumbbell in each hand in front of your thighs.\n2. Keeping your knees slightly bent, push your hips back and lower the dumbbells along your shins.\n3. Lower until you feel a stretch in your hamstrings (bar around mid‑shin).\n4. Drive your hips forward to return to the starting position, squeezing your glutes.\n5. Keep your back flat and core braced throughout.',
  ),
  ExercisePoolEntry(
    id: 'legs_db_step_ups',
    name: 'Dumbbell Step-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Hold a dumbbell in each hand, stand in front of a sturdy platform (chair, step).\n2. Place one foot on the platform, drive through the heel to step up, bringing the other foot to meet it.\n3. Step back down with control.\n4. Alternate the lead leg with each set.\n5. Keep your chest up and core tight.',
  ),
  ExercisePoolEntry(
    id: 'legs_ext_drop_set',
    name: 'Leg Extension Drop Set',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.legExtensionMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps**\n\n1. Perform a set of leg extensions to failure with a heavy weight.\n2. Immediately reduce the weight by about 20–30% and perform another set to failure.\n3. Reduce again and perform a third set to failure.\n4. This technique maximises muscle fatigue and hypertrophy.\n5. Rest appropriately between drop sets.',
  ),
  ExercisePoolEntry(
    id: 'legs_ext_iso_hold',
    name: 'Leg Extension Isometric Hold',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.legExtensionMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps**\n\n1. Perform a standard leg extension, but hold the fully extended position for 3–5 seconds.\n2. Squeeze your quads hard during the hold.\n3. Lower with control.\n4. This increases time under tension and improves neuromuscular connection.\n5. Use a moderate weight that allows you to maintain the hold.',
  ),
  ExercisePoolEntry(
    id: 'legs_ext_partial_reps',
    name: 'Leg Extension Partial Reps',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.legExtensionMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps**\n\n1. Perform leg extensions but only in the top half of the range of motion (from about 90° to full extension).\n2. Keep constant tension on the quads by not fully lowering the weight.\n3. Squeeze at the top.\n4. Perform reps without locking out completely to maintain continuous tension.\n5. This is effective for adding volume and stimulating growth.',
  ),
  ExercisePoolEntry(
    id: 'legs_ext_single_leg',
    name: 'Single-Leg Extensions',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.legExtensionMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps (Unilateral)**\n\n1. Use the leg extension machine, but only with one leg, the other resting.\n2. Extend the working leg fully, squeezing the quad.\n3. Lower with control.\n4. Complete all reps on one side before switching.\n5. This helps address strength imbalances.',
  ),
  ExercisePoolEntry(
    id: 'legs_ext_standard',
    name: 'Leg Extensions',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.legExtensionMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps**\n\n1. Sit on the leg extension machine with your back against the pad and your shins behind the ankle pad.\n2. Grasp the handles for stability, keep your knees aligned with the machine\'s pivot.\n3. Extend your legs until they are straight, squeezing your quads at the top.\n4. Lower the weight with control back to the starting position.\n5. Avoid swinging; use a controlled tempo.',
  ),
  ExercisePoolEntry(
    id: 'legs_hack_narrow_stance',
    name: 'Hack Squat - Narrow Stance',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.hackSquatMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
      MuscleGroup.glutes,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps (outer)**\n\n1. Place your feet close together (6–8 inches apart) on the platform.\n2. Perform the hack squat as described, focusing on knee extension.\n3. This stance targets the outer quads more.\n4. Keep your knees tracking over your toes.\n5. Use a moderate weight to maintain control.',
  ),
  ExercisePoolEntry(
    id: 'legs_hack_reverse',
    name: 'Reverse Hack Squat',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.hackSquatMachine,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Hamstrings**\n\n1. Face the hack squat machine, placing your shoulders against the pads and feet on the platform.\n2. Your hips will be more flexed, shifting emphasis to the posterior chain.\n3. Lower into a squat, pushing your hips back, then drive up through your heels.\n4. Keep your back straight and core tight.\n5. This variation is excellent for glute and hamstring development.',
  ),
  ExercisePoolEntry(
    id: 'legs_hack_single_leg',
    name: 'Single-Leg Hack Squat',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.hackSquatMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes (Unilateral)**\n\n1. Place one foot on the platform, the other resting on the machine frame.\n2. Unrack the weight and perform a squat using only the working leg.\n3. Lower until your thigh is parallel or below, then press back up.\n4. Complete all reps on one side before switching.\n5. Use a lighter weight to maintain balance and control.',
  ),
  ExercisePoolEntry(
    id: 'legs_hack_standard',
    name: 'Hack Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.hackSquatMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Position yourself in the hack squat machine with your shoulders under the pads and feet shoulder‑width apart on the platform.\n2. Unrack the weight and lower your body by bending your knees, keeping your back against the pad.\n3. Descend until your thighs are at least parallel to the floor (or below).\n4. Drive through your heels to push the weight back up, without locking your knees.\n5. Keep your core braced and maintain a controlled tempo.',
  ),
  ExercisePoolEntry(
    id: 'legs_hack_wide_stance',
    name: 'Hack Squat - Wide Stance',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.hackSquatMachine,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.adductors,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Adductors**\n\n1. Place your feet wider than shoulder‑width apart on the platform.\n2. Perform the hack squat, focusing on pushing through your heels and using your hips.\n3. This stance emphasises the glutes and inner thighs.\n4. Keep your back flat against the pad throughout.\n5. Control the descent and drive up powerfully.',
  ),
  ExercisePoolEntry(
    id: 'legs_kb_goblet_squats',
    name: 'Kettlebell Goblet Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Hold a kettlebell by the horns (or the handle) against your chest, elbows pointing down.\n2. Stand with feet shoulder‑width apart, keep your chest up.\n3. Squat down as low as you can while keeping the kettlebell close to your body.\n4. Drive through your heels to stand back up.\n5. This movement reinforces proper squat mechanics.',
  ),
  ExercisePoolEntry(
    id: 'legs_kb_lunges',
    name: 'Kettlebell Lunges',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Hold a kettlebell in each hand or a single kettlebell in the rack position.\n2. Step forward into a lunge, lowering your hips until both knees are bent at 90°.\n3. Push through your front heel to return to the starting position.\n4. Alternate legs with each rep.\n5. Keep your torso upright and the kettlebell(s) stable.',
  ),
  ExercisePoolEntry(
    id: 'legs_kb_single_arm_deadlifts',
    name: 'Single-Arm Kettlebell Deadlifts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.hamstrings,
      MuscleGroup.glutes,
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings, Glutes, Core**\n\n1. Stand with feet hip‑width apart, a kettlebell on the floor between your legs.\n2. Hinge at the hips, grip the kettlebell with one hand, keeping your back flat.\n3. Drive through your heels to stand up, keeping the kettlebell close to your body.\n4. Squeeze your glute at the top, then lower with control.\n5. Complete all reps on one side before switching.',
  ),
  ExercisePoolEntry(
    id: 'legs_kb_swings',
    name: 'Kettlebell Swings',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Hamstrings, Core**\n\n1. Stand with feet shoulder‑width apart, a kettlebell on the floor in front of you.\n2. Hinge at your hips, grasp the kettlebell with both hands, and swing it back between your legs.\n3. Explosively drive your hips forward to swing the kettlebell up to chest height.\n4. Let the kettlebell swing back down between your legs, keeping your back flat.\n5. Repeat for the desired number of reps, maintaining a steady rhythm.',
  ),
  ExercisePoolEntry(
    id: 'legs_lp_high_foot',
    name: 'Leg Press - High Foot Placement',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.legPressMachine,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Hamstrings**\n\n1. Place your feet high on the platform (near the top edge), shoulder‑width apart.\n2. Perform the leg press as usual, but you\'ll feel more hip involvement.\n3. Lower until your knees are at 90°, press through your heels.\n4. This variation emphasises glutes and hamstrings.\n5. Keep your back flat against the pad.',
  ),
  ExercisePoolEntry(
    id: 'legs_lp_low_foot',
    name: 'Leg Press - Low Foot Placement',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.legPressMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
      MuscleGroup.glutes,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps**\n\n1. Place your feet low on the platform (near the bottom edge), shoulder‑width apart.\n2. Perform the leg press, focusing on knee extension.\n3. This variation targets the quads more directly.\n4. Lower until your knees are at 90°, press up.\n5. Keep your heels flat on the platform.',
  ),
  ExercisePoolEntry(
    id: 'legs_lp_narrow_stance',
    name: 'Leg Press - Narrow Stance',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.legPressMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
      MuscleGroup.glutes,
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps (outer)**\n\n1. Place your feet close together (6–8 inches apart) on the platform.\n2. Perform the leg press, focusing on knee extension.\n3. This stance emphasises the outer quads.\n4. Lower until your knees are at 90°, press up.\n5. Keep your back flat against the pad.',
  ),
  ExercisePoolEntry(
    id: 'legs_lp_single_leg',
    name: 'Single-Leg Leg Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.legPressMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes (Unilateral)**\n\n1. Place one foot in the centre of the platform, the other foot resting on the floor or the machine frame.\n2. Perform the leg press using only the working leg.\n3. Lower until your knee is at 90°, press up.\n4. Complete all reps on one side before switching.\n5. Use a lighter weight to maintain balance and control.',
  ),
  ExercisePoolEntry(
    id: 'legs_lp_standard',
    name: 'Leg Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.legPressMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Sit on the leg press machine with your back flat against the pad and feet shoulder‑width apart on the platform.\n2. Unrack the weight and lower the platform by bending your knees, bringing them toward your chest.\n3. Lower until your knees are at 90° (or slightly below), keeping your feet flat.\n4. Press through your heels to push the platform back up, without locking your knees.\n5. Keep your hips and lower back pressed against the seat throughout.',
  ),
  ExercisePoolEntry(
    id: 'legs_selector_hip_abduction',
    name: 'Selectorized Hip Adduction',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Glutes, TFL**\n\n1. Sit on the hip abduction machine, with your thighs against the pads and your hands on the handles.\n2. Press your thighs outward against the pads, squeezing your glute medius.\n3. Hold for a second at the peak, then return with control.\n4. Keep your torso stable and avoid using momentum.\n5. This targets the hip abductors and glute medius.',
  ),
  ExercisePoolEntry(
    id: 'legs_selector_hip_adduction',
    name: 'Hip Adduction Machine',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.adductors,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Adductors**\n\n1. Sit on the hip adduction machine, with your thighs inside the pads and your hands on the handles.\n2. Squeeze your thighs together against the pads, engaging your adductors.\n3. Hold for a second at the peak, then return with control.\n4. Keep your torso stable and avoid using momentum.\n5. This targets the inner thigh muscles.',
  ),
  ExercisePoolEntry(
    id: 'legs_selector_seated_calf_raises',
    name: 'Seated Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves (Soleus)**\n\n1. Sit on the seated calf raise machine, with the pads resting on your knees.\n2. Place your feet on the platform with your heels hanging off the edge.\n3. Lower your heels down for a full stretch, then raise them as high as possible.\n4. Squeeze your calves at the top, hold for a second.\n5. Lower with control, feeling the stretch.',
  ),
  ExercisePoolEntry(
    id: 'legs_selector_standing_calf_raises',
    name: 'Standing Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves (Gastrocnemius)**\n\n1. Stand on the standing calf raise machine, with your shoulders under the pads and feet on the step.\n2. Lower your heels down for a stretch, then raise them as high as possible.\n3. Squeeze your calves at the top, hold for a second.\n4. Lower with control.\n5. Keep your knees straight throughout for maximum gastrocnemius activation.',
  ),
  ExercisePoolEntry(
    id: 'legs_smith_calf_raises',
    name: 'Smith Machine Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves**\n\n1. Place the Smith bar across your shoulders, stand on a step or a raised surface.\n2. Lower your heels down for a stretch, then raise them as high as possible.\n3. Squeeze your calves at the top, hold for a second.\n4. Lower with control.\n5. The Smith machine provides stability and lets you load heavier than bodyweight.',
  ),
  ExercisePoolEntry(
    id: 'legs_smith_front_squats',
    name: 'Smith Machine Front Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Legs',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes**\n\n1. Place the Smith bar across the front of your shoulders, crossing your arms to hold it.\n2. Stand with feet shoulder‑width apart, elbows high.\n3. Squat down, keeping your torso as upright as possible, following the track.\n4. Descend to parallel, then drive up through your heels.\n5. This variation targets the quads more with less hip hinge.',
  ),
  ExercisePoolEntry(
    id: 'legs_smith_hip_thrusts',
    name: 'Smith Machine Hip Thrusts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes, Hamstrings**\n\n1. Sit on the floor with your upper back against a bench, the Smith bar across your hips (use a pad).\n2. Place your feet flat on the floor, knees bent.\n3. Drive through your heels to lift your hips, squeezing your glutes at the top.\n4. Pause, then lower with control.\n5. The Smith machine adds stability and allows for heavier loading.',
  ),
  ExercisePoolEntry(
    id: 'legs_smith_lunges',
    name: 'Smith Machine Lunges',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Place the Smith bar across your upper back and position your feet in a staggered stance.\n2. Lower your back knee toward the floor, keeping your front knee over your ankle.\n3. Push through your front heel to return to the starting position.\n4. Alternate legs for each rep or complete a set per leg.\n5. The fixed path provides stability.',
  ),
  ExercisePoolEntry(
    id: 'legs_smith_squats',
    name: 'Smith Machine Squats',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Hamstrings**\n\n1. Place a barbell across your upper back (or use the Smith machine bar) and position yourself under the fixed path.\n2. Unrack the bar and stand with feet shoulder‑width apart, toes slightly pointed out.\n3. Squat down, keeping your back flat and chest up, following the vertical track.\n4. Descend until your thighs are parallel to the floor, then drive through your heels to stand up.\n5. The fixed path helps maintain balance and form.',
  ),
  ExercisePoolEntry(
    id: 'legs_stairs_box_jumps',
    name: 'Box Jumps',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.stairsOrStep,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps, Glutes, Calves (Power)**\n\n1. Stand in front of a sturdy box or step, about 12–24 inches high.\n2. Squat down and explode upward, jumping onto the box.\n3. Land softly with bent knees, absorbing the impact.\n4. Step down carefully and reset.\n5. This builds explosive lower body power.',
  ),
  ExercisePoolEntry(
    id: 'legs_stairs_calf_raises',
    name: 'Calf Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.stairsOrStep,
    targetMuscles: [
      MuscleGroup.calves,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Calves**\n\n1. Stand on the edge of a step with your heels hanging off.\n2. Lower your heels down for a deep stretch, then raise them as high as possible.\n3. Squeeze your calves at the top, hold for a second.\n4. Lower with control.\n5. This is a great way to increase range of motion.',
  ),
  ExercisePoolEntry(
    id: 'legs_stairs_lateral_step_ups',
    name: 'Lateral Step-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.stairsOrStep,
    targetMuscles: [
      MuscleGroup.quadriceps,
      MuscleGroup.glutes,
      MuscleGroup.adductors,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Legs',
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.lunge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Quadriceps, Glutes, Adductors**\n\n1. Stand sideways to a step, feet together.\n2. Step up sideways with your right foot onto the step, then bring your left foot up.\n3. Step down sideways, then repeat on the other side.\n4. Keep your chest up and core tight.\n5. This variation targets the inner and outer thighs.',
  ),
  ExercisePoolEntry(
    id: 'lower_chair_single_leg_hip_thrust',
    name: 'Single-Leg Hip Thrust',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.chairOrSimpleBench,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.hamstrings,
    ],
    compatibleSplits: {
      'Lower Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Glutes (Unilateral)**\n\n1. Lie on your back with your upper back against a chair, one foot flat on the floor, the other leg extended straight up.\n2. Drive through the heel of the grounded foot to lift your hips off the floor.\n3. Squeeze your glute at the top, then lower with control.\n4. Complete all reps on one side before switching.\n5. Keep your core braced to maintain stability.',
  ),
  ExercisePoolEntry(
    id: 'lower_db_romanian_deadlifts',
    name: 'Romanian Deadlifts',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.hamstrings,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings, Glutes**\n\n1. Stand with feet hip‑width apart, holding a dumbbell in each hand in front of your thighs.\n2. Keeping your knees slightly bent, push your hips back and lower the dumbbells along your shins.\n3. Lower until you feel a stretch in your hamstrings (bar around mid‑shin).\n4. Drive your hips forward to return to the starting position, squeezing your glutes.\n5. Keep your back flat and core braced throughout.',
  ),
  ExercisePoolEntry(
    id: 'lower_kb_single_leg_deadlift',
    name: 'Kettlebell Single-Leg Deadlift',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.hamstrings,
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings, Glutes (Unilateral)**\n\n1. Stand on one leg, holding a kettlebell in the opposite hand.\n2. Hinge at your hips, keeping your back flat, and lower the kettlebell towards the floor.\n3. Keep your standing leg slightly bent and your core engaged.\n4. Drive through the heel of the standing leg to return to the starting position, squeezing your glute.\n5. Complete all reps on one side before switching.',
  ),
  ExercisePoolEntry(
    id: 'lower_selector_hip_abduction',
    name: 'Selectorized Hip Abduction',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.glutes,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Lower Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Glutes**\n\n1. Sit on the hip abduction machine, with your thighs against the pads and your hands on the handles.\n2. Press your thighs outward against the pads, squeezing your glute medius.\n3. Hold for a second at the peak, then return with control.\n4. Keep your torso stable and avoid using momentum.\n5. This targets the hip abductors and glute medius.',
  ),
  ExercisePoolEntry(
    id: 'lower_selector_leg_curl',
    name: 'Selectorized Leg Curl',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.hamstrings,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.hinge,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Hamstrings**\n\n1. Lie face down on the leg curl machine, with the pad resting just above your heels.\n2. Grasp the handles for stability and keep your hips pressed against the pad.\n3. Curl your heels towards your glutes by flexing your hamstrings, squeezing at the peak.\n4. Lower the weight with control back to the starting position, fully extending your legs.\n5. Avoid using momentum; perform the movement slowly and deliberately.',
  ),
  ExercisePoolEntry(
    id: 'lower_selector_leg_extension',
    name: 'Selectorized Leg Extension',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.quadriceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Lower Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.squat,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Quadriceps**\n\n1. Sit on the leg extension machine with your back against the pad and your shins behind the ankle pad.\n2. Grasp the handles for stability, keep your knees aligned with the machine\'s pivot.\n3. Extend your legs until they are straight, squeezing your quads at the top.\n4. Lower the weight with control back to the starting position.\n5. Avoid swinging; use a controlled tempo.',
  ),
];
