// lib/engines/workout_engine/shared/exercises/catalog/definitions/shoulders_exercises.dart
// ⚠️ AUTO-GENERATED – DO NOT EDIT MANUALLY

import 'package:gymgenius/domain/enums/exports.dart';
import 'package:gymgenius/engines/workout_engine/shared/exercise_pool_entry.dart';

/// Canonical definitions for shoulders exercises.
const List<ExercisePoolEntry> shouldersDefinitions = [
  ExercisePoolEntry(
    id: 'arms_bw_plank_shoulder_taps',
    name: 'Plank Shoulder Taps',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Arms',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps, Core**\n\n1. Start in a high plank position with your hands directly under your shoulders.\n2. Lift your right hand off the floor and tap your left shoulder, keeping your hips as still as possible.\n3. Return your right hand to the floor, then lift your left hand to tap your right shoulder.\n4. Continue alternating, keeping your core braced to prevent your hips from swaying.\n5. To reduce difficulty, perform with your knees on the floor.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_wall_handstand_hold',
    name: 'Wall Handstand Hold',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Place your hands on the floor about 6–12 inches from a wall, shoulder‑width apart.\n2. Kick up into a handstand position, resting your feet against the wall for support.\n3. Keep your arms straight, shoulders engaged, and core tight.\n4. Hold for the prescribed time, maintaining a straight body line.\n5. To reduce difficulty, practice with one foot on the wall and one foot off.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bb_barbell_shrugs',
    name: 'Barbell Shrugs',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Trapezius**\n\n1. Stand upright with feet shoulder‑width apart, holding a barbell in front of your thighs with an overhand grip.\n2. Keeping your arms straight, shrug your shoulders straight up towards your ears as high as possible.\n3. Squeeze your traps at the top, hold for a second, then lower the bar back down with control.\n4. Avoid rolling your shoulders; focus on a pure vertical movement.\n5. Use a heavy weight but maintain strict form to avoid injury.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_smith_shrugs',
    name: 'Smith Machine Shrugs',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Traps**\n\n1. Set the Smith machine bar at thigh height and load a heavy weight.\n2. Stand upright, grip the bar with an overhand grip, hands shoulder‑width apart.\n3. Shrug your shoulders straight up towards your ears as high as possible, squeezing your traps.\n4. Hold at the top for a second, then lower the bar back down with control.\n5. Avoid rolling your shoulders; focus on a pure vertical movement.',
  ),
  ExercisePoolEntry(
    id: 'pull_db_dumbbell_shrugs',
    name: 'Dumbbell Shrugs',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Trapezius**\n\n1. Stand upright with feet shoulder‑width apart, holding a dumbbell in each hand at your sides, palms facing your body.\n2. Keeping your arms straight, shrug your shoulders straight up towards your ears as high as possible.\n3. Squeeze your traps at the top, hold for a second, then lower with control.\n4. Avoid rolling your shoulders; focus on a pure vertical movement.\n5. Use moderate weight to maintain strict form.',
  ),
  ExercisePoolEntry(
    id: 'pull_kb_shrugs',
    name: 'Kettlebell Shrugs',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Traps**\n\n1. Stand upright with feet shoulder‑width apart, holding a kettlebell in each hand at your sides.\n2. Keeping your arms straight, shrug your shoulders straight up towards your ears as high as possible.\n3. Squeeze your traps at the top, hold for a second, then lower with control.\n4. Avoid rolling your shoulders; focus on a pure vertical movement.\n5. Use moderate weight to maintain strict form.',
  ),
  ExercisePoolEntry(
    id: 'push_band_lateral_raises',
    name: 'Band Lateral Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Shoulders',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Side Shoulders**\n\n1. Stand on the middle of a resistance band, holding a handle in each hand at your sides.\n2. Keep a slight bend in your elbows and raise your arms laterally to shoulder height.\n3. Pause at the top, then lower slowly against the band tension.\n4. Keep your core tight and avoid swinging.',
  ),
  ExercisePoolEntry(
    id: 'push_band_overhead_press',
    name: 'Band Shoulder Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Shoulders',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Stand on the band, holding the handles at shoulder height with palms facing forward.\n2. Press the handles overhead until your arms are fully extended.\n3. Lower back to shoulder height with control, maintaining tension in the band.\n4. Keep your core braced and avoid arching your back.',
  ),
  ExercisePoolEntry(
    id: 'push_bb_overhead_barbell_press',
    name: 'Military Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Shoulders',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Stand with feet shoulder‑width apart, holding the bar at shoulder height with an overhand grip, hands just outside your shoulders.\n2. Keep your core tight and press the bar overhead until your arms are fully extended.\n3. Pause briefly at the top, then lower the bar back to shoulder height with control.\n4. Avoid arching your back excessively; keep the bar path vertical.',
  ),
  ExercisePoolEntry(
    id: 'push_bw_pike_push_ups',
    name: 'Pike Push-Up',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Push',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Start in a downward‑dog position with your hips high, hands shoulder‑width apart, and feet on the floor.\n2. Bend your elbows to lower the top of your head towards the floor, keeping your body in an inverted V shape.\n3. Press back up to the starting position, focusing on the shoulder muscles.\n4. Keep your core braced and your weight shifted forward onto your hands.',
  ),
  ExercisePoolEntry(
    id: 'push_cable_lateral_raise',
    name: 'Cable Lateral Raise',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Side Shoulders**\n\n1. Stand sideways to a low pulley, holding the handle with the hand farthest from the machine.\n2. Keep your core tight and raise your arm laterally to shoulder height.\n3. Hold for a second, then lower with control.\n4. Complete all reps on one side before switching.',
  ),
  ExercisePoolEntry(
    id: 'push_db_arnold_press',
    name: 'Arnold Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Shoulders',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders (all heads), Triceps**\n\n1. Sit on a bench with dumbbells held in front of your shoulders, palms facing you.\n2. Press the weights upward while rotating your palms to face forward at the top.\n3. Squeeze your shoulders at the top, then reverse the motion as you lower back down.\n4. Maintain a smooth, controlled tempo throughout.',
  ),
  ExercisePoolEntry(
    id: 'push_db_lateral_raises',
    name: 'Lateral Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Side Shoulders**\n\n1. Stand with feet shoulder‑width apart, dumbbells at your sides, palms facing inward.\n2. Keep a slight bend in your elbows and raise the dumbbells laterally to shoulder height.\n3. Pause briefly at the top, then lower them slowly back to the starting position.\n4. Avoid swinging your body; use strict form.',
  ),
  ExercisePoolEntry(
    id: 'push_db_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Shoulders',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Sit on a bench with back support, holding dumbbells at shoulder height with palms facing forward.\n2. Press the weights overhead until your arms are fully extended, keeping them close together.\n3. Pause briefly at the top, then lower them back to shoulder height with control.\n4. Keep your core braced and avoid arching your back.',
  ),
  ExercisePoolEntry(
    id: 'push_kb_arnold_press',
    name: 'Kettlebell Arnold Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders (all heads), Triceps**\n\n1. Hold kettlebells in front of your shoulders with palms facing you.\n2. Press upward while rotating your palms to face forward at the top.\n3. Reverse the rotation as you lower back down to the starting position.\n4. Keep the movement smooth and controlled.',
  ),
  ExercisePoolEntry(
    id: 'push_kb_bottoms_up_press',
    name: 'Kettlebell Bottoms-Up Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Core (Stability)**\n\n1. Hold a kettlebell upside down by the handle, with the bell facing upward.\n2. Press it overhead while keeping it stable – the unstable load forces your core and stabilisers to work hard.\n3. Lower with control, then switch sides.\n4. Use a lighter weight than usual to maintain control.',
  ),
  ExercisePoolEntry(
    id: 'push_kb_kettlebell_overhead_press',
    name: 'Kettlebell Overhead Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Rack a kettlebell against your forearm at shoulder height, keeping your elbow close to your body.\n2. Press the kettlebell overhead until your arm is fully extended.\n3. Pause briefly, then lower it back to the rack position with control.\n4. Complete all reps on one side before switching.',
  ),
  ExercisePoolEntry(
    id: 'push_kb_push_press',
    name: 'Kettlebell Push Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps, Quads**\n\n1. Rack kettlebells at your shoulders, feet hip‑width apart.\n2. Dip by bending your knees slightly, then drive up explosively and press the kettlebells overhead.\n3. As you press, use the leg drive to help lift the weight.\n4. Lower the kettlebells back to the rack position with control.',
  ),
  ExercisePoolEntry(
    id: 'push_selector_machine_shoulder_press',
    name: 'Machine Shoulder Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Sit at the shoulder press machine and adjust the seat so the handles are at shoulder height.\n2. Press the handles upward until your arms are fully extended.\n3. Pause at the top, then lower with control.\n4. Keep your head and back against the pad for support.',
  ),
  ExercisePoolEntry(
    id: 'push_smith_shoulder_press',
    name: 'Smith Machine Shoulder Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Place a bench (flat or with back support) under the Smith bar.\n2. Sit with the bar at shoulder height, grip it shoulder‑width apart.\n3. Press the bar overhead until your arms are fully extended.\n4. Lower back to shoulder height with control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_band_front_raise',
    name: 'Band Front Raise',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Front Shoulders**\n\n1. Stand on a resistance band, holding the handles in front of your thighs, arms straight.\n2. Raise your arms forward to shoulder height, keeping them straight and the band under tension.\n3. Pause at the top, then lower with control.\n4. Keep your core tight and avoid using momentum.\n5. For increased tension, use a thicker band or step further onto it.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_band_upright_row',
    name: 'Band Upright Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Traps**\n\n1. Stand on a resistance band, holding the handles with an overhand grip in front of your thighs.\n2. Pull the handles straight up towards your chin, leading with your elbows.\n3. Keep the handles close to your body and pause at the top.\n4. Lower with control against the band tension.\n5. Avoid excessive tension to prevent shoulder impingement.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_bw_handstand_push_ups',
    name: 'Handstand Push-ups (against wall)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Place your hands on the floor about 6–12 inches from a wall, shoulder‑width apart.\n2. Kick up into a handstand position, resting your feet against the wall for support.\n3. Keeping your body straight, bend your elbows to lower your head toward the floor.\n4. Press back up to full extension, squeezing your shoulders at the top.\n5. Keep your core tight and avoid arching your back.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_bw_pike_push_ups',
    name: 'Pike Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Start in a downward‑dog position with your hips high, hands shoulder‑width apart, feet on the floor.\n2. Bend your elbows to lower the top of your head toward the floor, keeping your body in an inverted V shape.\n3. Push back up to the starting position, focusing on the shoulder muscles.\n4. Keep your core braced and your weight shifted forward onto your hands.\n5. To increase difficulty, place your feet on an elevated surface.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_bw_pike_push_ups_feet_elevated',
    name: 'Elevated Pike Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Place your feet on a bench or chair, hands on the floor, and assume a pike position (hips high).\n2. Lower the top of your head toward the floor, increasing the range of motion.\n3. Push back up to the starting position, focusing on the shoulders.\n4. This variation adds more load to the anterior deltoids.\n5. Keep your core tight and your body stable.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_bw_pseudo_planche_push_ups',
    name: 'Pseudo Planche Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Chest**\n\n1. Start in a push‑up position, but place your hands lower than usual (toward your hips) and lean your shoulders forward.\n2. Keep your body straight and perform a push‑up, lowering your chest toward the floor.\n3. Push back up, maintaining the forward lean throughout.\n4. This variation places greater demand on the anterior deltoids.\n5. Use a controlled tempo to maximise muscle engagement.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_bw_wall_walks',
    name: 'Wall Walks',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Chest**\n\n1. Start in a push‑up position facing a wall, with your feet on the floor and hands on the floor.\n2. Walk your feet up the wall while simultaneously walking your hands back toward the wall.\n3. Continue until your body is nearly vertical (or as high as you can comfortably go).\n4. Reverse the movement, walking your feet back down and hands forward.\n5. This builds shoulder strength and control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_cable_front_raise',
    name: 'Cable Front Raise',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Front Shoulders**\n\n1. Attach a D‑handle to a low pulley and stand facing the machine.\n2. Grab the handle with one hand, keeping your arm straight, and raise it forward to shoulder height.\n3. Pause briefly, then lower with control.\n4. Complete all reps on one side before switching.\n5. Keep your core tight to avoid swaying.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_cable_reverse_fly',
    name: 'Cable Reverse Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.back,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts**\n\n1. Set two cables at shoulder height and attach D‑handles.\n2. Stand in the middle, cross the handles in front of you so your arms form an X.\n3. With a slight bend in your elbows, pull the handles out to the sides, squeezing your shoulder blades together.\n4. Pause at the peak, then return slowly to the crossed position.\n5. Keep your back straight and core braced.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_cable_upright_row',
    name: 'Cable Upright Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Traps**\n\n1. Attach a straight bar to a low pulley.\n2. Stand facing the pulley, grip the bar with an overhand grip, hands shoulder‑width apart.\n3. Pull the bar straight up towards your chin, leading with your elbows.\n4. Pause at the top, then lower with control.\n5. Keep the bar close to your body throughout the movement.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_core_bb_overhead_carry',
    name: 'Overhead Barbell Carry',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: true,
    movementPattern: MovementPattern.carry,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Core**\n\n1. Press a barbell overhead and lock it out with arms extended.\n2. Brace your core, keep your shoulders packed down, and walk forward for the prescribed distance or time.\n3. Maintain stability; keep the bar directly over your shoulders.\n4. Avoid letting the bar drift forward or backward.\n5. This exercise builds shoulder stability and core strength.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_core_bb_push_press',
    name: 'Push Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps, Quads**\n\n1. Hold a barbell at shoulder height with an overhand grip, feet shoulder‑width apart.\n2. Dip slightly by bending your knees (about 10–15°), keeping your torso upright.\n3. Explosively drive through your legs to generate momentum, pressing the bar overhead as you extend your hips and knees.\n4. Lock out your arms overhead, then lower the bar back to shoulder height with control.\n5. This variation uses leg drive to press heavier loads.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_core_bb_upright_row',
    name: 'Barbell Upright Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Traps**\n\n1. Stand upright with feet shoulder‑width apart, holding a barbell with an overhand grip, hands shoulder‑width apart.\n2. Let the bar hang at arm\'s length in front of your thighs.\n3. Pull the bar straight up towards your chin, leading with your elbows, keeping the bar close to your body.\n4. Pause at the top, then lower the bar with control back to the starting position.\n5. Avoid using momentum; use a controlled tempo.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_core_db_front_raises',
    name: 'Front Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Front Shoulders**\n\n1. Stand with feet shoulder‑width apart, holding a dumbbell in each hand in front of your thighs, palms facing your body.\n2. Keep your arms straight and raise them forward to shoulder height.\n3. Pause briefly, then lower with control.\n4. Avoid using momentum; keep the movement controlled.\n5. To increase intensity, perform one arm at a time.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_core_db_upright_rows',
    name: 'Upright Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Traps**\n\n1. Stand upright, holding a dumbbell in each hand in front of your thighs, palms facing your body.\n2. Pull the dumbbells straight up towards your chin, leading with your elbows.\n3. Keep the weights close to your body and pause at the top.\n4. Lower with control back to the starting position.\n5. Avoid excessive weight to prevent shoulder impingement.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_selector_front_raise',
    name: 'Selectorized Front Raise',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Front Shoulders**\n\n1. Sit at the front raise machine, grip the handles, and rest your forearms on the pads.\n2. Raise your arms forward to shoulder height, keeping them straight.\n3. Pause at the top, then lower with control.\n4. Keep your back against the pad and avoid using momentum.\n5. This machine provides constant tension throughout the range of motion.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_selector_lateral_raise',
    name: 'Selectorized Lateral Raise',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Side Shoulders**\n\n1. Sit on the lateral raise machine, place your forearms against the pads, and grip the handles.\n2. Raise your arms out to the sides to shoulder height, keeping a slight bend in your elbows.\n3. Pause at the top, then lower with control.\n4. Keep your back flat against the pad.\n5. Use light weight to focus on the contraction of the medial delts.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_selector_shoulder_press',
    name: 'Selectorized Shoulder Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Sit at the shoulder press machine, adjust the seat so the handles are at shoulder height.\n2. Grip the handles, keep your back against the pad, and press upward until your arms are fully extended.\n3. Pause briefly, then lower with control.\n4. Keep your head and back against the pad for support.\n5. Use a moderate weight to maintain proper form.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_selector_shrugs',
    name: 'Selectorized Shrugs',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Traps**\n\n1. Stand or sit at the shrug machine, grip the handles, and keep your arms straight.\n2. Shrug your shoulders straight up towards your ears as high as possible.\n3. Squeeze your traps at the top, hold for a second.\n4. Lower with control back to the starting position.\n5. Avoid rolling your shoulders; focus on a pure vertical movement.',
  ),
  ExercisePoolEntry(
    id: 'upper_band_overhead_press',
    name: 'Band Overhead Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Stand on the middle of a resistance band, holding a handle in each hand at shoulder height.\n2. Press the handles overhead until your arms are fully extended.\n3. Lower back to shoulder height with control, maintaining tension.\n4. Keep your core tight and avoid arching your back.',
  ),
  ExercisePoolEntry(
    id: 'upper_bb_overhead_press',
    name: 'Overhead Barbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Stand with feet shoulder‑width apart, holding the bar at shoulder height with an overhand grip, hands just outside your shoulders.\n2. Keep your core tight and press the bar overhead until your arms are fully extended.\n3. Pause briefly at the top, then lower the bar back to shoulder height with control.\n4. Avoid arching your back excessively; keep the bar path vertical.',
  ),
  ExercisePoolEntry(
    id: 'upper_cable_face_pulls',
    name: 'Face Pulls',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.traps,
    ],
    compatibleSplits: {
      'Upper Body',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts, Traps**\n\n1. Attach a rope to a high pulley, set at about face height.\n2. Grasp the rope with both hands and step back to create tension.\n3. Pull the rope towards your face, keeping your elbows high and hands beside your ears.\n4. Squeeze your shoulder blades together at the peak, then slowly return.',
  ),
];
