// lib/engines/workout_engine/shared/exercises/catalog/definitions/shoulders_exercises.dart
// ⚠️ AUTO-GENERATED – DO NOT EDIT MANUALLY

import 'package:gymgenius/domain/enums/exports.dart';
import 'package:gymgenius/engines/workout_engine/shared/exercise_pool_entry.dart';

/// Canonical definitions for shoulders exercises.
const List<ExercisePoolEntry> shouldersDefinitions = [
  ExercisePoolEntry(
    id: 'arms_bw_plank_shoulder_taps',
    name: 'Plank Shoulder Taps',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Arms',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.core,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.alternating,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps, Core**\n\n1. Plank position.\n2. Lift one hand to tap opposite shoulder.\n3. Alternate.',
  ),
  ExercisePoolEntry(
    id: 'arms_bw_wall_handstand_hold',
    name: 'Wall Handstand Hold',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Arms',
    },
    usesWeight: false,
    isTimed: true,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.isometric,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Kick up into a handstand with feet on a wall.\n2. Keep arms straight and core tight.\n3. Hold for time.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_bb_barbell_shrugs',
    name: 'Barbell Shrugs',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Trapezius**\n\n1. Hold a barbell in front of your thighs.\n2. Shrug your shoulders up towards your ears.',
  ),
  ExercisePoolEntry(
    id: 'back_biceps_smith_shrugs',
    name: 'Smith Machine Shrugs',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Back & Biceps',
      'Pull',
      'Upper Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Traps**\n\n1. Stand with Smith bar at thigh height.\n2. Shrug shoulders up towards ears.',
  ),
  ExercisePoolEntry(
    id: 'chest_triceps_band_face_pull',
    name: 'Band Face Pull',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.back,
    ],
    secondaryMuscles: [
      MuscleGroup.traps,
    ],
    compatibleSplits: {
      'Chest & Triceps',
      'Push',
      'Shoulders',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts, Traps**\n\n1. Anchor a band at face height.\n2. Pull the band towards your face, elbows high.\n3. Squeeze, then return.',
  ),
  ExercisePoolEntry(
    id: 'pull_db_dumbbell_shrugs',
    name: 'Dumbbell Shrugs',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Trapezius**\n\n1. Hold a dumbbell in each hand at your sides.\n2. Shrug your shoulders straight up towards your ears.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'pull_kb_shrugs',
    name: 'Kettlebell Shrugs',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Pull',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Traps**\n\n1. Hold a kettlebell in each hand at your sides.\n2. Shrug your shoulders straight up towards your ears.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'push_band_lateral_raises',
    name: 'Band Lateral Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Side Shoulders**\n\n1. Stand on the band, holding a handle in each hand at your sides.\n2. Raise your arms laterally to shoulder height.\n3. Lower with control against the band tension.',
  ),
  ExercisePoolEntry(
    id: 'push_band_overhead_press',
    name: 'Band Overhead Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Upper Body',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Stand on the band, hold handles at shoulder height.\n2. Press overhead until arms are extended.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'push_bb_overhead_barbell_press',
    name: 'Overhead Barbell Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Stand holding a barbell at shoulder height, hands just outside shoulders.\n2. Press the bar overhead until arms are fully extended.\n3. Lower back to shoulder height with control.',
  ),
  ExercisePoolEntry(
    id: 'push_bw_pike_push_ups',
    name: 'Pike Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Push',
      'Shoulders',
      'Upper Body',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Start in a downward-dog position, hips high, hands shoulder-width apart.\n2. Bend your elbows to lower the top of your head towards the floor.\n3. Press back up to the starting position.',
  ),
  ExercisePoolEntry(
    id: 'push_cable_lateral_raise',
    name: 'Cable Lateral Raise',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Side Shoulders**\n\n1. Stand sideways to a low pulley, handle in the outside hand.\n2. Raise your arm laterally to shoulder height.\n3. Lower with control, then switch sides.',
  ),
  ExercisePoolEntry(
    id: 'push_db_arnold_press',
    name: 'Arnold Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Shoulders',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders (all heads), Triceps**\n\n1. Sit with dumbbells in front of your shoulders, palms facing you.\n2. Press upward while rotating your palms to face forward.\n3. Reverse the rotation as you lower back down.',
  ),
  ExercisePoolEntry(
    id: 'push_db_lateral_raises',
    name: 'Lateral Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Side Shoulders**\n\n1. Stand with dumbbells at your sides, palms facing in.\n2. Raise the dumbbells laterally to shoulder height.\n3. Lower them slowly back to start.',
  ),
  ExercisePoolEntry(
    id: 'push_db_shoulder_press',
    name: 'Shoulder Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Shoulders',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Sit on a bench with back support, dumbbells at shoulder height.\n2. Press the weights overhead until arms are extended.\n3. Lower them back to shoulder height with control.',
  ),
  ExercisePoolEntry(
    id: 'push_kb_arnold_press',
    name: 'Kettlebell Arnold Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders (all heads), Triceps**\n\n1. Hold kettlebells in front of shoulders, palms facing you.\n2. Press up while rotating palms to face forward.\n3. Reverse on the way down.',
  ),
  ExercisePoolEntry(
    id: 'push_kb_bottoms_up_press',
    name: 'Kettlebell Bottoms-Up Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.absCore,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Core**\n\n1. Hold a kettlebell upside down by the handle (bell at the top).\n2. Press it overhead, keeping it stable.\n3. Lower with control, switch sides.',
  ),
  ExercisePoolEntry(
    id: 'push_kb_kettlebell_overhead_press',
    name: 'Kettlebell Overhead Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Rack a kettlebell against your forearm at shoulder height.\n2. Press it overhead until your arm is fully extended.\n3. Lower back to the rack position with control.',
  ),
  ExercisePoolEntry(
    id: 'push_kb_push_press',
    name: 'Kettlebell Push Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.kettlebell,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Push',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps, Quads**\n\n1. Rack kettlebells at shoulders, dip by bending knees.\n2. Drive up explosively and press overhead.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'push_selector_machine_shoulder_press',
    name: 'Machine Shoulder Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Sit at the shoulder press machine, grips at shoulder height.\n2. Press upward until arms are extended.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'push_smith_shoulder_press',
    name: 'Smith Machine Shoulder Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.smithMachine,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Push',
      'Upper Body',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Sit on a bench under the Smith bar.\n2. Press the bar overhead along the fixed path.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_band_front_raise',
    name: 'Band Front Raise',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Front Shoulders**\n\n1. Stand on a band, hold handles in front of your thighs.\n2. Raise your arms forward to shoulder height.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_band_lateral_raise',
    name: 'Band Lateral Raise',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Side Shoulders**\n\n1. Stand on a band, hold handles at your sides.\n2. Raise arms out to the sides to shoulder height.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_band_shoulder_press',
    name: 'Band Shoulder Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Stand on a band, hold handles at shoulder height.\n2. Press overhead until arms are straight.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_band_upright_row',
    name: 'Band Upright Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.resistanceBands,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Traps**\n\n1. Stand on a band, hold handles with overhand grip.\n2. Pull the band straight up towards your chin, elbows leading.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_bw_handstand_push_ups',
    name: 'Handstand Push-ups (against wall)',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Kick up into a handstand against a wall.\n2. Lower your head towards the floor.\n3. Press back up to full extension.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_bw_pike_push_ups_feet_elevated',
    name: 'Elevated Pike Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.advanced,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Place feet on a raised surface (bench, chair).\n2. Perform a pike push-up with increased range of motion.\n3. Lower head as far as possible, then press back up.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_bw_pseudo_planche_push_ups',
    name: 'Pseudo Planche Push-ups',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Chest**\n\n1. Start in a push-up position with hands placed closer to hips.\n2. Lean forward, keeping body straight.\n3. Perform a push-up, then return.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_bw_wall_walks',
    name: 'Wall Walks',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.bodyweight,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.chest,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    usesWeight: false,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.closedChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Chest**\n\n1. Start in a push-up position facing a wall.\n2. Walk your feet up the wall while walking your hands back.\n3. Reach a handstand position, then return with control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_cable_front_raise',
    name: 'Cable Front Raise',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.unilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Front Shoulders**\n\n1. Attach a D-handle to a low pulley.\n2. Facing the pulley, raise your arm straight forward to shoulder height.\n3. Lower with control and switch sides.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_cable_reverse_fly',
    name: 'Cable Reverse Fly',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
      MuscleGroup.back,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.transverse,
    description: '**Target: Rear Delts**\n\n1. Set two cables at shoulder height.\n2. Cross the handles, pull them out to the sides.\n3. Squeeze shoulder blades and return.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_cable_upright_row',
    name: 'Cable Upright Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.cableMachinePulley,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Traps**\n\n1. Attach a straight bar to a low pulley.\n2. Stand facing the pulley, grip the bar with overhand grip.\n3. Pull the bar up towards your chin, elbows leading.\n4. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_core_bb_military_press',
    name: 'Military Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.chest,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Stand with barbell resting on front shoulders.\n2. Press the bar overhead to full extension.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_core_bb_overhead_carry',
    name: 'Overhead Barbell Carry',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.absCore,
    ],
    secondaryMuscles: [
      MuscleGroup.triceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: true,
    movementPattern: MovementPattern.carry,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Core**\n\n1. Press a barbell overhead and hold it locked out.\n2. Walk forward for a set distance or time.\n3. Keep core braced and shoulders stable.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_core_bb_push_press',
    name: 'Push Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
      MuscleGroup.quadriceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Heavy',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps, Quads**\n\n1. Dip slightly by bending knees.\n2. Drive up explosively and press the bar overhead.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_core_bb_upright_row',
    name: 'Barbell Upright Row',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.barbellAndPlates,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Traps**\n\n1. Grip barbell with overhand grip, hands shoulder-width.\n2. Pull the bar up towards your chin, elbows leading.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_core_db_front_raises',
    name: 'Front Raises',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Front Shoulders**\n\n1. Raise dumbbells in front to shoulder height.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_core_db_upright_rows',
    name: 'Upright Rows',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.intermediate,
    equipmentType: EquipmentType.dumbbells,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
      MuscleGroup.biceps,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Traps**\n\n1. Hold dumbbells in front of your thighs.\n2. Pull them straight up towards your chin, elbows leading.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_selector_front_raise',
    name: 'Selectorized Front Raise',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Front Shoulders**\n\n1. Sit on the machine, grip handles.\n2. Raise arms forward to shoulder height.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_selector_lateral_raise',
    name: 'Selectorized Lateral Raise',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.shoulders,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Light',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.frontal,
    description: '**Target: Side Shoulders**\n\n1. Sit on the machine, arms against the pads.\n2. Raise arms out to the sides.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_selector_shoulder_press',
    name: 'Selectorized Shoulder Press',
    category: ExerciseCategory.compound,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.shoulders,
      MuscleGroup.triceps,
    ],
    secondaryMuscles: [
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.push,
    mechanics: Mechanics.openChain,
    forceType: ForceType.push,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Shoulders, Triceps**\n\n1. Sit at the machine, grip handles.\n2. Press overhead.\n3. Lower with control.',
  ),
  ExercisePoolEntry(
    id: 'shoulders_selector_shrugs',
    name: 'Selectorized Shrugs',
    category: ExerciseCategory.isolation,
    difficulty: ExerciseDifficulty.beginner,
    equipmentType: EquipmentType.gymMachinesSelectorized,
    targetMuscles: [
      MuscleGroup.traps,
    ],
    secondaryMuscles: [
      MuscleGroup.shoulders,
    ],
    compatibleSplits: {
      'Shoulders',
    },
    weightSuggestion: 'Moderate',
    usesWeight: true,
    isTimed: false,
    movementPattern: MovementPattern.pull,
    mechanics: Mechanics.openChain,
    forceType: ForceType.pull,
    laterality: Laterality.bilateral,
    planeOfMotion: PlaneOfMotion.sagittal,
    description: '**Target: Traps**\n\n1. Stand or sit on the machine, grip handles.\n2. Shrug your shoulders up towards your ears.\n3. Hold for a second, then lower with control.',
  ),
];
